### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zyiang1928** [eritislami/evobot#100]
what if not everyone can use the skip or stop command when music is playing like only someone is asking for music then others cannot use the skip or stop command until the music stops.

Can it be done?

**Comment by eritislami** [comment]
Yes this can be done by checking for roles like DJ or server admins but i can't say when this will be added, this is a good suggestion though so it's very likely to be worked on soon.

**Comment by zyiang1928** [comment]
Wowww okay, no need to worry I will wait for you to make it as I suggested, of course that's good advice and will make bots better than before

**Comment by dmason94** [comment]
Just came across this feature request, I would certainly like to see this added as well, if possible. I know parts of the code but not sure where to implement the code. Any help would be appreciated if possible (FYI - very nice code and bot by the way :D)

**Comment by razeNFR** [comment]
Any news of this feature ? I want to do this too :)

**Comment by zyiang1928** [comment]
It is not certain when this feature will be released, please be patient

Pada tanggal Min, 13 Sep 2020 00.00, razeNFR <notifications@github.com>
menulis:

**Comment by wolf-yuan-6115** [comment]
Well, this feature is good!
