### ISSUE TITLE
REMINDER : SoundCloud Feature will not be available

### ISSUE THREAD

**Issue by DirectX-Luck** [eritislami/evobot#101]
Sound Cloud will not accept more new Apps till they announces. So, I don't think we can use the Sound Cloud Tracker.

**Comment by ParasDeshpande** [comment]
No, you don't have to do that just go to their website and get your account's client id instead of getting the id that they give for apps.... Check #93 for more info...

**Comment by eritislami** [comment]
Creating an app is not required and it's optional
