### ISSUE TITLE
Bug: Issue with /q or /que

### ISSUE THREAD

**Issue by Technologx** [eritislami/evobot#1024]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. Do /q after adding several songs
 
**Expected behavior**
A description of what you expected to happen.
I expect to see a list of the songs added to the que.

**Environment (add if possible)**
* Node.js version: Current

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
(node:55214) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/Users/djblaze/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at Object.execute (/Users/Desktop/djblaze/commands/queue.js:20:46)
    at Client.client.on (/Users/Desktop/djblaze/index.js:82:13)
    at Client.emit (events.js:198:13)
(node:55214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:55214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AbelCode1** [comment]
> **Describe the bug** A description of what the bug is.
> 
> **How To Reproduce** Steps to reproduce the behavior:
> 
> 1. Do /q after adding several songs
> 
> **Expected behavior** A description of what you expected to happen. I expect to see a list of the songs added to the que.
> 
> **Environment (add if possible)**
> 
> * Node.js version: Current
> 
> **Additional information & screenshots** Add any other context or screenshots about the problem here. (node:55214) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function at Function.normalizeFields (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:450:8) at MessageEmbed.setup (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:78:91) at new MessageEmbed (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/MessageEmbed.js:18:10) at embedLikes.map.e (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/APIMessage.js:166:40) at Array.map () at APIMessage.resolveData (/Users/djblaze/node_modules/discord.js/src/structures/APIMessage.js:166:31) at TextChannel.send (/Users/Desktop/djblaze/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62) at Object.execute (/Users/Desktop/djblaze/commands/queue.js:20:46) at Client.client.on (/Users/Desktop/djblaze/index.js:82:13) at Client.emit (events.js:198:13) (node:55214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) (node:55214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It works fine for me

**Comment by AbelCode1** [comment]
Use this code



const { MessageEmbed } = require("discord.js");
const i18n = require("../util/i18n");

module.exports = {
  name: "queue",
  cooldown: 5,
  aliases: ["q"],
  description: i18n.__("queue.description"),
  async execute(message) {
    const permissions = message.channel.permissionsFor(message.client.user);
    if (!permissions.has(["MANAGE_MESSAGES", "ADD_REACTIONS"]))
      return message.reply(i18n.__("queue.missingPermissionMessage"));

    const queue = message.client.queue.get(message.guild.id);
    if (!queue) return message.channel.send(i18n.__("queue.errorNotQueue"));

    let currentPage = 0;
    const embeds = generateQueueEmbed(message, queue.songs);

    const queueEmbed = await message.channel.send(
      `**${i18n.__mf("queue.currentPage")} ${currentPage + 1}/${embeds.length}**`,
      embeds[currentPage]
    );

    try {
      await queueEmbed.react("⬅️");
      await queueEmbed.react("⏹");
      await queueEmbed.react("➡️");
    } catch (error) {
      console.error(error);
      message.channel.send(error.message).catch(console.error);
    }

    const filter = (reaction, user) =>
      ["⬅️", "⏹", "➡️"].includes(reaction.emoji.name) && message.author.id === user.id;
    const collector = queueEmbed.createReactionCollector(filter, { time: 60000 });

    collector.on("collect", async (reaction, user) => {
      try {
        if (reaction.emoji.name === "➡️") {
          if (currentPage < embeds.length - 1) {
            currentPage++;
            queueEmbed.edit(
              i18n.__mf("queue.currentPage", { page: currentPage + 1, length: embeds.length }),
              embeds[currentPage]
            );
          }
        } else if (reaction.emoji.name === "⬅️") {
          if (currentPage !== 0) {
            --currentPage;
            queueEmbed.edit(
              i18n.__mf("queue.currentPage", { page: currentPage + 1, length: embeds.length }),
              embeds[currentPage]
            );
          }
        } else {
          collector.stop();
          reaction.message.reactions.removeAll();
        }
        await reaction.users.remove(message.author.id);
      } catch (error) {
        console.error(error);
        return message.channel.send(error.message).catch(console.error);
      }
    });
  }
};

function generateQueueEmbed(message, queue) {
  let embeds = [];
  let k = 10;

  for (let i = 0; i < queue.length; i += 10) {
    const current = queue.slice(i, k);
    let j = i;
    k += 10;

    const info = current.map((track) => `${++j} - [${track.title}](${track.url})`).join("\n");

    const embed = new MessageEmbed()
      .setTitle(i18n.__("queue.embedTitle"))
      .setThumbnail(message.guild.iconURL())
      .setColor("#F8AA2A")
      .setDescription(
        i18n.__mf("queue.embedCurrentSong", { title: queue[0].title, url: queue[0].url, info: info })
      )
      .setTimestamp();
    embeds.push(embed);
  }

  return embeds;
}

**Comment by eritislami** [comment]
@AbelCode1 it has nothing to do with the code, @Technologx is your node.js version 14 or higher?

**Comment by Technologx** [comment]
I installed 8.16.1 because all the other pkg files signing certificate was expired.

On Oct 31, 2021, 12:28 PM, at 12:28 PM, Erit Islami ***@***.***> wrote:
***@***.*** it has nothing to do with the code, @Technologx is your

**Comment by eritislami** [comment]
> I installed 8.16.1 because all the other pkg files signing certificate was expired. On Oct 31, 2021, 12:28 PM, at 12:28 PM, Erit Islami ***@***.***> wrote: ***@***.*** it has nothing to do with the code, @Technologx is your
> […](#)
> node.js version 14 or higher? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#1024 (comment)](https://github.com/eritislami/evobot/issues/1024#issuecomment-955760893)

You need node.js 14 or higher to run the bot

**Comment by Technologx** [comment]
My node is 10.16.1 and npm is 6.9.0
