### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by raphaapha** [eritislami/evobot#1025]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. make the command pause
2. do the resume command
 
**Expected behavior**
A description of what you expected to happen.
I expected the music to pick up

**Environment (add if possible)**
* Node.js version: v16.11.1

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by raphaapha** [comment]
The resume command does not resume the music paused, it displays the message that the music resumes but it does not matter

**Comment by eritislami** [comment]
It's up to the discord.js maintainers to fix that, I can't do anything about it, I'm just using their library to provide the feature.

**Comment by AbelCode1** [comment]
> It's up to the discord.js maintainers to fix that, I can't do anything about it, I'm just using their library to provide the feature.

But it works fine on replit but not good else where
