### ISSUE TITLE
Bug: Error 

### ISSUE THREAD

**Issue by AbelCode1** [eritislami/evobot#1026]
![Uploading 7A4D87C1-6FFA-44F7-9304-C382B3206CAF.jpeg…]()

**Comment by AbelCode1** [comment]
![1F083657-BA21-4DC5-AF9C-147415F82982](https://user-images.githubusercontent.com/90580222/139596601-e54431d8-4bfc-4270-82cf-d1afbc32ddc2.jpeg)

**Comment by eritislami** [comment]
Not a bug, 403/404 the video you are trying to play can't be reached or is restricted.

**Comment by AbelCode1** [comment]
> Not a bug, 403/404 the video you are trying to play can't be reached or is restricted.

Ohh but i have a playlist on loop and the songs play then after awhile the songs start skipping then the bot crashes after

**Comment by Gamebuster19901** [comment]
Same. I sometimes get HTTP 403 response when I play a song using a large playlist (171 shuffled songs). I can stop the playlist and then play the song that was skipped individually, and It plays fine. It never crashes for me though.
