### ISSUE TITLE
Spotify Support

### ISSUE THREAD

**Issue by Technologx** [eritislami/evobot#1027]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]
No problems

**Describe the solution you'd like**
A description of what you want to happen.
/sp Cake By The Ocean DNCE 

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

I hope I filled this out correctly, I was just hoping to get spotify support added. So users can play from youtube or spotify.

**Comment by imlarx** [comment]
@Technologx Spotify does not support streaming from its platform. What music bots on Discord do is, they query requests from Spotify API and find the song from YouTube and play it.

**Comment by eritislami** [comment]
Currently not planning to work or maintain this type of feature, I believe others have a potentially working version
