### ISSUE TITLE
Bug: code error 410

### ISSUE THREAD

**Issue by etamkcehc** [eritislami/evobot#1028]
**Describe the bug**
I am not sure it is a bug or not. I used the code for music bot on discord since this September but at this afternoon the bot is showing error code 410 whenever I play YouTube video. Soundcloud works perfectly fine.

**How To Reproduce**
1.  Requested for a bot to play music
2.
 
**Expected behavior**
Not sure if I play something that crashed with YouTube policy and it automatically blocked the bot

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/93592487/139850750-1b6b6a35-c3fb-45da-a064-5050c4f861b0.png)

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/issues?q=is%3Aissue+410+
