### ISSUE TITLE
Enhancement: Set [connection.voice.setSelfDeaf] in commands/(play.js & playlist.js) to true to save bandwidth and avoid audio lag due to high bandwidth usage.

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#103]
‎

**Comment by eritislami** [comment]
So are you going to explain how this works, why would self defeaning save bandwidth/prevent lag ?
Did you test this and can show anything ?

**Comment by ParasDeshpande** [comment]
Well i was running this on a really trash server with very low bandwidth and the audio was lagging when the bot was being used in more than 5-6 servers.. After adding this the audio lag was fixed, not sure if that was the exact reason but groovy also does the same...  I guess discord sends the audio in the voice channel to the bot which uses bandwidth...

![image](https://user-images.githubusercontent.com/63962807/85914278-9cc55680-b859-11ea-8033-10c876b88536.png)


![image](https://user-images.githubusercontent.com/63962807/85914258-6e477b80-b859-11ea-9e89-12183cab61fe.png)

**Comment by eritislami** [comment]
Added in 08732c259087951577f913c2794368c8fef47cff
