### ISSUE TITLE
Bug: 2 vulnerabilities required manual review

### ISSUE THREAD

**Issue by johnq111** [eritislami/evobot#1033]
**Describe the bug**
When I did npm install it returned in vulerability message and could not be fix by npm audit fix. Please guide how to fix it.

  2 vulnerabilities required manual review and could not be updated
![image](https://user-images.githubusercontent.com/93890228/140668226-bce5ee67-012d-4fc9-ba06-36bbcce7adba.png)

**Comment by Moazlion** [comment]
It’s the same for me anyone know fix?

**Comment by Velosofy** [comment]
It's the same for everybody.. just ignore it

**Comment by johnq111** [comment]
> It's the same for everybody.. just ignore it

but without fixing the vulnerability, the code couldnt be run; bot cannot run

**Comment by eritislami** [comment]
It's a developer dependency, use `npm install --production` to skip it.
