### ISSUE TITLE
Bug: major error when playing 

### ISSUE THREAD

**Issue by AbelCode1** [eritislami/evobot#1036]
![E92B8672-F76F-49BF-A4A9-B928F8B1C3DB](https://user-images.githubusercontent.com/90580222/141027439-cccfef15-0bc5-4748-b0fd-4a1a8e282bbe.jpeg)

**Comment by AbelCode1** [comment]
![FEE38B65-F3AD-48E4-A9E2-2579B5031B64](https://user-images.githubusercontent.com/90580222/141027497-a1774ed4-d497-43c8-b99d-f26bba151e58.jpeg)

**Comment by Velosofy** [comment]
Changing your youtube token might help
