### ISSUE TITLE
Muti page help embed

### ISSUE THREAD

**Issue by Fakepng** [eritislami/evobot#1037]
I add a lot of commands more than 25 embed limit so my command gets cut off.
If anyone can help me pls consider helping.

**Comment by arthurvanl** [comment]
What do u mean exactly? Can u show some code or results u may have?

**Comment by Fakepng** [comment]
like this![image](https://user-images.githubusercontent.com/86796781/145213738-0b19d4ca-f0fd-417c-9daf-713176e9b462.png)

**Comment by eritislami** [comment]
Closing as old and not planned.
