### ISSUE TITLE
Pause/unpause

### ISSUE THREAD

**Issue by Diego77648** [eritislami/evobot#1038]
I dont know if this only happens to me, but when I pause I cant unpause the music I cant fix it by myself :/

**Comment by AbelCode1** [comment]
it happens to me too , what happens it actually unpause the music but without the sound

**Comment by AnimeAbout** [comment]
Use node version 14.15.4

**Comment by AbelCode1** [comment]
> Use node version 14.15.4

I did it still not working

**Comment by AnimeAbout** [comment]
https://youtu.be/X9r402LqUwk

**Comment by AbelCode1** [comment]
> https://youtu.be/X9r402LqUwk

Still doesnt work

**Comment by eritislami** [comment]
This was already discussed in other issues
