### ISSUE TITLE
Issue with creating an Thumbnail in Embed [Song Thumbnail]

### ISSUE THREAD

**Issue by DirectX-Luck** [eritislami/evobot#104]
Hello, I have made an Embed to fix the system as I want. As a result I used the below code to fix the setThumbnail Fuction. 
`.setThumbnail("queue.songs[0].thumbnail")` [Currently Using]
`.setThumbnail("song.thumbnail")` 

None of above is working correctly. Please lend me an help. Thanks

**Comment by ParasDeshpande** [comment]
check #49 i already did it... Mine works fine

**Comment by DirectX-Luck** [comment]
oh, I forgot to define the thumbnail as you did, Thanks for informing, Appreciated!
