### ISSUE TITLE
not playing music form youtube 

### ISSUE THREAD

**Issue by FForion** [eritislami/evobot#1041]
(node:370) UnhandledPromiseRejectionWarning: Error: Error: Cannot find module '/home/runner/evobot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24/opus.node'
Require stack:
- /home/runner/evobot/node_modules/@discordjs/opus/lib/index.js
- /home/runner/evobot/node_modules/prism-media/src/util/loader.js
- /home/runner/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/runner/evobot/node_modules/prism-media/src/opus/index.js
- /home/runner/evobot/node_modules/prism-media/src/index.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/runner/evobot/node_modules/discord.js/src/client/Client.js
- /home/runner/evobot/node_modules/discord.js/src/index.js
- /home/runner/evobot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/runner/evobot/node_modules/prism-media/src/util/loader.js
- /home/runner/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/runner/evobot/node_modules/prism-media/src/opus/index.js
- /home/runner/evobot/node_modules/prism-media/src/index.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/runner/evobot/node_modules/discord.js/src/client/Client.js
- /home/runner/evobot/node_modules/discord.js/src/index.js
- /home/runner/evobot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/runner/evobot/node_modules/prism-media/src/util/loader.js
- /home/runner/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/runner/evobot/node_modules/prism-media/src/opus/index.js
- /home/runner/evobot/node_modules/prism-media/src/index.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/runner/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/runner/evobot/node_modules/discord.js/src/client/Client.js
- /home/runner/evobot/node_modules/discord.js/src/index.js
- /home/runner/evobot/index.js
    at Object.loader [as require] (/home/runner/evobot/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/runner/evobot/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/runner/evobot/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Decoder (/home/runner/evobot/node_modules/prism-media/src/opus/Opus.js:183:1)
    at AudioPlayer.playOpusStream (/home/runner/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:73:23)
    at VoiceConnection.play (/home/runner/evobot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:75:28)
    at play (/home/runner/evobot/include/play.js:61:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AbelCode1** [comment]
Install the packages

**Comment by Velosofy** [comment]
RTFM

**Comment by AbelCode1** [comment]
> RTFM
opusscript & node-opus
