### ISSUE TITLE
Lavalink 

### ISSUE THREAD

**Issue by AbelCode1** [eritislami/evobot#1047]

**Comment by AbelCode1** [comment]
Turn bot into lavalink because of youtube api keeps getting blocked

**Comment by AbelCode1** [comment]
youtube-sr not fetching data as expected

**Comment by Goldenfreddy0703** [comment]
Im sorry to say this but lavalink is definitely a huge issue for some reason. I tried other music bots with lavalink and they are always problems. Live streams don't work with them sometimes and soundcloud does not work well or with spotify either. Lavalink is just the worst for me tbh. If i were me, i would use #991 then installing lavalink sense its a hassle.

**Comment by eritislami** [comment]
Closing as this is irrelevant to the future of the bot at this moment

**Comment by Goldenfreddy0703** [comment]
Holy crap I thought the owner was dead. Welcome back and it's nice to see you again.
