### ISSUE TITLE
Bug: Pause Music, Will not resume without totally stopping the queue

### ISSUE THREAD

**Issue by LouieBigBoi** [eritislami/evobot#1051]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.Pause Music
2.Attempt to resume 
 
**Expected behavior**
A description of what you expected to happen.
Music To resume
**Environment (add if possible)**
* Node.js version: 14

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by AbelCode1** [comment]
> **Describe the bug** A description of what the bug is.
> 
> **How To Reproduce** Steps to reproduce the behavior: 1.Pause Music 2.Attempt to resume
> 
> **Expected behavior** A description of what you expected to happen. Music To resume **Environment (add if possible)**
> 
> * Node.js version: 14
> 
> **Additional information & screenshots** Add any other context or screenshots about the problem here.

Where do you host your bit?

**Comment by LouieBigBoi** [comment]
Hetzner Cloud Servers.

**Comment by PandaIN95** [comment]
Use **Node 14.15.4** for resume functionality to work.

**Comment by eritislami** [comment]
Try @PandaIN95 's suggestion otherwise, you can read more about this in existing closed issues, there is nothing to be done right now regarding code changes
