### ISSUE TITLE
Bug: Missing Permissions does anyone know how to fix it?

### ISSUE THREAD

**Issue by Annguyen1qqq** [eritislami/evobot#1054]
*DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/runner/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'delete',
  path: '/channels/898415613666533377/messages/913321616161787904/reactions',
  code: 50013,
  httpStatus: 403
}

**Comment by AbelCode1** [comment]
The bot doesnt have the correct permissions enabled 

> *DiscordAPIError: Missing Permissions
> at RequestHandler.execute (/home/runner/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async RequestHandler.push (/home/runner/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
> method: 'delete',
> path: '/channels/898415613666533377/messages/913321616161787904/reactions',
> code: 50013,
> httpStatus: 403
> }

**Comment by eritislami** [comment]
For easy fix give it administrator permissions in your server, or set each permission manually. Also not a bug.
