### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by mahdilupo** [eritislami/evobot#1055]
please add autoplay !!
your code is awsome but needs a default autoplay

**Comment by Velosofy** [comment]
What autoplay?
The bot play the song as soon you give it a link

**Comment by mahdilupo** [comment]
as soon as music ends. bot plays similar music from youtube 
like this: https://github.com/Tomato6966/Musicium

**Comment by mahdilupo** [comment]
https://pastebin.com/q3mR2Siy

**Comment by eritislami** [comment]
Closing as this is irrelevant to the future of the bot at this moment
