### ISSUE TITLE
The bot sends NSFW content to non-NSFW channels.

### ISSUE THREAD

**Issue by ABotDev** [eritislami/evobot#106]

**Comment by eritislami** [comment]
Really no idea what you mean here, mind explaining your issue?

**Comment by NickaDev** [comment]
there is 18+ content on youtube so if you do !play porn the thumbnail will show.

**Comment by eritislami** [comment]
On this line you can add angle brackets "<" ">" around the song url to prevent it from expanding the metadata in discord
https://github.com/eritislami/evobot/blob/edb20cb6e6f449a61e38b3225ac846ff639e0432/include/play.js#L64
```js
var playingMessage = await queue.textChannel.send(`🎶 Started playing: **${song.title}** <${song.url}>`);
```

Other than that i don't plan to code filters to prevent this

**Comment by NickaDev** [comment]
Okay. I will try to make a filter tho but i will see if its going to work tho.
