### ISSUE TITLE
Bug: Two prefixes 

### ISSUE THREAD

**Issue by BfGanimeshnik** [eritislami/evobot#1066]
**Describe the bug**
Instead of a single prefix "b!" I also have the prefix ".", and if you use the prefix "." then the bot gives errors

**How To Reproduce**
1. I launch the bot, and I already have 2 prefixes at once, I use the ru version
 
**Expected behavior**
The bot should have used 1 prefix "b!", but instead it has 2 of them

**Environment (add if possible)**
* Node.js version: 16.13.1

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/55851088/146676388-0196ec12-7314-4449-ae22-68edf1b51615.png)
![image](https://user-images.githubusercontent.com/55851088/146676392-d5d1d0ad-5bdf-45d1-b134-551769c4f044.png)
![image](https://user-images.githubusercontent.com/55851088/146676408-d4ad1fe5-d33a-4069-8eb4-73b8c85a98cd.png)
![image](https://user-images.githubusercontent.com/55851088/146676414-1050bb93-5faa-4da2-a549-d53e5e97b0b3.png)

**Comment by eritislami** [comment]
The error in your last screenshot has nothing to do with the prefix, the fact that ytdl could not get video metadata doesn't mean the prefix doesn't work, it's just a coincidence, I have just one question, can you reproduce this easily or does it happen randomly with some videos?

**Comment by BfGanimeshnik** [comment]
If I just enter a link, it gives this error, when I enter a name, it doesn’t exist.
But with my normal prefix, there is no such thing, everything works well. I don’t understand at all where I got the prefix in the form of a dot.

**Comment by eritislami** [comment]
> If I just enter a link, it gives this error, when I enter a name, it doesn’t exist. But with my normal prefix, there is no such thing, everything works well. I don’t understand at all where I got the prefix in the form of a dot.

Could have two processes running

**Comment by BfGanimeshnik** [comment]
No, I have 1 process running

**Comment by BfGanimeshnik** [comment]
![image](https://user-images.githubusercontent.com/55851088/146828245-223ee198-1331-4409-bd18-f38f59581ad0.png)
