### ISSUE TITLE
Bug: Console log on search timeout

### ISSUE THREAD

**Issue by Sparker-99** [eritislami/evobot#108]
Ok so while i was debugging the bot on vs i found an unknown console log occurs while search command timeout after 30 seconds.

The log:

```
null: Map(0) {_array: null, _keyArray: null}
_array: null
_keyArray: null
[[Entries]]: Array(0)
: No debug adapter, can not send 'variables'
size: 0
__proto__: Map {constructor: , toJSON: }
: No debug adapter, can not send 'variables'
```
Kindly have a look to it

**Comment by eritislami** [comment]
https://github.com/discordjs/discord.js/blob/stable/src/structures/interfaces/TextBasedChannel.js#L300

It console logs the map because the collector ended, thats the way its written in discord.js, its inteded behaviour
This is what i get in my console

![](https://i.imgur.com/8yybHzP.png)

**Comment by Sparker-99** [comment]
Alright thats what i wanted to know

**Comment by Sparker-99** [comment]
Alright thats what i wanted to know
