### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by mahdilupo** [eritislami/evobot#1083]
add spotify support if its possible

**Comment by wolf-yuan-6115** [comment]
Yes, it is possible. But we can only get track name from Spotify, that means we unable to get track audio. Solution is searching track name on YouTube and play from YouTube.

**Comment by mahdilupo** [comment]
yeah I know how spotify api works but sometimes adding spotify playlist is better than entering names one by one.

**Comment by Rayrsn** [comment]
https://github.com/eritislami/evobot/pull/590 this is already implemented

**Comment by Velosofy** [comment]
Why the downvote? You can just simply merge the commits from other repo to yours and deploy the bot normally

**Comment by eritislami** [comment]
Closing as old and not planned.
