### ISSUE TITLE
All locale files "clip" command uses hard coded prefix

### ISSUE THREAD

**Issue by nishiua** [eritislami/evobot#1092]
For example, on line 4 of en.json there is,
`"usagesReply": "Usage: /clip <name>",`
when there should be,
`"usagesReply": "Usage: {prefix}clip <name>",`

This is not just only in the English locale but all.

**Comment by eritislami** [comment]
I have pushed this commit but didn't test it 9a0c2ef68064f083447918b0da3407e873cbf5e2
If you can let me know if it's ok

**Comment by nishiua** [comment]
Looks like it is working great! (Unusual languages like Arabic work too). 
After thinking about it, I'm sure it was just a typo. Thanks for creating a brilliant music bot.
