### ISSUE TITLE
Bug: Bot crash when can't add reactions

### ISSUE THREAD

**Issue by originalaidn** [eritislami/evobot#1093]
**Describe the bug**
When someone want to start music on bot, but if the bot can't add reactions to the message the bot crash.
Can fix the "Could not join the channel: undefined"? --> cantJoinChannel

**How To Reproduce**
BOT Crash:
1. Don't add role/permissions to the BOT
2. Start music on the BOT

Undefined join channel:
1. Leave channel and write !play
 
**Expected behavior**
BOT Crash:
The bot send a message, can't add reactions.

Undefined join channel:
"Could not join the channel: you aren't in voice channel."

**Comment by Velosofy** [comment]
This is invalid, when you try to queue a song but the bot doesn't have the permission to join your channel, it will send you a message about it - and it won't crash

![image](https://user-images.githubusercontent.com/61261357/150980805-ce8fda60-95ef-4fef-b962-da2433f3eb4a.png)

**Comment by Velosofy** [comment]
This is invalid per my testing

The bot does spit out error of not having the required permission to join voice channel, but it doesn't crash
![image](https://user-images.githubusercontent.com/61261357/150981104-a9fce8d1-d644-4cf1-a69a-400ad5e740db.png)
*you can see it doesn't crash because my terminal is still in `node`

**Comment by originalaidn** [comment]
> This is invalid per my testing
> 
> The bot does spit out error of not having the required permission to join voice channel, but it doesn't crash ![image](https://user-images.githubusercontent.com/61261357/150981104-a9fce8d1-d644-4cf1-a69a-400ad5e740db.png) *you can see it doesn't crash because my terminal is still in `node`

I speak about the reactions, not the permission to join voice channel, but my other bot no crashed if can't add reactions..
but the another "bug" still exists
