### ISSUE TITLE
Bug: Queue won't work

### ISSUE THREAD

**Issue by keepofthehause** [eritislami/evobot#1098]
**Describe the bug**
Attempting to use the queue command causes an error

**How To Reproduce**
1. Add some songs or add a playlist
2. Attempt to display the song queue, doing so will fail and give you an error in the bot console
 
**Expected behavior**
The queue should display correctly.

**Environment (add if possible)** Debian 10
* Node.js version: 10.24.0

**Comment by Velosofy** [comment]
Please update your node.js version to v14 or higher, it's a part of the requirement
