### ISSUE TITLE
Bug: No audio during playback (Both YouTube and MP3)

### ISSUE THREAD

**Issue by SugarD-x** [eritislami/evobot#1112]
**Describe the bug**
During playback, the bot outputs no audio even though it shows it trying to "speak" in the voice channel. I've noticed this with both YouTube videos and MP3 files in the `sounds` folder. Both the latest release version and the GitHub repository seem to have the issue for me.

**How To Reproduce**
1. Install a default copy of the bot from either the repository or the latest release.
2. Attempt to play any YouTube video or MP3 file from the `sounds` folder.
 
**Expected behavior**
To hear the audio.

**Environment (add if possible)**
* Node.js version: Both 16.8.0 and 17.6.0 appear affected.

**Comment by SugarD-x** [comment]
I host it directly on a Windows VPS that I manage. It used to work fine up until recently.

**Comment by SugarD-x** [comment]
This is still an issue for me. :P

**Comment by Velosofy** [comment]
Does it show any error output ? from the terminal perhaps?

**Comment by SugarD-x** [comment]
Nothing at all. It acts as if it is working fine on the application's end.

**Comment by eritislami** [comment]
Please try again with the current master branch and fresh packages, if this is still an issue for you I will re-open
