### ISSUE TITLE
Bug: source dead

### ISSUE THREAD

**Issue by pengengantibaju** [eritislami/evobot#1126]
> @discordjs/opus@0.7.0 install /root/evobot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v64-napi-v3-linux-x64-glibc-2.31.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.7.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v64-napi-v3-linux-x64-glibc-2.31.tar.gz

**Comment by Velosofy** [comment]
a more comprehensive report is highly appreciated

**Comment by eritislami** [comment]
Install `opusscript` instead of `@discordjs/opus`

`npm rm @discordjs/opus`
`npm install opusscript`
