### ISSUE TITLE
Bug: Open Chat (Voice Channel) feature causing crashes

### ISSUE THREAD

**Issue by DavidCarbon** [eritislami/evobot#1127]
**Describe the bug**
Open Chat (Voice Channel) packet causing crashes. The bot doesn't know how to handle the extra packet (chat message) from a voice call (more specifically while in the same voice call) 

**How To Reproduce**
1. Bot must be on a Server
2. Bot can either be in a Voice Call or On Standby
3. Open Chat
4. Send a message (either bot or generic)
5. Bot Crashes
 
**Expected behavior**
Bot either ignores the "Open Chat" messages or response to commands from it

**Environment (add if possible)**
* Node.js version: 14.19.1

**Additional information & screenshots**
Notes: Don't mind the other bot, the bot that is based off this repo had crashed to confirm the bug
Error Logs: https://mclo.gs/9lIbRpg
![image](https://user-images.githubusercontent.com/9911250/164619820-c333bc5b-7f39-4e28-ac72-03dc09e224cb.png)
![image](https://user-images.githubusercontent.com/9911250/164618551-76568ba4-45ef-4b76-8d3c-99483e202933.png)

**Comment by DavidCarbon** [comment]
Seems like [version 12](https://github.com/discordjs/discord.js/blob/v12/src/client/actions/MessageCreate.js) of Discord.js doesn't have the mitigation fix as seen in [version 13](https://github.com/discordjs/discord.js/blob/v13/src/client/actions/MessageCreate.js). Not sure if a fix is possible from our side, other than forking the code and manually applying the fix.

**Comment by Velosofy** [comment]
It seems like it's impossible to fix unless we upgrade to v13

**Comment by eritislami** [comment]
I will be publishing the v13 version soon, whether or not this bug will be automatically fixed is not sure

**Comment by wolf-yuan-6115** [comment]
Version 1.0.0 of evobot upgraded to v13, see https://github.com/eritislami/evobot/releases/tag/1.0.0

**Comment by DavidCarbon** [comment]
Will test the latest build later today, will follow up on if the bug is still present
