### ISSUE TITLE
Error: The YouTube API key you provided was not a string.

### ISSUE THREAD

**Issue by ItsCraftIsBored** [eritislami/evobot#1129]
**Describe the bug**
when i type node index.js
it says Error: The YouTube API key you provided was not a string.

**How To Reproduce**
1. type node index.js
 
**Expected behavior**
A description of what you expected to happen.
it should run normally

**Environment (add if possible)**
* Node.js version: npm 8.5.0
* Windows Server 2016

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by Velosofy** [comment]
Have you make sure the key you put into the config.json is the right key?

**Comment by ItsCraftIsBored** [comment]
oh actually i forgot to change the .txt to .json
