### ISSUE TITLE
Bug: Troubles trying to run the command,  "npm install"

### ISSUE THREAD

**Issue by JoJoSniper** [eritislami/evobot#113]
I end up getting this error when I attempt do it

PS C:\Users\jojof\OneDrive\Desktop\evobot-master> npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/derhuerst/http-basic.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

is there a fix?
I tried doing it on cmd and visual studio code, I'm on windows 10

**Comment by eritislami** [comment]
Install Git. https://git-scm.com/

**Comment by JoJoSniper** [comment]
Thanks! That fixed the problem! Do you have a discord server and or maybe some sort of donation I could give?

**Comment by eritislami** [comment]
No, thank you, i appreciate the comment
