### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mina9999** [eritislami/evobot#114]
1.add the bot to stay in voice chat or not and bot only use a text channel that we set with channel id in config.(its so annoying bot wont stay in vc or it join any voice chats)

2.set status be on or off and help in dms or chat.

3.default volume (it restart in every songs and we should set it again)

4.dj role for forceskip and vote skip for people in voice chat.

5.now playing in channel topic( discord have rate limit for this but still its ok)

all bots have thouse options i guess 

thank you

**Comment by rexjohannes** [comment]
5. U need a verified bot or u get really fast ratelimited

others are very good ideas

**Comment by AmadeusWolf** [comment]
@mina9999 i would also like to see the vote skip
