### ISSUE TITLE
Bug: Play command does not run playlist command when playlist is given.

### ISSUE THREAD

**Issue by nikosszzz** [eritislami/evobot#1141]
**Describe the bug**
Using the play command to start a playlist does not work.

**How To Reproduce**
1. Run normal !play command with a youtube playlist link.
2. The command continues as if it is given a search/video link instead of running the playlist command.
 
**Expected behavior**
It should run the playlist command with the given link from the play command.

**Environment (add if possible)**
* Node.js version: 16.14.2

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://user-images.githubusercontent.com/53112175/166137706-15100422-482f-457f-8bbe-111a4be4311b.png)

**Comment by nikosszzz** [comment]
I found a possible fix. The videoPattern pattern seems to cause the issue. As soon as I removed it, the command worked as it should.

Code here:
```
if ((playlistCheck.test(args[0])) ||
            (scdl.isValidUrl(url) && url.includes("/sets/")) || (spotifyPlaylistPattern.test(args[0]))
        ) {
            return message.client.commands.get("playlist").execute(message, args);
        } 
```

**Comment by eritislami** [comment]
Thanks i didn't think to test this after changing the regex
