### ISSUE TITLE
Bug: ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by kuonglemon** [eritislami/evobot#1143]
Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'

 Node.js version: 16.9.0 and 16.15.0

![2c21ba894eece8f66afec11e3a910b5](https://user-images.githubusercontent.com/81738923/166139927-5c325446-1de3-47ef-a8d7-7ddbdbee7049.png)

**Comment by eritislami** [comment]
I didn't think this would be an issue but I also didn't test it because I'm not developing on Windows, in the mean time I suggest you try to run the bot with docker

**Comment by SugarD-x** [comment]
Don't quote me on this, but I believe I got around this on another bot by using double slashes for Windows paths.

**Comment by nikosszzz** [comment]
I have fixed this in the handler for commands to load on Windows for me:

```
import { readdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath, pathToFileURL } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export async function importCommands(client) {
  const commandFiles = readdirSync(join(__dirname, "..", "commands")).filter((file) => file.endsWith(".js"));

  for (const file of commandFiles) {
    const command = await import(join(pathToFileURL(__dirname).href, "..", "commands", `${file}`));
    client.commands.set(command.default.name, command.default);
  }
}
```

**Comment by eritislami** [comment]
I believe this should be fixed in the typescript version which is coming soon

https://github.com/eritislami/evobot/tree/refactor/typescript
