### ISSUE TITLE
Bug: queueing age restricted videos make bot crash

### ISSUE THREAD

**Issue by PandaIN95** [eritislami/evobot#1147]
**How To Reproduce**
1. play any normal song than add any age restricted song into the queue
2. then skip the current playing song bot will crash 
 
**Environment (add if possible)**
* Node.js version: 16.15.0 

**Additional information & screenshots**
[crash](https://imgur.com/aG5MQzO)

**Comment by eritislami** [comment]
I believe this should be fixed in the typescript version which is coming soon

https://github.com/eritislami/evobot/tree/refactor/typescript
