### ISSUE TITLE
Lyrics command doesn't work error below

### ISSUE THREAD

**Issue by NickaDev** [eritislami/evobot#115]
`(node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
at module.exports (/home/container/node_modules/unidecode/unidecode.js:20:14)
at main (/home/container/node_modules/lyrics-finder/src/index.js:38:10)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.execute (/home/container/commands/lyrics.js:15:10)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by eritislami** [comment]
Thanks, try again with a8f4c134b6788e62fc625a75bec2a1fe01bc8bfe i didn't bother to test this case since i thought the package would handle the error appropriately but i was wrong

**Comment by NickaDev** [comment]
it tries to display it in html code.
Lyrics
<span dir="ltr">Nights, flying down the 10, nearly 2 AM
Happiness begins
Days lifted in a haze, we weren't just a phase
We weren't just pretend (just pretend)

I remember low lows and high highs
We threw our hands up, palms out to the skies

It was fun when we were young and now we're older
Those days when we were broke in California
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster
It was fun when we were young and now we're older
Those days that are the worst, they seem to glow now
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster with you

Woo ooh ooh, woo ooh
Woo ooh ooh (oh, oh)
But I'd come back and ride that roller coaster

Faith led me to the clouds, reaching for the ground
His life was upside down
Now everything has changed, we found better days
But I still hear the sound

I remember low lows and high highs
We threw our hands up, palms out to the skies

It was fun when we were young and now we're older
Those days when we were broke in California
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster
It was fun when we were young and now we're older (oh)
Those days that are the worst, they seem to glow now (yeah)
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster with you

Woo ooh ooh (yeah, with you)
Woo ooh (with you, with you)
Woo ooh ooh (oh, oh)
But I'd go back and ride that roller coaster

It was fun when we were young and now we're older
Those days that are the worst, they seem to glow now
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster

Nights, flying down the 10, nearly 2 AM
Happiness begins</span>

**Comment by NickaDev** [comment]
Lyrics
<span dir="ltr" >Nights, flying down the 10, nearly 2 AM
Happiness begins
Days lifted in a haze, we weren't just a phase
We weren't just pretend (just pretend)

I remember low lows and high highs
We threw our hands up, palms out to the skies

It was fun when we were young and now we're older
Those days when we were broke in California
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster
It was fun when we were young and now we're older
Those days that are the worst, they seem to glow now
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster with you

Woo ooh ooh, woo ooh
Woo ooh ooh (oh, oh)
But I'd come back and ride that roller coaster

Faith led me to the clouds, reaching for the ground
His life was upside down
Now everything has changed, we found better days
But I still hear the sound

I remember low lows and high highs
We threw our hands up, palms out to the skies

It was fun when we were young and now we're older
Those days when we were broke in California
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster
It was fun when we were young and now we're older (oh)
Those days that are the worst, they seem to glow now (yeah)
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster with you

Woo ooh ooh (yeah, with you)
Woo ooh (with you, with you)
Woo ooh ooh (oh, oh)
But I'd go back and ride that roller coaster

It was fun when we were young and now we're older
Those days that are the worst, they seem to glow now
We were up-and-down and barely made it over
But I'd go back and ride that roller coaster

Nights, flying down the 10, nearly 2 AM
Happiness begins</ span>

**Comment by alias-rahil** [comment]
The error was in the package. It is fixed now in this [commit](https://github.com/alias-rahil/lyrics-finder/commit/0ddf4bd90b70bebb8d746df36ae50174dc84b132).

**Comment by alias-rahil** [comment]
The error was in the package. It is now resolved.

1. Now the package won't throw any errors, instead will return an empty string.
2. The span html tag is now removed from the text.

**Comment by eritislami** [comment]
@alias-rahil Thank you, i appreciate the collaboration
