### ISSUE TITLE
Music Management

### ISSUE THREAD

**Issue by asupreme1337** [eritislami/evobot#1150]
**Is your feature request related to a problem? Please describe.**
The proposal is related to the fact that the bot, when playing music, reacts to reactions only to the user who started this music, or to individual users (moderators /administrators) to stop the music due to violation of any rules.

**Describe the solution you'd like**
I would like the bot to react only to the initiator of the music stream. Because one person can turn on the music, and the other indulges and switches the volume or something else. This causes discomfort to users.

**Comment by eritislami** [comment]
Hey thanks for the suggestion, I also believe it's worth having a DJ role or something similar to that concept and I hope to add it in the future, in the mean time if you wish to experiment with it yourself, I can show you a pretty easy way to have exclusive control of the bot with some exceptions regarding the reactions,

This is the line before every command execution, here you could add a simple check to stop the bot from executing commands from other users

https://github.com/eritislami/evobot/blob/a1055363c971852da199ad28b5cafdb197fd7320/utils/messageCreate.js#L48

```js
if (message.member.user.id !== "266241948824764416") return;
```

Replace the number with your own user id, and to do that:

> Go to User Settings > Advanced > enable Developer Mode.
Next, simply right-click your profile picture and select ‘Copy ID’ to copy your User ID.

**Comment by eritislami** [comment]
> Wow, that's cool. But will the initiator of the music be able to control the reactions when using this code? After all, if another user tells the bot to play music, then he probably won't be able to control it...

This would only allow the owner, what you propose is a new feature that would be nice to have but yes
