### ISSUE TITLE
Bug: Stopping music with ⏹️ make the bot not load any other music

### ISSUE THREAD

**Issue by TheFury4** [eritislami/evobot#1153]
If you stop the music using the emoji :stop_button: the bot interrupt the music and wont load any other music in queue
Node JS version: 16.15.0
https://prnt.sc/RQl-jAIqAf0H

**Comment by nhanledev** [comment]
Event <prefix>stop command made the bot stop responding

**Comment by WongJH** [comment]
You May Try
replace the code

queue.loop = false;
queue.songs = [];
queue.player.stop();
queue.connection.destroy();

At commands/stop.js line 13 to line 16 with

queue.songs.shift();
queue.songs = [1];
queue.player.stop(); 

This method worked out for me with node v17.7.2

**Comment by eritislami** [comment]
I believe this should be fixed in the typescript version which is coming soon

https://github.com/eritislami/evobot/tree/refactor/typescript

**Comment by eritislami** [comment]
#1167
