### ISSUE TITLE
Bug: eror youtube dl no update

### ISSUE THREAD

**Issue by pengengantibaju** [eritislami/evobot#1157]
when i play a song and stop cant play again and show this 
![image](https://user-images.githubusercontent.com/92777707/168111607-eb406401-e8e6-45c8-9100-3cd15752c60a.png)

**Comment by SugarD-x** [comment]
https://www.npmjs.com/package/ytdl-core#Update-Checks

That error is related to ytdl-core, which is a dependency of evobot. It looks like your system is blocking the bot from connecting to the ytdl-core repo to check for updates.
