### ISSUE TITLE
Bug: Can't install new packages.

### ISSUE THREAD

**Issue by adityavandari** [eritislami/evobot#1158]
wanted to install "express" plugin but cant

**Comment by adityavandari** [comment]
want to add this line of code in index.js


const express = require('express')
const app = express();
const port = 3000


app.get('/', (req, res) => res.send('Yo boi!!'))


app.listen(port, () =>
console.log(`Your app is listening a http://localhost:${port}`)

**Comment by adityavandari** [comment]
want to add this line of code in index.js

const express = require('express')
const app = express();
const port = 3000

app.get('/', (req, res) => res.send('UPandRunnin!!'))

app.listen(port, () =>
console.log(Your app is listening a http://localhost:${port})

**Comment by eritislami** [comment]
1. Do not use issues for programming support
2. This project uses ESM
3. Google
