### ISSUE TITLE
Bug: Music Wont play after stopped

### ISSUE THREAD

**Issue by WongJH** [eritislami/evobot#1159]
**Describe the bug**
Music added after stop and bot will leave VC instantly and no "❌ Music queue ended." displayed. Songs after current song will be added into queue and was unable to play. Commands wont work due to the bot already left the VC

You May Try
1.  replace the code 

    queue.loop = false;
    queue.songs = [];
    queue.player.stop();
    queue.connection.destroy();

At commands/stop.js line 13 to line 16 with

    queue.loop = false;
    queue.songs.shift();
    queue.songs = [1];
    queue.player.stop(); 

 
After replacing the code it should  work fine and  display "❌ Music queue ended." and leave the VC after stay time

**Environment (add if possible)**
* Node.js version: 17.7.2

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
[commands.stop.txt](https://github.com/eritislami/evobot/files/8713985/commands.stop.txt)

**Comment by eritislami** [comment]
#1167
