### ISSUE TITLE
Bug: ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by FForion** [eritislami/evobot#1169]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: v18

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Try the typescript branch for now, should work, and check the readme on that branch for instructions
