### ISSUE TITLE
Bug: Does not act on messages in the new Voice text channels

### ISSUE THREAD

**Issue by tyzbit** [eritislami/evobot#1170]
**Describe the bug**
The bot does not act on messages in the new voice text channels.

**How To Reproduce**
1. Send a command in a voice text channel.
2. Observe the bot does not respond.
 
**Expected behavior**
The bot responds to commands in voice text channels.

**Environment (add if possible)**
* Node.js version: `eritislami/evobot:1.2.2` Docker image

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by wolf-yuan-6115** [comment]
This is Discord.js relative bug, we can't slove this.

**Comment by tyzbit** [comment]
This is supported in `v14-dev` of discord.js https://github.com/discordjs/discord.js/issues/7998

**Comment by suneettipirneni** [comment]
This is now released in version 13.8.0

**Comment by tyzbit** [comment]
This is still not resolved. All that's needed is to bump discord.js to at least 13.8.0.

**Comment by tyzbit** [comment]
This is not resolved. I just checked version `2.0.0` and it appears it was built with `13.8.0`: https://github.com/eritislami/evobot/blob/9ae5898c2a906011a4062ae944ea169ee0bc7689/package-lock.json#L1527
