### ISSUE TITLE
Bug: When the bot is playing a song, it stops randomly

### ISSUE THREAD

**Issue by KimPig** [eritislami/evobot#1176]
**Describe the bug**
A description of what the bug is.

When the bot is playing a song, it stops randomly and quits the vioce channel.
After that, it can be loaded before I reboot the bot

**How To Reproduce**

Actually I don't know under what conditions this bug occurs, but it's pretty common.
It happens about once in 8 times.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by renanluiz** [comment]
Same here

**Comment by eritislami** [comment]
Can't help debug this by just saying it's "random", you could help by getting the error from terminal, watching your ram usage, etc...

**Comment by mozzi-berilinky** [comment]
Where are you hosting the bot? If the bot is being hosted on heroku or replit, the bot may reboot unexpectedly.

**Comment by DivaySaini** [comment]
same, there is no kind of error in the log. hosting on a private linux server.

**Comment by stephensilber** [comment]
Also running into the same issue. Running the bot inside of a docker container on a small digital ocean droplet. Used to work without this issue before the typescript upgrade so if it's a memory issue I think it's a newly introduced one. If someone points me to which logs would be useful I'd be happy to post them here once it happens again. For us it happens every single time a long mix is playing (> 1 hour) and usually at around the same time.

**Comment by Sharrnah** [comment]
Having the same issue:

This is what appeared in the terminal log:
```
> evobot@2.0.0 start
> ts-node index.ts

*** Bot ready!
AudioPlayerError: aborted
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketCloseListener (node:_http_client:402:19)
    at TLSSocket.emit (node:events:538:35)
    at TLSSocket.emit (node:domain:475:12)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7) {
  resource: AudioResource {
    playStream: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      encoder: null,
      _options: [Object],
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    edges: [ [Object], [Object], [Object] ],
    metadata: Song {
      url: 'https://www.youtube.com/watch?v=lovYZqGVPBQ',
      title: '6 Hours of The Best Epic Inspirational Music for Studying and Working',
      duration: 21614
    },
    volume: VolumeTransformer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _readInt: [Function (anonymous)],
      _writeInt: [Function (anonymous)],
      _bits: 16,
      _bytes: 2,
      _extremum: 32768,
      volume: 1,
      _chunk: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    encoder: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      encoder: null,
      _options: [Object],
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [Array],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    playbackDuration: 2034420,
    started: true,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
```

Running the Docker Container in Kubernetes.

**Comment by zPanic** [comment]
Not stale, having the same issue as @Sharrnah.

**Comment by frenchtoasters** [comment]
Not stale, having the same issue as @Sharrnah

**Comment by eritislami** [comment]
I've put the progress label so stale bot won't touch this issue anymore, the thing is that I have played 1-2 hour videos with my bot and haven't had an issue, this is quite difficult to debug and determine why it's happening

**Comment by frenchtoasters** [comment]
> I've put the progress label so stale bot won't touch this issue anymore, the thing is that I have played 1-2 hour videos with my bot and haven't had an issue, this is quite difficult to debug and determine why it's happening

I do know that I would hit the issue when running this in a container, for me its in a kubernetes cluster. The behavior that I have seen is that it will play for 1-2 hours a video. Then after that video has run it will start to fail on the next few videos. I can try and get some kubernetes logs from my setup if you think that would help.

 TBH I forked and moved to `play-dl` instead and have not run into this issue any more, not sure if that is an option for this project though https://github.com/frenchtoasters/evobot/commit/63666ba84c542908645aa8f195b4fc37d8dcee6d

**Comment by diespinozah** [comment]
> > I've put the progress label so stale bot won't touch this issue anymore, the thing is that I have played 1-2 hour videos with my bot and haven't had an issue, this is quite difficult to debug and determine why it's happening
> 
> I do know that I would hit the issue when running this in a container, for me its in a kubernetes cluster. The behavior that I have seen is that it will play for 1-2 hours a video. Then after that video has run it will start to fail on the next few videos. I can try and get some kubernetes logs from my setup if you think that would help.
> 
> TBH I forked and moved to `play-dl` instead and have not run into this issue any more, not sure if that is an option for this project though [frenchtoasters@63666ba](https://github.com/frenchtoasters/evobot/commit/63666ba84c542908645aa8f195b4fc37d8dcee6d)

The problem is not random, it happens with some videos about more than 1h duration, we just don't know what's the common thing about those videos. this is an example -> https://www.youtube.com/watch?v=c4LqKf9dxPY

The fix might be as @frenchtoasters says to moved to play-dl instead ytdl-core. I have read about other similar issues and the problem is ytdl-core. This is one of the repositories with similar isssues -> https://github.com/Androz2091/discord-player/issues/892

**Comment by nanoeray** [comment]
No its not just doing this or 1h duration videos. I have opened this https://www.youtube.com/watch?v=YdW6n8Leznc and still same error. bot stops before the duration ends. every time the stop point changing randonly and no terminal error. Just bot says Music ended.

**Comment by eritislami** [comment]
We have now moved to play-dl with the help of @diespinozah I will let this issue stay open for a bit longer to see if anyone has feedback about it.

**Comment by ChristianVaughn** [comment]
I see this issue has suposedly been fixed, but I just had the issue pop up with the error
```
AudioPlayerError: aborted
    at connResetException (node:internal/errors:720:14)
    at TLSSocket.socketCloseListener (node:_http_client:461:19)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:614:7) {
  resource: AudioResource {
    playStream: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      encoder: null,
      _options: [Object],
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    edges: [ [Object], [Object], [Object] ],
    metadata: Song {
      url: 'https://www.youtube.com/watch?v=4hBhArKJ43U',
      title: 'cozy autumn nintendo mix 🍁 (part 2)',
      duration: 4092
    },
    volume: VolumeTransformer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _readInt: [Function (anonymous)],
      _writeInt: [Function (anonymous)],
      _bits: 16,
      _bytes: 2,
      _extremum: 32768,
      volume: 1,
      _chunk: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    encoder: Encoder {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      encoder: null,
      _options: [Object],
      _required: 3840,
      _buffer: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: [Function: bound onwrite]
    },
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [Array],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    playbackDuration: 1244180,
    started: true,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}
```
