### ISSUE TITLE
Bug: Once stopped, the bot does not play music again.

### ISSUE THREAD

**Issue by ghost** [eritislami/evobot#1178]
**Describe the bug**
I am using the TypeScript branch. This is the same issue as recent ones (#1176, #1174)
I did see one error: 
Error: Cannot destroy VoiceConnection - it has already been destroyed 
But am unable to get the rest of it from the log. 

**How To Reproduce**
1. Play music
2. Stop the bot 
3. Try playing music again.
 
**Environment (add if possible)**
node: v16.15.0 
npm: 8.5.5

**Comment by modee0011** [comment]
change

    queue.loop = false;
    queue.songs = [];
    queue.player.stop();
    queue.connection.destroy();
    
    To:

   queue.loop = false;
    queue.songs.shift();
    queue.songs = [1];
    queue.player.stop();

**Comment by lif3oftheparty** [comment]
You should really read the issue before pasting code. I am using the refactor/typescript branch, not master.

**Comment by eritislami** [comment]
So I believe the issue is caused by the "Stay time" feature, the real issue is that when you stop a song, play a new song, in the timeout it reports the state as "Idle" and this would usually prevent the bot from disconnecting or destroying the connection, for now I have disabled it and it should be ok

**Comment by Senjar** [comment]
```
public stop() {
    this.queueLock = true;
    this.loop = false;
    this.songs = [];
    this.player.stop();
    bot.queues.delete(this.message.guild!.id);

    !config.PRUNING && this.textChannel.send(i18n.__("play.queueEnded")).catch(console.error);

    setTimeout(() => {
      if (
        this.player.state.status !== AudioPlayerStatus.Idle ||
        this.connection.state.status === VoiceConnectionStatus.Destroyed
      )
        return;

      this.connection.destroy();

      !config.PRUNING && this.textChannel.send(i18n.__("play.leaveChannel"));
    }, 100);
  }
```

I think this is because at "this.player.state.status !== AudioPlayerStatus.Idle" you are referencing a dead queue that is always idle since the play command creates new queues.

`bot.queues.get(this.message.guild!.id)?.player.state.status`
instead of
`this.player.state.status `
should fix it
And I believe the wait time was in place of the number 100 so finally it should look like this if stay time is in seconds:
```
public stop() {
    this.queueLock = true;
    this.loop = false;
    this.songs = [];
    this.player.stop();
    bot.queues.delete(this.message.guild!.id);

    !config.PRUNING && this.textChannel.send(i18n.__("play.queueEnded")).catch(console.error);

    setTimeout(() => {
      if (
        bot.queues.get(this.message.guild!.id)?.player.state.status !== AudioPlayerStatus.Idle ||
        this.connection.state.status === VoiceConnectionStatus.Destroyed
      )
        return;

      this.connection.destroy();

      !config.PRUNING && this.textChannel.send(i18n.__("play.leaveChannel"));
    }, config.STAY_TIME*1000);
  }
```

**Comment by Senjar** [comment]
Tested and fixed the code

```
  public stop() {
    this.queueLock = true;
    this.loop = false;
    this.songs = [];
    this.player.stop();
    bot.queues.delete(this.message.guild!.id);

    !config.PRUNING && this.textChannel.send(i18n.__("play.queueEnded")).catch(console.error);

    setTimeout(() => {
      const playerStatus = bot.queues.get(this.message.guild!.id)?.player.state.status
      if (playerStatus !== undefined &&
        (playerStatus !== AudioPlayerStatus.Idle ||
        this.connection.state.status === VoiceConnectionStatus.Destroyed)
      )
        return;

      this.connection.destroy();

      !config.PRUNING && this.textChannel.send(i18n.__("play.leaveChannel"));
    }, config.STAY_TIME*1000);
  }

```
Tested the following scenarios:
When the timeout hits 0 and:
- Nothing is playing -> Bot Disconnect
- Song is playing -> Nothing
- Song is paused -> Nothing
Haven't tested when it's buffering but since the code says anything but idle is ok it should work

**Comment by eritislami** [comment]
Thanks @Senjar
