### ISSUE TITLE
Bug: Volume issue

### ISSUE THREAD

**Issue by MrRob1** [eritislami/evobot#118]
**Describe the bug**
If you play a song and change the volume it will change if the song ends and you add another song. It will go back to max.

**How To Reproduce**
1. Play a song, 
2. Change Volume
3. Wait for song to end
4. Add new song

 
**Expected behavior**
After a song ends, add a new song to replicate

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
This is intended, the volume is tied to the queue, for now if you want a more permanent change you have to change the volume of the bot user in discord with right click, there is a discussion about permanent volume settings in #95
