### ISSUE TITLE
Bug: Disconnecting a bot through Discord's menu bugs out the music

### ISSUE THREAD

**Issue by nikosszzz** [eritislami/evobot#1180]
**Describe the bug**
If you go to your bot that is playing music, and disconnect it using the discord method and then try to play Music again, the queue becomes bugged.

**How To Reproduce**
1. Play something in the bot.
2. Disconnect it by right-clicking on the bot in the voice channel.
3. Try to play another video/song.
4. Bot adds song/video to queue, but does not rejoin voice channel.
 
**Expected behavior**
On disconnect it should destroy the connection and/or queue.

**Environment (add if possible)**
* Node.js version: 16.14.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by xainsworth** [comment]
Same, and solution works like a charm.

**Comment by wgetgoose** [comment]
Same issue. Adding a feature like !join or !disconnect might be cool for the future too.

**Comment by wgetgoose** [comment]
Not sure how stale this issue is when the issue still persists.

**Comment by nikosszzz** [comment]
> Not sure how stale this issue is when the issue still persists. 

I’m pretty sure the fix for it is already merged or, if not you can try the fix i posted above.

**Comment by nikosszzz** [comment]
Closing this since it has been fixed.

**Comment by Agentsarkar** [comment]
> 

in which file did u do it ?

**Comment by abarichello** [comment]
This issue still persists, can you please reopen?

**Comment by abarichello** [comment]
FYI I was able to fix this issue by removing this line: https://github.com/eritislami/evobot/blob/22d353fe497b366134344e00fd58a80b6d31220c/structs/MusicQueue.ts#L58
