### ISSUE TITLE
Bug: cmd crashes

### ISSUE THREAD

**Issue by Hiura-Souji** [eritislami/evobot#1182]
**Describe the bug**
When I stop the music, the bot won't leave the channel after 30 seconds
When I disconnect the bot from the channel, the cmd crashes directly.
PS.I am using the latest EVO version.

**How To Reproduce**
1.stop the music
2.wait 30 sec.
3.disconnect the bot
4.play music agian
5.show  loading and cmd crashes. Or it add music to list, but bot not work (Bot join the channel and then leave).

 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: v17.7.2

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
#1180 Will be handled here
