### ISSUE TITLE
Bug: Queueing a playlist result in only 1 song played

### ISSUE THREAD

**Issue by Velosofy** [eritislami/evobot#1183]
**Describe the bug**
The bot failed to retrieve playlist songs, it only queue 1 song

**How To Reproduce**
1. Run the bot as usual
2. Try to queue a playlist
3. Check the queue list with !queue
 
**Expected behavior**
The bot should queue every songs there are in the playlist

**Environment (add if possible)**
* Node.js version: v16.11.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://user-images.githubusercontent.com/61261357/173839164-7b6a9218-a7c0-42d2-9c86-8a7714e036cc.png)

**Comment by nikosszzz** [comment]
![image](https://user-images.githubusercontent.com/53112175/173885900-2fc532fb-0c49-4adb-b364-e2466c3923b1.png)
Can confirm this happens aswell to me.

**Comment by Sputnik1973** [comment]
This issue is happening to me aswell
![Screenshot_20220615-203652](https://user-images.githubusercontent.com/40334223/173900720-63730183-2183-453c-ba09-5ec1dc3fe7f9.png)

**Comment by DivaySaini** [comment]
you have to use the command "playlist" to add the playlist in the queue, however only 10 songs are added even if in the config.json the max playlist is increased. it's a glitch or a mistake.

**Comment by nikosszzz** [comment]
> you have to use the command "playlist" to add the playlist in the queue, however only 10 songs are added if the config.json is not edited. you have to increase the "max playlist".
> 
> you probably should edit the title to solved or something (and it's not a bug so please consider removing it from the title)

Still does not work for me. 

Playlist or the play command still gives me only up to ONE song.

**Comment by nikosszzz** [comment]
Though, playing around with the Playlist code struct has given me some information:

All titles seem to be parsed from the playlist, but only the FIRST title & song get always only queued for some reason.

**Comment by Velosofy** [comment]
> you have to use the command "playlist" to add the playlist in the queue, however only 10 songs are added if the config.json is not edited. you have to increase the "max playlist".
> 
> you probably should edit the title to solved or something (and it's not a bug so please consider removing it from the title)

Please try to understand the issue before commenting, the bot is smart enough to use `playlist` command if we put playlist link with `play`.

**Comment by DivaySaini** [comment]
@nikosszzz the bot is working very fine for me without any changes in the code, you should try updating the bot or something. @Velosofy  this is an issue but the songs in the playlist are being queued with "playlist" only, "play" command just queues the first song in the playlist. the bot have some glitch that it is not using playlist command when using the play command while using a playlist link, while it shows all the songs of the playlist but not plays all the songs. this maybe done intentionally because you can see many playlists created by big creators on youtube music containing only one song, or i'm wrong and it is just a glitch. it is working for now tho.

**Comment by nikosszzz** [comment]
> @nikosszzz the bot is working very fine for me without any changes in the code, you should try updating the bot or something. @Velosofy this is an issue but the songs in the playlist are being queued with "playlist" only, "play" command just queues the first song in the playlist. the bot have some glitch that it is not using playlist command when using the play command while using a playlist link, while it shows all the songs of the playlist but not plays all the songs. this maybe done intentionally because you can see many playlists created by big creators on youtube music containing only one song, or i'm wrong and it is just a glitch. it is working for now tho.

My bot is entirely updated fully to the new TypeScript codebase with nothing touched. 

And @Velosofy's claim is right. Play command automatically goes to the `playlist` command as you can read in the code. There is no bug there and I've tested it extensively. Somewhere in the Song/Playlist structs is the problem which has not been identified, but thats my personal opinion over the problem.

**Comment by nikosszzz** [comment]
Have noticed the following: running the play command or the playlist command with the given playlist while the bot has music playing, does fetch the amount of songs from `MAX_PLAYLIST_SIZE` in that playlist. 

Perhaps, something entirely wrong with the MusicQueue starting too early the queue so it misses it all?

**Comment by DivaySaini** [comment]
that can't be an issue @nikosszzz . when the first song is already playing and you do the same command again, the whole playlist is added in the queue, (sorry i did the same thing last time and got it right so commented too early to check, again sorry about that).

**Comment by nikosszzz** [comment]
> that can't be an issue @nikosszzz . when the first song is already playing and you do the same command again, the whole playlist is added in the queue, (sorry i did the same thing last time and got it right so commented too early to check, again sorry about that).

when you first run it without ANYTHING playing in the queue, only the first song gets added. The rest can be added if you re-run the same command while its playing, but thats not a fix nor a workaround. 

Therefore, this is not intended behavior and it's a bug/issue.

**Comment by DivaySaini** [comment]
> 

yes, i do agree this is a bug.

**Comment by nikosszzz** [comment]
I have finally found a fix!

![image](https://user-images.githubusercontent.com/53112175/180021515-d3eb8aec-9719-43f3-9898-5217f284e6c4.png)
Add the selected line into that part of the code and try running the command. Should work as expected!

**Comment by DenisCepaka** [comment]
> I have finally found a fix!
> 
> ![image](https://user-images.githubusercontent.com/53112175/180021515-d3eb8aec-9719-43f3-9898-5217f284e6c4.png) Add the selected line into that part of the code and try running the command. Should work as expected!

Thanks
