### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by medo102** [eritislami/evobot#1186]
**Describe the bug**
A description of what the bug is.
@Onil, The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
**How To Reproduce**
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Not a bug, and you are using an old version
