### ISSUE TITLE
playing soundcloud url throws an exception using the docker image

### ISSUE THREAD

**Issue by monsieurlasogette** [eritislami/evobot#1196]
![584D4A0C-F031-43FF-B1E5-9E6A8564B6F3](https://user-images.githubusercontent.com/94866988/177321735-db55a0a3-6758-4aad-9b99-d96d1ab22420.jpeg)

**Comment by NicWebster96** [comment]
@monsieurlasogette Can you post the URL you are trying to play?

**Comment by eritislami** [comment]
Soundcloud is disabled currently, will see if I can re-implement
