### ISSUE TITLE
 Disconnect Before Music Ends

### ISSUE THREAD

**Issue by MrPerfectShot** [eritislami/evobot#12]
When I Play Music Bot  Disconnect Before Music Ends Saying Music queue ended but Music Dont End And Dont Show Errors.
Im Only Change Config.js To Test Bot.

If You Need My Discord: MrPerfectShot#2252

**Comment by eritislami** [comment]
Hello, i made some changes today to implement the changes that were made in discord.js v12 which might fix your issue. Please try a fresh clone of the bot in a new directory, make sure to be running node v12.0.0 or later and if you are still encountering issues make sure to reply with any console errors you receive

**Comment by MrPerfectShot** [comment]
Hello I Test Again And Problem Solved Thanks Very Much And Good Work
