### ISSUE TITLE
Bug: Missing Features that are mentioned in the README.md (!clip + STAY_TIME)

### ISSUE THREAD

**Issue by Sharrnah** [eritislami/evobot#1220]
**Describe the bug**
Trying out the bot for the first time, it works nicely.
Except 2 things that are mentioned in the README.md but don't work and i can't even find any functionality in the code for it.
So it was either never implemented -> Should not be mentioned in the README.md
Or it was implemented and got removed by accident (maybe together with the Refactor?)

**How To Reproduce**
1. Use `!clips` command. it lists the clips from the folder (but without file extension)
2. Use `!clip putmusichere.mp3` like mentioned in the README.md. (also tried it with `!play` but that just plays some random Youtube video)
3. Set `STAY_TIME` to 30 (as much as i found in the code, its supposed to be seconds. Could help to mention that as well in the README.md)
4. Let the Bot play something, but stop by pressing the reaction or use `!stop` and not letting it finish playing.
 
**Expected behavior**
Steps 1-2: It should start playing the MP3 file. but does nothing.
Steps 3-4: Bot should leave the Voice Channel after 30 seconds. But never leaves.

**Environment (add if possible)**
* Node.js version: Using latest Docker image from Docker-Hub

**Additional information & screenshots**
* I have seen https://github.com/eritislami/evobot/issues/936
  If that is really the opinion, it should be removed from the README.md and the `!clips` command with it, since it is useless.
* Same with `STAY_TIME`. even though i think this is something that should work (again?)

**Comment by eritislami** [comment]
It was temporarily disabled to accommodate a bug fix, I am aware and looking into it

**Comment by eritislami** [comment]
The latest release has fixed stay time feature, the clips will have to wait for now

**Comment by Rayrsn** [comment]
any update on the clip command?
