### ISSUE TITLE
Bug: There was an error executing that command.

### ISSUE THREAD

**Issue by SmaDababaXor** [eritislami/evobot#1235]
**Describe the bug**
A description of what the bug is. when ever i use prefix play is says There was an error executing that command.

**How To Reproduce**
1. !play https://youtu.be/S2ujotDMluo
2.There was an error executing that command.
 
**Expected behavior**
plays the song 

**Environment (add if possible)**
* Node.js version: Welcome to Node.js v16.15.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by ChineseUncleTom** [comment]
Same issue here

**Comment by nhanledev** [comment]
Same issue with any song and search feature

**Comment by slunkius** [comment]
To me it says:
Invalid regular expression: missing /

**Comment by ceselder** [comment]
same issue

**Comment by ceselder** [comment]
`SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (/root/evobot/node_modules/ytdl-core/lib/sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/root/evobot/node_modules/ytdl-core/lib/info.js:401:17)
`

**Comment by ceselder** [comment]
its a bug in node-ytdl-core

https://github.com/fent/node-ytdl-core/issues/1110

**Comment by ceselder** [comment]
https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413

temp fix

**Comment by razeNFR** [comment]
Thank for the fix, it worked for me :)

**Comment by legouju** [comment]
> [fent/node-ytdl-core#1108 (comment)](https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413)
> 
> temp fix

yep can vouch, changing this fixed, now need to see if I can get the docker container to use the latest node-ytdl-core as I belive it has been fixed now.

**Comment by Cptnmo109** [comment]
Just change the ytdl version to 4.10.0
Delete the package-lock.json
And start the bot

**Comment by dracorlll** [comment]
same here

**Comment by lucid-OmO** [comment]
> > > [fent/node-ytdl-core#1108 (comment)](https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413)
> > > temp fix
> > 
> > 
> > yep can vouch, changing this fixed, now need to see if I can get the docker container to use the latest node-ytdl-core as I belive it has been fixed now.
> 
> where do i put this in replt.it?

you can fix it by changing the youtube-dl version to 4.10.0 inside the package.json and delete the package-lock.json and just restart the bot

**Comment by eritislami** [comment]
36ef0c282b6557f338843f3c79ee9e6a90205f3a

Reinstall your npm packages to get the fix
