### ISSUE TITLE
Bug: Invalid Token code

### ISSUE THREAD

**Issue by lk1421** [eritislami/evobot#1256]
I put in my bot token from discord dev portal but it keep saying invalid token. Can someone help me out to fix the error?

![image](https://user-images.githubusercontent.com/79070023/187008102-06130e2e-bdeb-4434-8994-e3bd754d3c19.png)
![image](https://user-images.githubusercontent.com/79070023/187008119-14d7d43b-95bd-4426-aa05-dd504571023a.png)
![image](https://user-images.githubusercontent.com/79070023/187008053-35fc411a-6081-4228-aaea-a8a03186b2a2.png)

**Comment by filip2cz** [comment]
I have same error, how did you resolve it?
