### ISSUE TITLE
🚀 Search accept multiple songs

### ISSUE THREAD

**Issue by ABotDev** [eritislami/evobot#126]
When you use the search command you can only pick one song, it will be cool if you can update it so you can pick multiple songs.

Sorry for my bad english.

**Comment by eritislami** [comment]
Added in [EvoBot 0.9.0](https://github.com/eritislami/evobot/releases/tag/0.9.0)

Search command now also accepts comma seperated list of songs, example: `1, 2, 4, 6`
Will keep this open for a bit in case there is feedback.

**Comment by wolf-yuan-6115** [comment]
Wow!!!
Good suggest!!!
