### ISSUE TITLE
Bug: Prefix doesn't work?

### ISSUE THREAD

**Issue by 9ofe** [eritislami/evobot#1267]
Everything in the bot works fine. But commands with the prefix doesn't work at all.
I can only use the bot by mentioning the bot like "@bot help" etc..
I did the default install. I also tried with docker but the same problem.

**Comment by eritislami** [comment]
Recent change by Discord, you have to enable message content in Discord Developer Portal

![image](https://user-images.githubusercontent.com/22680785/188308004-d0e31e0f-3f46-47b1-8d67-e3144764a6a9.png)
