### ISSUE TITLE
🐛 Evobot 2.3.1 stops music queue twice and the object destroys itself

### ISSUE THREAD

**Issue by diespinozah** [eritislami/evobot#1279]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. play a song
2. stop the song with the emoji (stop button reaction) 
3. bot ended the queue twice
 
**Expected behavior**
A description of what you expected to happen.
bot end the queue once. When it ends the queue twice should destroy 2 objects and the bot crash
**Environment (add if possible)**
* Node.js version: 18.9.0

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/49412551/190881859-88aa05f0-ffcb-40e5-ae58-1c02dd1bffe7.png)
![image](https://user-images.githubusercontent.com/49412551/190881870-b8e41755-44da-477b-b442-a0a8a5008308.png)

Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Thanks will look into it

**Comment by Quack6666** [comment]
I'm not too familiar with Node so it might not be the best way, but I managed to fix it by editing the file `structs/MusicQueue.ts` and replacing the line 121:
```
this.connection.destroy();
```
with the following:
```
if (this.connection.state.status !== VoiceConnectionStatus.Destroyed) {
  try {
     this.connection.destroy();
  } catch {}
}
```

**Comment by diespinozah** [comment]
> I'm not too familiar with Node so it might not be the best way, but I managed to fix it by editing the file `structs/MusicQueue.ts` and replacing the line 121:
> 
> ```
> this.connection.destroy();
> ```
> 
> with the following:
> 
> ```
> if (this.connection.state.status !== VoiceConnectionStatus.Destroyed) {
>   try {
>      this.connection.destroy();
>   } catch {}
> }
> ```

your solution fix the object destroying itself twice and kill the process. But it's still destroying the object and leaving the channel when you queue more songs after a "stop" command

**Comment by eritislami** [comment]
Should be handled by #1318

**Comment by diespinozah** [comment]
> Should be handled by #1318

When @Quack6666 posted the solution (same as the commit) I've been testing and it fixes partially the solution as I mentioned here 

> > I'm not too familiar with Node so it might not be the best way, but I managed to fix it by editing the file `structs/MusicQueue.ts` and replacing the line 121:
> > ```
> > this.connection.destroy();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with the following:
> > ```
> > if (this.connection.state.status !== VoiceConnectionStatus.Destroyed) {
> >   try {
> >      this.connection.destroy();
> >   } catch {}
> > }
> > ```
> 
> Thanks for the solution.
> 
> It fix the object destroying itself twice and killing the process. But it's still destroying the object and leaving the channel when you add more songs to the queue after a "stop" command.

**Comment by diespinozah** [comment]
> 

everytime I use Stop command (my "STAY_TIME" is 30 seconds) if I play another song before that, the bot will play the song but It will leave the channel anyways after that 30s. That happens to me.

**Comment by diespinozah** [comment]
> > > Should be handled by #1318
> > 
> > 
> > When @Quack6666 posted the solution (same as the commit) I've been testing and it fixes partially the solution as I mentioned here
> > > > I'm not too familiar with Node so it might not be the best way, but I managed to fix it by editing the file `structs/MusicQueue.ts` and replacing the line 121:
> > > > ```
> > > > this.connection.destroy();
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > with the following:
> > > > ```
> > > > if (this.connection.state.status !== VoiceConnectionStatus.Destroyed) {
> > > >   try {
> > > >      this.connection.destroy();
> > > >   } catch {}
> > > > }
> > > > ```
> > > 
> > > 
> > > Thanks for the solution.
> > > It fix the object destroying itself twice and killing the process. But it's still destroying the object and leaving the channel when you add more songs to the queue after a "stop" command.
> 
> Same thing here, sometimes it doesn't do it but sometimes it does still.

Everytime I use Stop command (my "STAY_TIME" is 30 seconds) if I play another song before that, the bot will play the song but It will leave the channel anyways after that 30s. That happens to me.

**Comment by eritislami** [comment]
@diespinozah Should be fixed now
