### ISSUE TITLE
Bug: Music starting but does not sound.

### ISSUE THREAD

**Issue by cosmicfugues** [eritislami/evobot#128]
I'm playing music with "s!play blabla" command. Bot coming my room and bot says the song has started, but there is no sound. I created the Youtube API for the website (javascript), its true?

**Comment by cosmicfugues** [comment]
I create API again problem solved but why is this happening? This problem will probably occur again. No errors appear on my console.

**Comment by rexjohannes** [comment]
This can be a YouTube Ratelimit if you are at a shared host.

**Comment by peter2892** [comment]
i have the same issue, can i have some help fixing this?

**Comment by eritislami** [comment]
> i have the same issue, can i have some help fixing this?

It's hard to tell what is causing your issue without any errors/reasons for it
