### ISSUE TITLE
Bug: Showing this error

### ISSUE THREAD

**Issue by GokseLW** [eritislami/evobot#129]
(node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit

**Comment by rexjohannes** [comment]
You can ignore this.

**Comment by cosmicfugues** [comment]
Dinleyici sayısının fazlalığından dolayı memory leak olduğunu söylüyor. Bu hata değil uyarı sadece, görmezden gelebilirsin. İllaki ben çözmek istiyorum dersen RAM ile alakalı olabilir.

**Comment by GPM-50** [comment]
It is occured due ur system issue while running ignore this and restart the bot for fix
