### ISSUE TITLE
Playlist maximum queue is 9 sounds🐛 

### ISSUE THREAD

**Issue by mrpinkcat** [eritislami/evobot#1302]
**Describe the bug**
When i use `[prefix]play` command with a youtube playlist, the bot load 9 songs in queue, even if the playlist have more than 9 songs. 

**How To Reproduce**
Use the play command with a playlist that have more the 9 songs
 
**Expected behavior**
The bot should queue all the playlist

**Environment (add if possible)**
* Node.js version: 16 LTS

**Additional information & screenshots**

![Screenshot from 2022-10-12 14-59-38](https://user-images.githubusercontent.com/13932200/195349178-e9342faa-04dd-4c97-9afe-dfd7162f77b8.png)

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/blob/8ea1f21da4d817f4f328f1e74510daa1b95332c2/config.json.example#L3

**Comment by mrpinkcat** [comment]
Ho sorry ! I didn't understant that in that way.
The readme is incomplete for that part. Do you want me to do a MR for that ?
