### ISSUE TITLE
bot crashes after !stop command is used 

### ISSUE THREAD

**Issue by BomberH99** [eritislami/evobot#1316]
**Describe the bug**
when using the bot if the !stop command is used the bot ends the song and leaves the vc shortly after. when the bot leaves if throws a " Cannot destroy VoiceConnection - it has already been destroyed" error 

However if the bot runs its course and finishes and then leaves no error is caused and the bot coninues to work as intended
**How To Reproduce**
1.play a song using the bot 
2.while the music is playing use the !stop command to stop the music queue 
3. when the bot leaves it will crash 
 
**Expected behavior**
for the bot to leave and not crash 

**Environment (add if possible)**
* Node.js version: 19.01 

**Additional information & screenshots**
not a programmer so idk if this is important but the error seems to be originating from a node modual which could mean this is not the bots fault instead a error the functionality of the discord js API.
![image](https://user-images.githubusercontent.com/84206907/200150261-59089ff5-3efe-4c9c-896b-36b9367e795e.png)
(image of the terminal output after the crash

**Comment by doctorfamiliar** [comment]
I got the same bug.
