### ISSUE TITLE
Bot cant send messages when you renew token.

### ISSUE THREAD

**Issue by PixlGalaxy** [eritislami/evobot#1324]
**Describe the bug**
A description of what the bug is.

Now when you create a bot on discord/applications, the token it gives you is longer than the ones I got a few months ago. The bot dont reply to commands with this new token, I think this is caused because the lenght of the new token is longer than the ones that discord was used to give a year ago.

I tryed creating two new discord applications on the discord developer portal and renewing the bot token, it didnt work. But when I used the old token I got on a application I created almost a year ago, it works perfectly. The bot will reply to the messages if you use the old token that had 59 characters if im not wrong, the new one has 70.

**How To Reproduce**
1. Create a new discord application, if you already have one renew the token.
2. paste the token on the config file 
 
**Expected behavior**
A description of what you expected to happen.
the bot will appear online, but it will not reply to messages 

**Environment (add if possible)**
* Node.js version: I tryed these two versions, and i had the same issue: 16.13.1 & 18.12.1

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by PixlGalaxy** [comment]
It worked after activation MESSAGE CONTENT INTENT on the discord developer portal.

**Comment by eritislami** [comment]
Yep, I guess we can close this then
