### ISSUE TITLE
Bug: I get this error when trying to play music from soundcloud

### ISSUE THREAD

**Issue by JoJoSniper** [eritislami/evobot#133]
Error: scdl.downloadFromURL is not a function

Any fixes?

**Comment by eritislami** [comment]
Run `npm ls --depth 0` it should say that soundcloud-downloader is version `0.0.9` like this

```
$ npm ls --depth 0
evobot@0.6.2 C:\Users\Erit\evobot
+-- @discordjs/opus@0.3.2
+-- discord.js@12.2.0
+-- ffmpeg-static@4.2.5
+-- lyrics-finder@21.0.5
+-- simple-youtube-api@5.2.1
+-- soundcloud-downloader@0.0.9
+-- ytdl-core@3.1.2
-- ytdl-core-discord@1.2.1
```

if not delete npm_modules folder and copy package.json from the repo and run npm install again.

**Comment by xSphere1** [comment]
when play There was an error playing that Soundcloud track.

**Comment by Kvaced** [comment]
![image](https://user-images.githubusercontent.com/56303464/89101608-c990fe80-d401-11ea-8734-e824a11dcb2c.png)
I have the wrong version when I have the right version...

**Comment by eritislami** [comment]
> I'm getting a mistake when I do have the right version as you said earlier.

`Error: scdl.downloadFromURL is not a function`
I'm not even using this function in my current code, if you don't want to provide more details try reinstalling the project

**Comment by Kvaced** [comment]
ça pourrait venir d'ou alors ? @eritislami

**Comment by Kvaced** [comment]
what i need update for no more Error: scdl.downloadFromURL is not a function i don't want reinstall the project
