### ISSUE TITLE
🚀 Hybrid Command system will be so Nice to have.

### ISSUE THREAD

**Issue by Bassil-GG** [eritislami/evobot#1332]
it will bring the slash command system
and still have the prefix command system which majority of people still prefer
Have a nice day <3

**Comment by eritislami** [comment]
Hey Bassil, I see you probably closed this due to no response from my side and I agree that is unfortunate, but also I've rarely had time to contribute to this project anymore, I think we can keep it open as a future enhancement to be made, but I can't make any promises about the timing.

**Comment by RiemaruKarurosu** [comment]
I would want to help with this, but I've no experience with discordjs lib, I've start to rewrite some of the commands, but the structs quite confuse me with the new needs for the commands.
