### ISSUE TITLE
Detected server process in a crashed state

### ISSUE THREAD

**Issue by LIKEaBORZ** [eritislami/evobot#1334]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ npm run start
container@pterodactyl~ Server marked as running...
> evobot@2.3.1 start
> ts-node index.ts
/tmp/start-e8924333.sh: 1: ts-node: Permission denied
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 126
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ npm run start
container@pterodactyl~ Server marked as running...
> evobot@2.3.1 start
> ts-node index.ts
/tmp/start-4aef9d94.sh: 1: ts-node: Permission denied
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 126
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago

On  Windows:  through the command line, everything works fine, but after I upload the bot to the hosting , it does not work!
I've been suffering for a week now!

STARTUP COMMAND: npm run start
![6666666666](https://user-images.githubusercontent.com/42068399/209478886-b47c3fde-ac16-46ca-a055-7436ab6542e6.png)

**Comment by eritislami** [comment]
You're getting a `permission denied` error, this is due to your environment/server configuration, try running `npm run prod` to start the bot which will build and transpile typescript -> javascript, I don't see this as a bug

**Comment by LIKEaBORZ** [comment]
> You're getting a `permission denied` error, this is due to your environment/server configuration, try running `npm run prod` to start the bot which will build and transpile typescript -> javascript, I don't see this as a bug

The hosting assistant on which I put the bot helped me, thank you for your answer!

**Comment by SmegDan** [comment]
@LIKEaBORZ Do you host with sparkedhost? What did they set it to in the end?
