### ISSUE TITLE
Fix playing from mobile links

### ISSUE THREAD

**Issue by suhd00d** [eritislami/evobot#134]
Hi there,

For some reason evobot doesn’t recognize m.youtube.com or m.spotify.com, would you please be able to implement a fix? :) 

Thank you, I love the bot!

**Comment by eritislami** [comment]
Thanks will check it.

**Comment by suhd00d** [comment]
I'd like to also add that it doesn't recognize Soundcloud "set" links, like if I were to play a specific song in a "set" or playlist it returns undefined transcoding.

**Comment by eritislami** [comment]
Mobile links should work as of (4edfc5452624635dd3fce8e3ddb731da80d14853), soundcloud sets are not supported yet.
