### ISSUE TITLE
🐛 Name displayed when skipping, pausing or removing is incorrect

### ISSUE THREAD

**Issue by BenJoey** [eritislami/evobot#1348]
**Describe the bug**
The name shown int the message after using an emote command is the name of the song requester not the one who used the emote.

**How To Reproduce**
1. Have User A request a song
2. User B uses pause
 
**Expected behavior**
User B's name should be in the message not User A's

Hi, I recently forked your bot (awesome bot btw) and I noticed this.
This is my fix for it (this is probably not the best solution tbh): https://github.com/BenJoey/evobot/commit/7c4eed027907d6a36aba8a4dff80eee4254c02df

**Comment by eritislami** [comment]
Thank you, will look into this when I have some time

**Comment by Mirasaki** [comment]
Ohhh, it happens when the control buttons are clicked - not the commands
