### ISSUE TITLE
Bug: Videos less than 30 seconds on average not playing

### ISSUE THREAD

**Issue by cosmicfugues** [eritislami/evobot#136]
**Describe the bug**
Videos less than 30 seconds on average not playing

**How To Reproduce**
1. play video less than 30 seconds average
2. bot coming room and disconnecting.
 
**Expected behavior**
Bot says that the music starting when the bot enters the room and disconnecting instantly. **Videos longer than an average of 30 seconds working without errors.**

**Environment (add if possible)**
* Node.js version: 12

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
I tested 25 videos shorter than 30 seconds, some even 4-5 seconds and never had an issue, are you sure this isn't a network error or something else?

**Comment by cosmicfugues** [comment]
Its not network error, i have Status Code: 429, how can i fix them?

**Comment by eritislami** [comment]
https://httpstatuses.com/429 - Rate limiting, im going to close this issue because it's not related to the project, you can still continue commenting if you wish
