### ISSUE TITLE
🚀 Keep Message object

### ISSUE THREAD

**Issue by cshadd** [eritislami/evobot#1361]
**Is your feature request related to a problem? Please describe.**
This is not a problem if we ignore prefix commands, but I noticed when the slash commands were implemented the original prefix commands were removed due to the removal of the Message object.

**Describe the solution you'd like**
Is it possible to reimplement the Message object and keep it alongside the slash commands? This way both the slash commands or prefix commands can be used. Not sure if we can include both slash and message objects in the events.

**Comment by eritislami** [comment]
Yes that would be possible, but I don't want to be responsible for maintaining two systems now, I believe we should follow the standard for bots and that is why slash commands exist, to me supporting the old system feels like a step back.

If someone really really loves the old way they can use the release versions before slash commands were added, anyone can choose to fork this template and continue with their own path. It's just not something I want to do
