### ISSUE TITLE
Bug: Status code: 429

### ISSUE THREAD

**Issue by suhd00d** [eritislami/evobot#137]
1|TritanSh |     at TLSSocket.emit (events.js:314:20)
1|TritanSh |     at addChunk (_stream_readable.js:304:12)
1|TritanSh |     at readableAddChunk (_stream_readable.js:280:9)
1|TritanSh |     at TLSSocket.Readable.push (_stream_readable.js:219:10)
1|TritanSh | Error: Status code: 429
1|TritanSh |     at ClientRequest.<anonymous> (/root/tritanbot/node_modules/ytdl-core/node_modules/miniget/dist/index.js:150:31)
1|TritanSh |     at Object.onceWrapper (events.js:421:26)
1|TritanSh |     at ClientRequest.emit (events.js:314:20)
1|TritanSh |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
1|TritanSh |     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
1|TritanSh |     at TLSSocket.socketOnData (_http_client.js:509:22)
1|TritanSh |     at TLSSocket.emit (events.js:314:20)
1|TritanSh |     at addChunk (_stream_readable.js:304:12)
1|TritanSh |     at readableAddChunk (_stream_readable.js:280:9)
1|TritanSh |     at TLSSocket.Readable.push (_stream_readable.js:219:10)

**Comment by suhd00d** [comment]
Can someone tell me specifically if this is a coding issue or a rate limit from youtube?

**Comment by eritislami** [comment]
429 means too many requests, rate limited
