### ISSUE TITLE
🐛  Prefix won't change

### ISSUE THREAD

**Issue by Mykiz136** [eritislami/evobot#1384]
Changing the prefix in the config.json has no effect

**Comment by eritislami** [comment]
All discord bots are using slash commands now, if you really want the prefix you have to use 2.5.2 version

**Comment by Mykiz136** [comment]
> All discord bots are using slash commands now, if you really want the prefix you have to use 2.5.2 version

Why? I hate slash commands lol

**Comment by Mykiz136** [comment]
> All discord bots are using slash commands now, if you really want the prefix you have to use 2.5.2 version

Where do I find that version?
