### ISSUE TITLE
YouTube Compliance Issues & Help

### ISSUE THREAD

**Issue by suhd00d** [eritislami/evobot#139]
Hi there,
I got an email from YouTube stating that this is not in compliance with them due to the fact that we store data for 12 months. Can you please help me find the code so I can change it from 12 months to 30 days? The report is pasted below.  I have 15 days to fix the issue or they won't remove the IP ban. 

July 27, 2020
ToS Violations Report V.1 YouTube API Services-Developer Policies
Violations that require immediate resolution:
E. Handling YouTube Data and Content (l​ ink​)
Policy #​: III.E.4.a-g​ (Refreshing, Storing, and Displaying API Data) (​link​)
● Violation: ​API Client is storing data for more than 30 days.
Proposed Solution: ​Regarding data storage, we only allow the API Clients to store the public data temporarily, but not more than 30 days and the stored data must either be refreshed or deleted after 30 days

**Comment by suhd00d** [comment]
![E0866FCE-8BFF-445B-8167-1B23C5B3ABDE](https://user-images.githubusercontent.com/55116398/88565399-89490f00-d002-11ea-8c5f-71ce39675cec.jpeg)

**Comment by eritislami** [comment]
Ive been using the youtube api for years now and never seen anything like this, the only thing that uses the api key in my bot is the [simple-youtube-api](https://github.com/tjrgg/simple-youtube-api) package, i don't see how it would store data anywhere..

**Comment by suhd00d** [comment]
Exactly, I spent even a few hours looking through the node modules and bot and I couldn't find anywhere that states we store data unless it's through Opus when downloading. Do you have any suggestions? I'm at a complete loss and I don't want to just stop the bot's production I've been working on lol

**Comment by suhd00d** [comment]
Could it possibly be these?
    "ytdl-core": "^3.1.0",
    "ytdl-core-discord": "^1.2.1"

**Comment by eritislami** [comment]
> Could it possibly be these?
> "ytdl-core": "^3.1.0",
> "ytdl-core-discord": "^1.2.1"

No, they don't use the api

**Comment by eritislami** [comment]
I will be closing this as there is nothing i can do to fix, you can still continue discussing if you wish.
