### ISSUE TITLE
🐛 Same as discussion "Playlist Larger than 100 songs crashing bot #1354"

### ISSUE THREAD

**Issue by diespinozah** [eritislami/evobot#1397]
**Describe the bug**
When you queue a playlist larger than 100 songs the bot crashes

**How To Reproduce**
1. queue a playlist largar that 100 songs
2. bot joins the channel and crashes.
 
**Expected behavior**
limit the queue with the value setted on config.js or queue all the songs

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**

![error1](https://user-images.githubusercontent.com/49412551/229953223-1acefe4e-a651-44de-a473-a739ea4edb28.PNG)
![error2](https://user-images.githubusercontent.com/49412551/229953242-15036cc5-dd70-4846-9d47-6c7e538c948c.PNG)
![error3](https://user-images.githubusercontent.com/49412551/229953253-ab30b3c1-e1c8-4213-8bcc-3327a80a2f1b.PNG)
![error4](https://user-images.githubusercontent.com/49412551/229953262-4bed6b6b-541c-4614-83b0-d7de85e116c0.PNG)
![error5](https://user-images.githubusercontent.com/49412551/229953282-ac360aa5-3293-44e5-a292-860f4437011f.PNG)

**Comment by eritislami** [comment]
I see this is a embed description field issue with the character limit, not directly connected to the number of songs that the bot will queue, will check this out when I can

**Comment by diespinozah** [comment]
@eritislami also when playlist command worked fine it always truncate the queue to 100 even when MAX_PLAYLIST_SIZE were 1000 and the playlist has 150 songs for example

**Comment by Kunumi-Gab** [comment]
+1 to this issue, for a workaround create a playlist using youtube music songs

**Comment by Unnil** [comment]
```typescript
.setDescription(playlist.videos.map((song: Song, index: number) => `${index + 1}. ${song.title}`).join("\n").slice(0, 4095))
``` 

I was able to fix this by adding a slice in the description on line 87 of the commands/playlist.ts

It seems that discordjs does not like descriptions that have more than 4096 characters. When playing long playlists it will go over that number.

@eritislami, wasnt able to do a PR right now but will do later.
