### ISSUE TITLE
Soundcloud playing issue

### ISSUE THREAD

**Issue by Sakura-49** [eritislami/evobot#140]
Some songs from soundcloud does not plays instead it gives this error :
``` Stream error: Could not find media with specified format: (audio/ogg; codecs="opus") ```
and leaves the voice channel....

**How To Reproduce**:
* A sample music command : ```!play https://soundcloud.com/marshmellomusic/alone```
 
**Expected behavior**:
Its should play but i think opus codec is missing for some songs

**Environment (add if possible)**:
* Node.js version: 12.18.3

**Screenshot**:
![asas](https://user-images.githubusercontent.com/68957183/88808573-b3502c00-d1d0-11ea-8dec-5dfc25243f01.PNG)

**Comment by eritislami** [comment]
Should be working as of latest commit, thanks for contributing
