### ISSUE TITLE
🐛 This interaction failed

### ISSUE THREAD

**Issue by dillfrescott** [eritislami/evobot#1400]
When using `/search` and choosing a song, it says "This interaction failed"

![Screenshot 2023-04-08 201454](https://user-images.githubusercontent.com/56714680/230747819-2b2aa7a1-f73f-4846-82a3-bf0c3263e68a.png)

hosted using docker

**Comment by eritislami** [comment]
Depends what error you got in the console, if you can share that.

**Comment by zdooder** [comment]
I worked around this by upgrading discord.js to 14.8.0.  No idea if there are any counterindications yet, but it seems to have resolved the error for me.
