### ISSUE TITLE
I can't play music

### ISSUE THREAD

**Issue by lorenzoalinovi** [eritislami/evobot#141]
When I play music my bot gives me this:

Could not join the channel: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.

**Comment by AmadeusWolf** [comment]
Your internet is slow and the bot is not connecting properly. this is something on your end, not the code.

**Comment by lorenzoalinovi** [comment]
I have 40ms on discord and i'm hosting it on repl.

**Comment by Unkn0wnNode** [comment]
I mean repl should be able to run this but the only thing that could be causing an issue is UDP being blocked.
