### ISSUE TITLE
Bug: Lyrics-finder does not support Turkish letters (Ğ,Ü,Ş,İ,Ö,Ç)

### ISSUE THREAD

**Issue by xlegendryx** [eritislami/evobot#143]
[screenshot.](https://hizliresim.com/PQQsGU)

* Node.js version: 12.0.1

I upload screenshot. Actually it should be like this

Bu gece yanımda olsan
Yüzüne gonca kondursam
Küçücük avuçlarında
Sana masallar anlatsam

**Comment by eritislami** [comment]
You can make an issue here: https://github.com/alias-rahil/lyrics-finder
