### ISSUE TITLE
🐛 Error: Used Disallowed intents

### ISSUE THREAD

**Issue by mikailreialt** [eritislami/evobot#1435]
**Describe the bug**
when I run npm run start or npm run prod

**How To Reproduce**
1. typed npm run start
2. typed npm run prod
 
**Expected behavior**
Its Suppose to be run perfectly
**Environment (add if possible)**
Node js Command prompt
* Node.js version: 18.16.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://github.com/eritislami/evobot/assets/135125031/3c758f60-27dc-485d-bea0-8c32b54e421e)
![image](https://github.com/eritislami/evobot/assets/135125031/d4641dcf-0abf-42ee-a992-e4e244f2555d)

**Comment by fedorkanin** [comment]
Were you able to resolve the issue?

**Comment by ryzhovalex** [comment]
Got the same error. The problem was in enabling the intents in the discord's bot's configuration window ("Bot" pane).

> 1.1. Enable 'Message Content Intent' in Discord Developer Portal
