### ISSUE TITLE
🚀 Having both Discord built-in slash commands and custom commands (with custom prefix)

### ISSUE THREAD

**Issue by TheJoshue** [eritislami/evobot#1437]
**Is your feature request related to a problem? Please describe.**
like before version Evobot 2.0, to have ability to set custom prefix symbol to use "!play" for example instead of nowadays build-in command /play

**Describe the solution you'd like**
Adding also option to enable legacy commands (not built in)

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by eritislami** [comment]
I understand but I'm not interested in taking this direction with the bot

**Comment by TheJoshue** [comment]
> I understand but I'm not interested in taking this direction with the bot

i understand you
will you please want to fork your evobot and make this available only for me? i will donate if you want.

My discord: De Baker Cat#3962
