### ISSUE TITLE
🚀 Make able to use spotify link to play song

### ISSUE THREAD

**Issue by TheJoshue** [eritislami/evobot#1438]
**Is your feature request related to a problem? Please describe.**
No, it's an addition

**Describe the solution you'd like**
Adding spotify links supported besides youtube links

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by TheJoshue** [comment]
anyone?

**Comment by LucaBarbaLata** [comment]
There is already a pull request opened. Just modify the code

⁣Get BlueMail for Android ​

**Comment by eritislami** [comment]
Closing as old and not planned.
