### ISSUE TITLE
🐛 Song stops playing before actual ending

### ISSUE THREAD

**Issue by AitakattaSora** [eritislami/evobot#1455]
**Describe the bug**
Song stops playing before its actual ending. It happens randomly and I think it has something to do with the stream from play-dl library. Maybe the stream is shorter than the actual song length. Does someone face this issue too? It happens maybe once in 10 plays.

**How To Reproduce**
1. Play a song from youtube
 
**Expected behavior**
Song plays till finish without stopping

**Environment (add if possible)**
* Node.js version:  16.15.0

**Comment by tomaszkalisiak-digica** [comment]
I have the same issue. But it happens every time.

**Comment by Bobini1** [comment]
I have the same issue. But it keeps happening every time.
