### ISSUE TITLE
Song Length

### ISSUE THREAD

**Issue by AmadeusWolf** [eritislami/evobot#146]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]
Something to show the song duration and how long its been playing for
**Describe the solution you'd like**
A description of what you want to happen.
so you can see on the nowplaying or when you play a song exactly how long it is
**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
![image](https://user-images.githubusercontent.com/68157877/89189021-528d6e80-d597-11ea-9e2c-ec6ec6ad5931.png)

**Comment by eritislami** [comment]
Merged #147 thank you @Sparker-99
