### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by Lok3rn3t** [eritislami/evobot#1466]
**Describe the bug**
A description of what the bug is.
Bot crashes when searching for `phonk` music

**How To Reproduce**
1. Bot crashes when searching for `phonk` music

**Environment (add if possible)**
* Node.js version: 20.4.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
https://prnt.sc/smFW8AvTPd8S

**Comment by eritislami** [comment]
Probably fixed in [2.8.1](https://github.com/eritislami/evobot/releases)
