### ISSUE TITLE
Please add live stream support.

### ISSUE THREAD

**Issue by Abhinash76** [eritislami/evobot#148]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by ElijahRus250** [comment]
not in the api

**Comment by TEOIMFO** [comment]
How to fix error, to can normal play stream from yt?

**Comment by SugarD-x** [comment]
Please see the other issues, and post your own if none of them are applicable. This is for a separate issue.
