### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#149]
![Screenshot_20200807-095448](https://user-images.githubusercontent.com/53672750/89607385-3be76000-d894-11ea-8ed1-701250d0d3fe.png)
![Screenshot_20200807-095456](https://user-images.githubusercontent.com/53672750/89607390-40ac1400-d894-11ea-9221-7f87d067ba26.png)
![Screenshot_20200807-095506](https://user-images.githubusercontent.com/53672750/89607397-46095e80-d894-11ea-8441-8f45507fc2a0.png)

**Comment by eritislami** [comment]
https://support.glitch.com/t/an-update-on-pinging-services-glitch/27311

Glitch has banned discord bots/auto ping apps, don't make any more issues regarding this, it's not supported.
