### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by Ashiito** [eritislami/evobot#1498]
**Describe the bug**
After starting the music (link or not) the bot connects to the voice channel, but does not play the sound, and later leaves it. The latest available version of the bot, node, is used.js v18. The control panel is pterodactyl. There are no errors in the console

**Environment (add if possible)**
* Node.js version: 18

**Comment by eritislami** [comment]
There is something causing it on your side, need more info

**Comment by eritislami** [comment]
Closing due to out of date
