### ISSUE TITLE
There was an error executing that command. 

### ISSUE THREAD

**Issue by shweegl** [eritislami/evobot#1501]
**Describe the bug**
Whenever I play a song it gives me an error: 
"There was an error executing that command. "
I'm running it via docker with the command provided in the github readme
`docker run -e "TOKEN=<discord-token>" eritislami/evobot`

**How To Reproduce**
1. /play youtube link or /play song title 
2. error thrown
 
**Expected behavior**
Bot joining the voice call and playing music 

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![Screenshot_1](https://github.com/eritislami/evobot/assets/27150301/a90c7414-9ab9-4974-9faf-90e0295305fb)

**Comment by eritislami** [comment]
Using newest version ?

**Comment by eritislami** [comment]
> I'm using the docker container you're providing with my discord token.

Check if you are using the latest container version, if not just delete the container and re-pull newest

**Comment by shweegl** [comment]
Thank you it worked!
