### ISSUE TITLE
🐛 Error message when stop interaction is executed using emoji below song

### ISSUE THREAD

**Issue by itsmemac** [eritislami/evobot#1502]
**Describe the bug**

Whenever you press the "Stop_button" emote below the song to stop the song, you receive an error message in the console log.
Eventually the music stops without an issue instantly but it leaves an error message in log

![image](https://github.com/eritislami/evobot/assets/37410297/fecc9fe9-e46b-4e36-b460-eb075d61bf53)

**How To Reproduce**
1. Play a song
2. Click Stop emoji below the song in discord channel
 
**Expected behavior**
No errors in console when stop_button is executed

**Environment (add if possible)**
* Node.js version: 16

**Additional information & screenshots**
```
Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:102:46)
    at Object.execute (/home/container/commands/stop.ts:17:17)
    at ReactionCollector.<anonymous> (/home/container/structs/MusicQueue.ts:277:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'InteractionAlreadyReplied'
}
```
![image](https://github.com/eritislami/evobot/assets/37410297/5d95de6a-0af8-4c84-bf66-40eadef90955)

**Comment by itsmemac** [comment]
Any update on this ?

**Comment by eritislami** [comment]
> Any update on this ?

Hi, I feel bad for putting off the list of issues in this project for so long but it's very difficult for me to find time to take a look and dedicate some time for the project as I have many other responsibilities, but I will try my best to block some time off and go over the list of existing issues.

**Comment by itsmemac** [comment]
> > Any update on this ?
> 
> Hi, I feel bad for putting off the list of issues in this project for so long but it's very difficult for me to find time to take a look and dedicate some time for the project as I have many other responsibilities, but I will try my best to block some time off and go over the list of existing issues.

Thank you for this amazing bot and please do take your time as this issue doesn't cause any issue with the bots function, just error logs growing.

**Comment by eritislami** [comment]
Closing due to out of date
