### ISSUE TITLE
Save Songs to a Playlist Feature.

### ISSUE THREAD

**Issue by heartsiddharth** [eritislami/evobot#151]
**Is your feature request related to a problem? Please describe.**
No this is not  a problem.

**Describe the solution you'd like**
What ideally should happen is after adding the songs in the que , user can save the queue songs to a playlist. And later whenever he wants to listen to the same playlist , He can just use /playlist <saved playlist name> 

**Describe alternatives you've considered**
Currently playlist is taking YT playlist.

**Additional context**
Please add this feature.

**Comment by SugarD-x** [comment]
This would be an amazing enhancement that puts the bot on par with some of the more popular music bots out there.

**Comment by ThaddeusKKR** [comment]
For playlist saving, something like [hastebin](https://hastebin.com) could be used (1 YouTube link per line or something)

**Comment by ParasDeshpande** [comment]
just save the playlists as map of (song-names, yt-link) in a map of (playlist-name, playlist-songs) for each guild...
Maybe in a keyv database, coz thats the simplest ig...
something like
```
guildPlaylists: Map([
                ['<playlist-name>', Map([
                    ['song-1', 'youtube-link']
                ])]
            ])
```
🤔
