### ISSUE TITLE
🐛 max listeners exceeded warning.

### ISSUE THREAD

**Issue by FirestormeDS** [eritislami/evobot#1522]
**Describe the bug**
A description of what the bug is.

it shows this message but after that it shows {mybot } is ready, then when i run any command the program reboot and the bot restart too, everytime it reboot i run one command and he restart

**Environment (add if possible)**
* Node.js version: node 20

**Additional information & screenshots**

here is a screenshot
![Screenshot_20231024_210230_Chrome](https://github.com/eritislami/evobot/assets/62776195/2f491427-9e77-4f10-ac3f-96260136063a)

**Comment by eritislami** [comment]
It's just a warning those listeners will not increase.

**Comment by LucaBarbaLata** [comment]
@FirestormeDS can you help me with something 

I see you managed to run the bot in a wings daemon
And i want to ask you how you managed to run it without this error. (screenshot attached)
![Screenshot_2024-04-22-09-15-28-98_4d38fce200f96aeac5e860e739312e76](https://github.com/eritislami/evobot/assets/88965309/0a478cc8-b6bf-4d80-877e-00471d882a6d)

**Comment by FirestormeDS** [comment]
try to look at the node.js version like trying older version or something
like that maybe you missed something on the config file.
