### ISSUE TITLE
🐛 Unable to play music on soundcloud

### ISSUE THREAD

**Issue by haruma1115** [eritislami/evobot#1524]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.When I use the 'play' command and enter the Soundcloud webpage, it gets stuck at 'loading'.
2.https://i.imgur.com/X1vcLj0.png
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: v18.16.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
https://i.imgur.com/P4jMzOZ.png

Sorry, my English is not very good. I hope I can express my problem clearly. Thank you.

**Comment by eritislami** [comment]
Soundcloud is not supported

**Comment by haruma1115** [comment]
> Soundcloud is not supported

ok thank you!
