### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by cloudedaim** [eritislami/evobot#1526]
**Describe the bug**
Age restriction & API

**How To Reproduce**
1. Start the bot
2. Try to play an age restricted video
 
**Expected behavior**
Play it instead of spitting out:
Error: While getting info from url
Sign in to confirm your age

**Environment: Debian 12**
* Node.js version: 16.11.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Youtube doesn't allow playing age restricted videos without a youtube account, the bot does not use a youtube account it's public scraping

**Comment by rockrevenchy** [comment]
Actually there is a way to fix this and i did open an issue then closed it once i found a fix for it #1490

https://github.com/eritislami/evobot/issues/1490

Perhaps it could be worth to add that info to the wiki or readme or pinned issues
