### ISSUE TITLE
The bot remains in the voice channel forever

### ISSUE THREAD

**Issue by Jordaar** [eritislami/evobot#153]
I would love if the bot remains in the voice channel forever...and play a playlist looped by me...

THANKS!

**Comment by SugarD-x** [comment]
This would be amazing if we could toggle this. Many open source bots have it, and many paid bots make you pay extra for it. It would be awesome to have this feature!

**Comment by SugarD-x** [comment]
This would be amazing if we could toggle this. Many open source bots have it, and many paid bots make you pay extra for it. It would be awesome to have this feature!

**Comment by Cy1der** [comment]
Since the bot does not detect if no one is in a vc, just play a playlist and set it to loop...

**Comment by SugarD-x** [comment]
The bot doesn't have playlist support, and it _does_ detect if anyone is in the voice channel.

**Comment by dylanjamesdev** [comment]
This has been resolved with a recent patch.
