### ISSUE TITLE
Make the bot never leave the voice channel

### ISSUE THREAD

**Issue by Jordaar** [eritislami/evobot#154]
I would love to see a feature in these bot that don't allow the bot to disconnect from the voice channel..

**Comment by KizutoChan** [comment]
But if the bot doesn't automatically disconnect, it will cause problems

**Comment by Jordaar** [comment]
There are many discord bot's that don't leave voice channel...take for example Groovy.....is there a possible way to do this?

**Comment by eritislami** [comment]
Duplicate of #153
