### ISSUE TITLE
Bug: error status code: 429

### ISSUE THREAD

**Issue by ABotDev** [eritislami/evobot#155]
**Describe the bug**
doesn't play any music any more
 
**Expected behavior**
Playing music

**Environment (add if possible)**
* Node.js version: "node": ">=12.0.0"

**Additional information & screenshots**
in discord: 
<img width="108" alt="2020-08-14 (2)" src="https://user-images.githubusercontent.com/66113328/90280418-30370300-de6b-11ea-8433-2ca39e598c9b.png">
in console:
<img width="556" alt="2020-08-14 (4)" src="https://user-images.githubusercontent.com/66113328/90280694-a50a3d00-de6b-11ea-966a-c96a888d3f37.png">

**Comment by eritislami** [comment]
Error 429 mean's too many requests have been made in a short time and it's rate limited. Try again later..

**Comment by ABotDev** [comment]
i tried again fk 7days later still get this fk error.

**Comment by eritislami** [comment]
> i tried again fk 7days later still get this fk error.

Well there is a chance your IP is blocked, you could try with a vpn or different ip somehow
