### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by chintu548** [eritislami/evobot#161]
**Playlist feature **
When you play a playlist from youtube with more than 10 songs and skip to the 11th song the playlist ends 

**How To Reproduce**
Steps to reproduce the behaviour:
1.play a playlist from youtube 
2.skip to 11th song 
 
**Expected behaviour**
It should play the 11th song

**Comment by chintu548** [comment]
Please fix this bug

**Comment by eritislami** [comment]
Test: https://imgur.com/a/jdCMQkk

I think you are missing something here, did you get any errors in chat or from console?
