### ISSUE TITLE
🚀  Health Checks

### ISSUE THREAD

**Issue by djpiper28** [eritislami/evobot#1620]
**Is your feature request related to a problem? Please describe.**
Sometimes the bot will not respond to commands, and requires a restart. I run the app within a kubernetes cluster and ideally it will have the ability to add a healthcheck so that my cluster can restart the bot when it isn't working.

**Describe the solution you'd like**
The bot runs an express server (or similar), with a singular healthcheck endpoint. This tries to ping discord, if it can it returns a 200 code, otherwise a 500 code. This means my cluster can detect failure and restart the offending pod.

**Describe alternatives you've considered**
n/a

**Additional context**
App runs in kubernetes.

**Comment by eritislami** [comment]
I understand your need for this change but I feel it is outside of the needs of the average user, adding an entire express server to the project feels to me like it is outside of the domain of the project, it's more so something end-users can implement on their own, as for now the bot does have a ping command which returns the API latency to Discord.

**Comment by djpiper28** [comment]
> I understand your need for this change but I feel it is outside of the needs of the average user, adding an entire express server to the project feels to me like it is outside of the domain of the project, it's more so something end-users can implement on their own, as for now the bot does have a ping command which returns the API latency to Discord.

If I were to add this feature and put it behind a feature flag that defaults to disabled is that okay?

**Comment by eritislami** [comment]
> > I understand your need for this change but I feel it is outside of the needs of the average user, adding an entire express server to the project feels to me like it is outside of the domain of the project, it's more so something end-users can implement on their own, as for now the bot does have a ping command which returns the API latency to Discord.
> 
> If I were to add this feature and put it behind a feature flag that defaults to disabled is that okay?

For this repository my main point is that i don't want to accept a PR for something that i don't feel comfortable maintaining, I think a more lightweight solution would be to run a restart command via [PM2](https://pm2.keymetrics.io/) to restart the bot since that is something that i am more familiar with, if not then you are free to modify the code in your version of the bot.

**Comment by djpiper28** [comment]
What I've don't is forked the repo and added the functionality I needed there. There are a few other bug fixes I might work on when I have time and I'll pr those into the main repo.
