### ISSUE TITLE
Bug: "No videos was found with a matching title"

### ISSUE THREAD

**Issue by Jovantri10** [eritislami/evobot#167]
![Screen_20200823_114043_e001](https://user-images.githubusercontent.com/51161901/90971002-bfac7800-e535-11ea-8926-1458e961aa1a.jpg)

**Comment by Jovantri10** [comment]
pepek owner tolol

**Comment by raghust3t** [comment]
same thing happening with me

**Comment by abrar1122** [comment]
Same problem with me..please solve it

**Comment by Unkn0wnNode** [comment]
This happened to me and this was because the IP I was using was rate limited. Since I was on heroku I was able to swap out my IP's but to confirm this you need to go into your console where your bot is hosted and look to see if you get a status code 429

**Comment by Thirteen-1123550** [comment]
same thing happening with me

**Comment by SugarD-x** [comment]
Make sure your YouTube API key is set within ```config.json```. You may need to revisit your YouTube API account to activate it for the correct API settings. I had to do this after actually making the API key, which was very misleading.
