### ISSUE TITLE
No video found/ 403 forbidden

### ISSUE THREAD

**Issue by Sup-Sup123** [eritislami/evobot#172]
The console keeps logging/saying 

code: 403,
  message: 'Requests from referer <empty> are blocked.',
  errors: [
    {
      message: 'Requests from referer <empty> are blocked.',
      domain: 'global',
      reason: 'forbidden'
    }
  ],
  status: 'PERMISSION_DENIED'

**Comment by Clu3l3s3** [comment]
Make sure that your youtube api key is correct.

**Comment by Sup-Sup123** [comment]
It is correct

**Comment by SugarD-x** [comment]
Make sure it is surrounded by quotes in your ```config.json``` file or it also won't work. You may also have to go to your account again and make sure it is set to use the correct API settings, else it won't enable for use with the bot.

**Comment by RaymondJiang1** [comment]
Hey, the 403 means that either youtube blocked the IP that you are hosting the bot from and/or your youtube API key is wrong.
