### ISSUE TITLE
joining voice channel delay

### ISSUE THREAD

**Issue by BjarnM** [eritislami/evobot#176]
Works great but when I type "!p *link*" it joins the voice channel after 10 seconds and starts the song after 5 seconds.
All another commandos is a quick respond.

Bot is running on VPS [UK server]
CPU Cores: 2
Total CPU Speed: 4.8GHz
Memory: 2GB
Disk Space: 40GB
Bandwidth: 2000GB

language: discord.js

**Comment by suhd00d** [comment]
Most likely the memory or internet speed is too low. When it takes time to play the music, it’s simply because it’s downloading the song. :)
