### ISSUE TITLE
Bug: The bot isn't joining the voice channel

### ISSUE THREAD

**Issue by DynamoYT** [eritislami/evobot#179]
![unknown](https://user-images.githubusercontent.com/63182360/92305287-81866e00-efa3-11ea-80b1-94af315e35c4.png)
The bot isn't joining the voice channel

**Comment by eritislami** [comment]
This is because it's already playing in a different channel, to change the channel you need to end the queue first, not a bug

**Comment by DynamoYT** [comment]
Can you make it like if someone disconnects the bot from the voice channel so this will delete the full queue?

**Comment by suhd00d** [comment]
You can add a leave command.

**Comment by canopus310** [comment]
i have this issue but it isnt playing in any other channels
