### ISSUE TITLE
Some small bugs

### ISSUE THREAD

**Issue by DPulavarthy** [eritislami/evobot#18]
![error](https://user-images.githubusercontent.com/44714849/80130894-f5792a00-855e-11ea-97c5-976e8afea687.png)
`1.)` Short YouTube links give me this error, but normal links and playlists links are fine.
`Error: No playlist ID found in URL: https://youtu.be/vjhFsPNk6Po`

`2.)` The bot sometimes stops playing music for a few seconds and then skips to the next song or ends the queue.

`3.)` Every once in a while it stops playing and then sends this error
`HTTPError [FetchError]: request to https://discordapp.com/api/v7/channels/663187945246687232/messages failed, reason: write ECONNABORTED
    at RequestHandler.execute (C:\Users\USER\Documents\Discord Bots\kasumi\node_modules\discord.js\src\rest\RequestHandler.js:107:21)`

**Comment by eritislami** [comment]
Thanks for posting, i have a fix ready for the link issue, I believe the 'ECONNABORTED' error happens because your bot instance has lost connection to discord api

**Comment by DPulavarthy** [comment]
Alright

**Comment by eritislami** [comment]
youtu.be links should be working as of 8cff648a09b2a7

**Comment by eritislami** [comment]
I have added extra error catching and more buffering to YTDL in 0cd74f0 i would appreciate if you could test these new changes and see if it's better or not, thanks

**Comment by DPulavarthy** [comment]
![network](https://user-images.githubusercontent.com/44714849/80522192-ca714a80-8951-11ea-8920-da69f37f08be.png)
Even with a weak connection the bot continues to play, thanks for fixing!
