### ISSUE TITLE
Error: Total value is either not provided or invalid

### ISSUE THREAD

**Issue by Barracuda1337** [eritislami/evobot#180]
![Ek Açıklama 2020-09-05 224720](https://user-images.githubusercontent.com/53797515/92312507-d6d57600-efc9-11ea-871d-52fd4ea096a5.png)
![image](https://user-images.githubusercontent.com/53797515/92312513-e6ed5580-efc9-11ea-9ef3-809483fb4c17.png)

**Comment by eritislami** [comment]
Which commit are you on? i pushed a fix for this 2 days ago, 6c19eefdf28826fe546b0b89333ff9376163298e
