### ISSUE TITLE
Embed play view with thumbnail

### ISSUE THREAD

**Issue by lakhindar572** [eritislami/evobot#182]
Please embed the play view command. I mean when we play a song, the output will be embedded with the video thumbnail, hyperlink in song title, and obviously reaction control Emoji in it. 😅. Now it simply post just the title and video link (with reaction control emoji).

**Comment by suhd00d** [comment]
The thumbnail would be hard to get from a discord aspect. You can however make the embeds yourself. I forked this repo and built a bot on top of the music aspect so it’s definitely doable. I turned everything into embeds but the playing response.
