### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DynamoYT** [eritislami/evobot#187]
![Screenshot 2020-09-11 221901](https://user-images.githubusercontent.com/63182360/92951960-d54df700-f47c-11ea-80c1-382101803f4d.png)
 Playlist issue. See what playlist I have played and what song bot is playing.

**Comment by DynamoYT** [comment]
![Screenshot 2020-09-11 221846](https://user-images.githubusercontent.com/63182360/92952041-f282c580-f47c-11ea-8cba-8cfd9683d26c.png)

**Comment by razeNFR** [comment]
Yeah, i have the same issue, i dont know how to solve that :/

**Comment by chino-chan1** [comment]
is that your own playlist? if not, bot can't play playlist that was made automatically by youtube, like my mix in your youtube home page.

**Comment by razeNFR** [comment]
But isnt possible to do that ? Rythm and Fredboat can play that type of playlist

**Comment by eritislami** [comment]
Not a bug, mixes are created for the account only, you can save the mix as a public playlist if you want to play it.
