### ISSUE TITLE
Error when playing music

### ISSUE THREAD

**Issue by sosita213** [eritislami/evobot#190]
Im getting error when use play command error: Could not find player config what is this error and how i can fix it ?

**Comment by Hezaus** [comment]
yea i got it to the bot keep connet ahd auto disconnet the VC did you figure out how to fix it? i got you api key arelady but it still not working

**Comment by mikeemiks27** [comment]
try installing the module i fixed mine

**Comment by sosita213** [comment]
Which module ?

**Comment by mikeemiks27** [comment]
ytdl-core-discord

**Comment by sosita213** [comment]
Ok thanks 😄

**Comment by Hezaus** [comment]
i still doesn't help me :(

**Comment by ejasecond** [comment]
update the ytdl

**Comment by eja0iq** [comment]
update the ytdl

**Comment by SugarD-x** [comment]
It's a known issue with the dependencies. See this issue here:
https://github.com/amishshah/ytdl-core-discord/issues/232

**Comment by Hezaus** [comment]
ok thank you :)

**Comment by SugarD-x** [comment]
Once the ytdl-core-discord dependency is updated in the package.json/package-lock.json by the bot's author to the latest version, this issue should be resolved.

**Comment by eritislami** [comment]
> Once the ytdl-core-discord dependency is updated in the package.json/package-lock.json by the bot's author to the latest version, this issue should be resolved.

There is no need for that since it's not a major version update, simply installing packages will get the latest version
