### ISSUE TITLE
"`info.length_seconds` will be removed in a near future release" message when bot starts

### ISSUE THREAD

**Issue by Yankue** [eritislami/evobot#194]
Whenever I run the bot, it gives the message:
`'info.length_seconds' will be removed in a near future release, use 'info.videoDetails.lengthSeconds' instead.`
Is this anything to worry about, and if so how do I fix it?

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/blob/93351dd73d9eef23268fa4f770ac00d992164504/commands/play.js#L65

It's already using the recommended property, perhaps you are on an older commit/old ytdl version?
Try updating your packages

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/blob/93351dd73d9eef23268fa4f770ac00d992164504/commands/play.js#L65

It's already using the recommended property but i think ytdl-discord still hasnt updated

**Comment by SugarD-x** [comment]
It is indeed ytdl-core-discord at fault. See here: https://github.com/amishshah/ytdl-core-discord/issues/244

**Comment by eritislami** [comment]
Thanks @SugarD-x this is now fixed, make sure to run `npm install` to get the latest version.
