### ISSUE TITLE
Error with the search command

### ISSUE THREAD

**Issue by Oxadeum** [eritislami/evobot#195]
Hey ! ^^

I have a error with the search command

`(node:5544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voice' of undefined`

Thank's for your help

**Comment by IamAdren** [comment]
https://prnt.sc/ukb4k7
Works perfect for me.

**Comment by Oxadeum** [comment]
yes but if i choose the music, the bot don't join the channel and I have the error `TypeError: Cannot read property 'voice' of undefined`

**Comment by RaymondJiang1** [comment]
Sometimes it does that.
