### ISSUE TITLE
Bot stops playing the song after some time and gives this error...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#20]
> events.js:288
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Status code: 416
>     at ClientRequest.<anonymous> (D:\Bots\evobot-master\node_modules\miniget\dist\index.js:128:27)
>     at Object.onceWrapper (events.js:418:26)
>     at ClientRequest.emit (events.js:311:20)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
>     at TLSSocket.socketOnData (_http_client.js:476:22)
>     at TLSSocket.emit (events.js:311:20)
>     at addChunk (_stream_readable.js:294:12)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at TLSSocket.Readable.push (_stream_readable.js:209:10)
> Emitted 'error' event on PassThrough instance at:
>     at errorOrDestroy (internal/streams/destroy.js:108:12)
>     at PassThrough.onerror (_stream_readable.js:746:7)
>     at PassThrough.emit (events.js:311:20)
>     at PassThrough.<anonymous> (D:\Bots\evobot-master\node_modules\ytdl-core\lib\index.js:133:14)
>     at PassThrough.emit (events.js:323:22)
>     at ClientRequest.<anonymous> (D:\Bots\evobot-master\node_modules\miniget\dist\index.js:133:28)
>     at Object.onceWrapper (events.js:418:26)
>     [... lines matching original stack trace ...]
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)

**Comment by eritislami** [comment]
I have added extra error catching and more buffering to YTDL in 0cd74f0603 i would appreciate if you could test these new changes and see if it's better or not, thanks

**Comment by ParasDeshpande** [comment]
**Now it works fine **_👍_
