### ISSUE TITLE
Bug: NowPlaying can't show the real times when playing playlist

### ISSUE THREAD

**Issue by chino-chan1** [eritislami/evobot#200]
**Describe the bug**
imagine i want to play never gonna give you up. i use "<prefix>play never gonna give you up", it can show the real duration of the song. but, when i'm using "<prefix>playlist rick astley" or "<prefix>p https://example.com/urplaylist", it shows 24h of music duration.

**Environment (add if possible)**
* Node.js version: v12.0.0

**Additional information & screenshots**
![Screenshot_20200922-185131_Discord.jpg](https://user-images.githubusercontent.com/60313514/93879177-75214580-fd05-11ea-916d-e47d095b85bc.jpg)
![Screenshot_20200922-185159_Discord.jpg](https://user-images.githubusercontent.com/60313514/93879198-7c485380-fd05-11ea-8889-7e3c514e69f0.jpg)

**Comment by eritislami** [comment]
Yes i am aware of this, the problem is when the playlist is retrieved there is no individual duration value for each song, using youtube-simple-api
