### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by FtwWolf123** [eritislami/evobot#201]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.Error: Cannot find module './config.json'
2.Error: Cannot find module './config.json'
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Copy and rename config.json.example to config.json then fill in the values.
