### ISSUE TITLE
How to host the bot on Heroku or a Free 24/7 bot hoster.

### ISSUE THREAD

**Issue by Icelagy** [eritislami/evobot#202]
While hosting in heroku i get this error
Error waiting for network: Resource temporarily unavailable.
I created the procfile also btw.

**Comment by alide123321** [comment]
for 24/7 I wouldn't use Heroku if you are using it for free I would use repl.it and to keep it up 24/7 follow this article https://dev.to/fizal619/so-you-want-to-make-a-discord-bot-4f0n and for your bot token I would put it in a .env file so people cant access it
