### ISSUE TITLE
Bug: [Warning!] Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#203]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. Play a queue with more songs than the max event listener limit(10)...

**Environment (add if possible)**
* Node.js version: v12.18

**Additional information & screenshots**
```
(node:31424) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection].
Use emitter.setMaxListeners() to increase limit
```
Probably occuring as the play command keeps adding this for each song that is played... https://github.com/eritislami/evobot/blob/93351dd73d9eef23268fa4f770ac00d992164504/include/play.js#L48

**Comment by ParasDeshpande** [comment]
@eritislami Fixed this by adding
```
if (queue.connection._events.disconnect.length < 2) {
      queue.connection.on("disconnect", async () => {
        try {
          if (collector && !collector.ended) await collector.stop();
        } catch (error) {
          console.log(error);
        }
        return await message.client.queue.delete(message.guild.id)
      });
    }
```

**Comment by kasepta** [comment]
still got error log
(node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit

node version :
   "node": ">=12.0.0"

**Comment by ParasDeshpande** [comment]
hmm no you shouldn't.... Where did you add this???

**Comment by ParasDeshpande** [comment]
You need to replace the existing queue.on disconnrct line with this...

**Comment by ParasDeshpande** [comment]
Replace this with what i gave
https://github.com/eritislami/evobot/blob/93351dd73d9eef23268fa4f770ac00d992164504/include/play.js#L48
`                                ⬇️`
```
if (queue.connection._events.disconnect.length < 2) {
      queue.connection.on("disconnect", async () => {
        try {
          if (collector && !collector.ended) await collector.stop();
        } catch (error) {
          console.log(error);
        }
        return await message.client.queue.delete(message.guild.id)
      });
    }
```

**Comment by kasepta** [comment]
i have to add the code, and i still got the error like that.

**Comment by ParasDeshpande** [comment]
might be an error somewhere else.., also this isn't the best solution as "_events" should not be accessed like that... Waiting for erit to find a better solution... But mine one should work fine as a temporary fix for now... It works perfectly for me...
