### ISSUE TITLE
Bug: Error: Cannot find module './config.json' 

### ISSUE THREAD

**Issue by JordivDeijk** [eritislami/evobot#206]
if i type in command prompt 'node .' , it give this error. 
![image](https://user-images.githubusercontent.com/71943389/94348040-8afe7580-0039-11eb-9735-2b5a5d9f1b94.png)
![image](https://user-images.githubusercontent.com/71943389/94348050-9487dd80-0039-11eb-9ece-3aa0c851f615.png)

**Comment by Cy1der** [comment]
"../config.json" u need 2 dots

**Comment by alide123321** [comment]
> "../config.json" u need 2 dots

or if you don't have a config.json file make one in the main directory and put this in it
{
  "TOKEN": "",
  "YOUTUBE_API_KEY": "",
  "SOUNDCLOUD_CLIENT_ID": "",
  "MAX_PLAYLIST_SIZE": 10,
  "PREFIX": "/",
  "PRUNING": false
}

**Comment by TheCuteFoxxy** [comment]
You have to rename `config.json.example` to `config.json`
