### ISSUE TITLE
Help: Disconnect Command

### ISSUE THREAD

**Issue by Xenodirt** [eritislami/evobot#208]
I wanted a disconnect from voice channel command for the bot, so I took reference from other commands.
Here's what I made:
```
const { canModifyQueue } = require("../util/EvobotUtil");

module.exports = {
    name: "disconnect",
    aliases: ["dc"],
    description: "Disconnects the bot from the voice channel.",
    async execute(message) {
        const queue = message.client.queue.get(message.guild.id);
        if (!canModifyQueue(message.member)) return;
        
        queue.channel.leave();
        if (!queue.channel.leave) return;
        return message.reply("I have left the voice channel by your request. Thanks for tuning in!")
    }
}
```
The thing is... it only disconnects when there is music playing. I want it to also disconnect without music (Every time I would try to do that, I get an error). What do I do to get it to disconnect regardless if there is music playing or not and at the same time, erasing the queue?

**Comment by hogan-chung** [comment]
Uh... I think this script are already in the bot...

**Comment by Raphilia** [comment]
The stop command already does this, unless you have modified the code so that the bot stays even when there's no music playing (which I think is a flaw), there's no need for a Disconnect command.

**Comment by Xenodirt** [comment]
> The stop command already does this, unless you have modified the code so that the bot stays even when there's no music playing (which I think is a flaw), there's no need for a Disconnect command.

Yup, that's what I did actually. A disconnect command would still be useful for me in occassions.

**Comment by Xenodirt** [comment]
> The stop command already does this, unless you have modified the code so that the bot stays even when there's no music playing (which I think is a flaw), there's no need for a Disconnect command.

Yup, that's what I did actually. Any idea for a disconnect command with my modified code?

**Comment by Raphilia** [comment]
> > The stop command already does this, unless you have modified the code so that the bot stays even when there's no music playing (which I think is a flaw), there's no need for a Disconnect command.
> 
> Yup, that's what I did actually. Any idea for a disconnect command with my modified code?
`	execute(message) {

		if (!canModifyQueue(message.member)) return;

		const clientVoiceConnection = message.guild.me.voice.channel;
		if (!clientVoiceConnection) return;

		clientVoiceConnection.leave();
		return message.reply("I have left the voice channel by your request. Thanks for tuning in!")
	}`

**Comment by Raphilia** [comment]
This should do the trick
```javascript
		if (!canModifyQueue(message.member)) return;

		const clientVoiceConnection = message.guild.me.voice.channel;
		if (!clientVoiceConnection) return;

		clientVoiceConnection.leave();
		return message.reply("I have left the voice channel by your request. Thanks for tuning in!");
```

**Comment by Xenodirt** [comment]
> This should do the trick
> 
> ```js
> 	execute(client, message) {
> 
> 		if (!canModifyQueue(message.member)) return;
> 
> 		const clientVoiceConnection = message.guild.me.voice.channel;
> 		if (!clientVoiceConnection) return;
> 
> 		clientVoiceConnection.leave();
> 		return message.reply("I have left the voice channel by your request. Thanks for tuning in!");
> 	}
> ```
> 
> Just keep in mind this does not perform checks if a music is still playing (since I don't know to what extent you've modified the code)

I'm getting this error in the log:
`TypeError: Cannot read property 'voice' of undefined`
