### ISSUE TITLE
Bug: Queue is undefined

### ISSUE THREAD

**Issue by Cy1der** [eritislami/evobot#211]
**Describe the bug**
Queue in ../include/play.js is undefined

**How To Reproduce**
Steps to reproduce the behaviour:
1. Define queue just like eritislami did
 
**Expected behavior**
Queue is defined

**Environment (add if possible)**
* Node.js version: 14.9.0

**Comment by ParasDeshpande** [comment]
can you provide some error or give some code in more detail? Or tell what have you modified???
