### ISSUE TITLE
Bug: Error during playback

### ISSUE THREAD

**Issue by bartixen** [eritislami/evobot#232]
**Describe the bug**
`Error during playback`

**Steps to reproduce the behavior:**
1. `!play https://www.youtube.com/watch?v=SXFS1-BEtaQ`
2. `Music queue ended.`
    `Error: No suitable format found`
 
**Expected behavior**
`Music should play`

**Node.js version:** `v12.19.0`

**Additional information & screenshots**

![errordiscord](https://user-images.githubusercontent.com/48735544/95331475-58127800-08aa-11eb-8dab-566bdaff0830.png)

![errornode](https://user-images.githubusercontent.com/48735544/95331501-6365a380-08aa-11eb-9b69-4feef6851255.png)

**Comment by bartixen** [comment]
I tested locally and it works, but it shows this bug on vps from debian, maybe you need to install something more.

**Comment by chino-chan1** [comment]
<img width="432" alt="Screen Shot 2020-10-12 at 11 47 37" src="https://user-images.githubusercontent.com/60313514/95706335-ca0b0880-0c80-11eb-81b2-cfd873e4f0c0.png">
it's working in my bot ._.
