### ISSUE TITLE
Bug: Can't play music using youtu.be youtube url

### ISSUE THREAD

**Issue by wolf-yuan-6115** [eritislami/evobot#235]
I can't play song with `youtu.be` Url

**Comment by eritislami** [comment]
<img width="648" alt="Screen Shot 2020-10-27 at 21 21 58" src="https://user-images.githubusercontent.com/22680785/97357698-7c0a1d80-189a-11eb-92e0-243495bafa13.png">

I believe it's working as intended, if you have any other problem feel free to reply
