### ISSUE TITLE
The bot does not store the 'volume' value for a single guild.

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#24]
The volume of the bot has to be changed everytime when playing another queue... This could be fixed by adding a new map for guild specific volume, also the volume changes are global and not guild specific... So if someone changes the volume on another server it changes that on all servers.

**Comment by eritislami** [comment]
I just tested what you said with 2 servers and the volume is exclusive to each server, the map uses the guild id so i'm not sure how they could be the same, as for the queue yes its correct, every new queue starts with default volume at 100

**Comment by eritislami** [comment]
Going to close this for now, if there is anything else to add feel free to comment
