### ISSUE TITLE
Offers

### ISSUE THREAD

**Issue by ENOT1KK** [eritislami/evobot#243]
Will there be commands for moderation? (Ban (unban), warm (unwarn), kick, mute (unmute))
I would really like to see these functions in the bot

**Comment by ZeskOficial** [comment]
Is a musicbot, if u want add those functions is pretty easy.

**Comment by dylanjames-js** [comment]
^

**Comment by ParasDeshpande** [comment]
I don't think that he'll add those features, coz it's just a music bot currently
