### ISSUE TITLE
Ability to translate Evobot response

### ISSUE THREAD

**Issue by techroy23** [eritislami/evobot#270]
**Is your feature request related to a problem? Please describe.**
Ability to translate Evobot response

**Describe the solution you'd like**
Add a folder/file that contains evobot reponses (eg. LANG/EN.TXT LANG/ES.TXT LANG/FR.TXT)

**Describe alternatives you've considered**
err. not sure if theres alternative

**Additional context**

**Comment by eritislami** [comment]
Not interested in doing this, sorry

**Comment by wolf-yuan-6115** [comment]
> Not interested in doing this, sorry

...
I think you can do this and there will have more people will use EvoBot
