### ISSUE TITLE
Bug: No suitable format found 

### ISSUE THREAD

**Issue by dylanjames-js** [eritislami/evobot#277]
**Describe the bug**
Any time I try to play music from YouTube it produces an error stating the following:

“No suitable format found”

**How To Reproduce**
1. Play any song from YouTube .
 
**Expected behavior**
The song to play. 

**Environment (add if possible)**
* Node.js version: Newest

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

I don’t believe this is a rate limit by YouTube since I haven’t met my API usage quota.

**Comment by dylanjames-js** [comment]
![Uploading 884DE9DC-2F7D-4B01-9141-9812E6FE97C9.jpeg…]()

**Comment by dylanjames-js** [comment]
![1B4F0649-75FA-4282-8589-98C1A592566D](https://user-images.githubusercontent.com/55116398/97295876-43c8f780-1826-11eb-8c52-d9cc078d9cae.jpeg)

**Comment by dylanjames-js** [comment]
I tried searching for the ytdl-core-discord’s repo but it’s nonexistent anymore.

**Comment by djsmithuk** [comment]
Tried it with some music videos of various music studios and all seem to be working as expected, have you got a URL or name so i can test on a fork of the bot?

Also the node package is still live and available - https://npmjs.com/package/ytdl-core-discord

**Comment by eritislami** [comment]
For me this happens when video is blocked in my country

**Comment by dylanjames-js** [comment]
It may have been a VPS issue because when I switched hosting to a new provider for other reasons it fixed it completely-- closing.
