### ISSUE TITLE
Bug: Not playing song

### ISSUE THREAD

**Issue by alide123321** [eritislami/evobot#286]
**Describe the bug**
not playing even if I used the link

**How To Reproduce**
1) .p https://www.youtube.com/watch?v=ZdlrVDwn_a4&ab_channel=Quadeca
2) or .p Quadeca - Insecure (KSI Diss Track) Official Video
 
gives one of these error messages 
```
No video was found with a matching title.

Error: Error parsing info: Cookie header used in request, but unable to find YouTube identity token
```

is it age-restricted and if so how do I bypass that

**Environment (add if possible)**
* Node.js version: V14.14.0

**Comment by yizheng5946** [comment]
we are same

**Comment by DirectX-Luck** [comment]
Well, The thing is, There is no YTDL-CORE-Discord available in Github. Which means the API is not working. We need to find a good method to search and play music.

**Comment by alide123321** [comment]
> Well, The thing is, There is no YTDL-CORE-Discord available in Github. Which means the API is not working. We need to find a good method to search and play music.

It plays music most of the time it’s just certain links it doesn’t

**Comment by DirectX-Luck** [comment]
But not for my bot which was made using ytdl-core-discord. It doesn't play anything, Sadly.

**Comment by ZeskOficial** [comment]
For me is fully working, i used your link and your song
https://i.imgur.com/YESeYWU.png

**Comment by alide123321** [comment]
> For me is fully working, i used your link and your song
> https://i.imgur.com/YESeYWU.png

ill take a look at my code again thank you

**Comment by DirectX-Luck** [comment]
> For me is fully working, i used your link and your song
> https://i.imgur.com/YESeYWU.png

Oops, I sent the wrong link to you guys. Sorry. Check this out : https://www.npmjs.com/package/ytdl-core-discord >> Github Page

**Comment by eritislami** [comment]
It's working for me as well, try fresh clone of the bot if you don't have custom changes
