### ISSUE TITLE
Stopping when i trying to start

### ISSUE THREAD

**Issue by RaufSSen** [eritislami/evobot#29]
No error. Just stoping when i try to play song.

Using Glitch.com
I set node engine to v12.

Help me.

**Comment by VirusLauncher** [comment]
I have realized that some songs does't play, try a popular song and see if it work. This is probably a bug and might have to fix.

**Comment by VirusLauncher** [comment]
@RaufSSen I got it to work now

Install these dependencies:   
 "bufferutil": "^4.0.1",
    "erlpack": "^0.1.3",
    "libsodium": "^0.7.4",
    "sodium": "^3.0.2",
    "utf-8-validate": "^5.0.2",
    "zlib-sync": "^0.1.6",
    "ffmpeg-static": "^4.2.2",
    "node-opus": "^0.3.3"
  },

Then go on this site and install back a little update from the devs. 
https://github.com/tjrgg/simple-youtube-api

Note: I'm new to Node.js but i am learning.

**Comment by Atom-Dragon** [comment]
> I have realized that some songs does't play, try a popular song and see if it work. This is probably a bug and might have to fix.

yes this is an problem with old yt vids commonly like 4 years old or more  , it will work the second time you try to play the song it also happens with other bot like rythm etc :)

**Comment by RaufSSen** [comment]
worked thx!

**Comment by RaufSSen** [comment]
i want to ask something.

**Comment by RaufSSen** [comment]
why bot started when i installed these dependencies?

**Comment by VirusLauncher** [comment]
To be honest, i don't know. From my research, youtube and other sound services have limited support to bots last year.

**Comment by RaufSSen** [comment]
Oh, nevermind. Thanks for help!
