### ISSUE TITLE
Bug with command queue 

### ISSUE THREAD

**Issue by Avadro** [eritislami/evobot#294]
I have this message when i write command q or queue : 
Missing Permissions - [ADD_REACTIONS, MANAGE_MESSAGES]! 

But, the bot have the permission to add reactions and manage messages. 
Thans.

**Comment by eritislami** [comment]
Please test again with this commit 4a066d09ca79056bef6c6ab09f22c69453071e47

**Comment by Avadro** [comment]
When i write /q or /queue, the music is stopped and i have this error message on cmd : 

TypeError: fields.flat is not a function
TypeError: fields.flat is not a function

C:\Users\Administrator\node_modules\opusscript\build\opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFil
abort(TypeError: fields.flat is not a function). Build with -s ASSERTIONS=1 for more info.

**Comment by eritislami** [comment]
> When i write /q or /queue, the music is stopped and i have this error message on cmd :
> 
> TypeError: fields.flat is not a function
> TypeError: fields.flat is not a function

This error happens because your node.js version is lower than 12, to fix install Node.js LTS https://nodejs.org/en/

**Comment by Avadro** [comment]
Perfect, thanks ;)
