### ISSUE TITLE
Change bitrate

### ISSUE THREAD

**Issue by RaufSSen** [eritislami/evobot#30]
Can i change the bitrate. Because bot is lagging.

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/blob/7702b9e70629e4947fac96019d903d9a0cb1d989/include/play.js#L31

You can modify the bitrate here by adding it in the streamOptions object in the play method, here is the documentation
https://discord.js.org/#/docs/main/stable/typedef/StreamOptions
