### ISSUE TITLE
Bug: Error 403

### ISSUE THREAD

**Issue by Icelagy** [eritislami/evobot#302]
I get this error when using "Play" command:

{
  code: 403,
  message: 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.',
  errors: [
    {
      message: 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.',
      domain: 'youtube.quota',
      reason: 'quotaExceeded'
    }
  ]
}

**Comment by L0SER8228** [comment]
Change YouTube api key

**Comment by Icelagy** [comment]
I already changed it, twice.

**Comment by wolf-yuan-6115** [comment]
Try to reinstall module

**Comment by Icelagy** [comment]
How do I reinstall modules.

**Comment by eritislami** [comment]
Not a bug, moving to discussions
