### ISSUE TITLE
make the bot play live streams

### ISSUE THREAD

**Issue by AndroSameh100** [eritislami/evobot#313]
make the bot play live stream like the music live streams its not impossible i test it on other bots like groovy its worked! but when i use it on evobot it give me this error Error: FFmpeg/avconv not found!
so please add this Feature

**Comment by wolf-yuan-6115** [comment]
This feature is already in the bot.
Try to reinstall modules!

**Comment by AndroSameh100** [comment]
oh yes thanks but.. its still give me some issues first and then it work
issue like : Error: Error parsing info: Unable to retrieve video metadata
