### ISSUE TITLE
Bug:Bot randomly stops playing music

### ISSUE THREAD

**Issue by ichaemin** [eritislami/evobot#315]
While playing the song, the bot randomly stops playing.

There is no time limit, sometimes the bot lasts more than 10 hours, sometimes it literally disconnects after an hour.

After the song stops playing, all queues are cleared and stopped.

I'm using Heroku for the host and there are no errors in the logs.

I think it's a websocket related issue, but I'm not sure what to do.

**Comment by wolf-yuan-6115** [comment]
Well, i am using Heroku to host my bot too
But I have never met this error

**Comment by eritislami** [comment]
Are you paying for heroku? bots don't stay online 24/7 for free.

**Comment by ichaemin** [comment]
That was the problem. Thank you.

**Comment by wolf-yuan-6115** [comment]
> Are you paying for heroku? bots don't stay online 24/7 for free.

You don't need to pay money to Heroku to let Discord bot 24/7, just need to add a credit card.

**Comment by ichaemin** [comment]
I already added a credit card.
I updated the config bar in Heroku and I think the problem was solved.

**Comment by ichaemin** [comment]
> > Are you paying for heroku? bots don't stay online 24/7 for free.
> 
> You don't need to pay money to Heroku to let Discord bot 24/7, just need to add a credit card.

Are you using the free dyno?
When I hosted my bot as a free version, heroku cycled it every day, so I had downtime. Do you have no problem?

**Comment by wolf-yuan-6115** [comment]
> > > Are you paying for heroku? bots don't stay online 24/7 for free.
> > 
> > You don't need to pay money to Heroku to let Discord bot 24/7, just need to add a credit card.
> 
> Are you using the free dyno?
> When I hosted my bot as a free version, heroku cycled it every day, so I had downtime. Do you have no problem?
> 
> 

I don't have this problem before ._.

**Comment by ichaemin** [comment]
Hello, thanks to you, my bot is hosted 24/7.
Looking at the time the bot started with the uptime command, it seems that the hosting issue has been resolved.
But I don't know if others are also getting this error, but the song stops playing and the problem comes back.
The last time the problem occurred, the bot turned off and on, the music stopped, then the queue was reset and the music stopped playing.
The problem I encountered this time was that the music stopped playing, but the queue was kept, there was no voice and it was not moving to the next song.
Again, nothing in the log.
It's a bit weird, but after the song has stopped, you have to type the skip command to move on to the next song.
My bot now has no downtime, but this happens nonetheless.

Sorry for my poor english...................
