### ISSUE TITLE
soundcloud  

### ISSUE THREAD

**Issue by thekushharia** [eritislami/evobot#317]
not playing properly soundcloud music

**Comment by wolf-yuan-6115** [comment]
Eww me 2

**Comment by eritislami** [comment]
Cool but it would be helpful if you provided more info & explain what is happening, or used the issue template, I will reopen when more info is available.

**Comment by wolf-yuan-6115** [comment]
> Cool but it would be helpful if you provided more info & explain what is happening, or used the issue template, I will reopen when more info is available.

Hi, @eritislami , you will get http error code `401 (Bad Request)` when you are trying to play Soundcloud music.
