### ISSUE TITLE
Add invite command

### ISSUE THREAD

**Issue by sam920829** [eritislami/evobot#318]

**Comment by wolf-yuan-6115** [comment]
You can get your bot invite by `https://discord.com/oauth2/authorize?client_id=${message.client.user.id}&permissions=8&scope=bot`
~~I think~~

**Comment by dylanjamesdev** [comment]
You can easily do this yourself.

**Comment by eritislami** [comment]
e877e1a6e92bf2dbd98ffcd9f670222c7a43089d
