### ISSUE TITLE
[ Feature Request ] : Add time of the song

### ISSUE THREAD

**Issue by REMOOO** [eritislami/evobot#321]
**Time of the song**
Add time of the song, shown by hours, minutes, seconds.

**Nowplaying**
Edit the bar and time of song, do setInterval to update the message by the new time ( message.edit )

**Volume**
Make the bot save the volume, No need to edit it after queue end.
![Capture](https://user-images.githubusercontent.com/13511097/99140418-a0138000-264a-11eb-9c3a-3579176022b9.PNG)
![Capture2](https://user-images.githubusercontent.com/13511097/99140419-a144ad00-264a-11eb-8480-3218a17a7a6c.PNG)

**Comment by eritislami** [comment]
Already suggested before, not planning to work on this
