### ISSUE TITLE
!!! Unable to retrieve video metadata solution is not working !!!

### ISSUE THREAD

**Issue by wolf-yuan-6115** [eritislami/evobot#325]
@eritislami said we need to edit `package-lock.json`
```json
{
    "Some" : "Other Modules",
    "ytdl-core-discord" : {
        "ytdl-core^3.××"
    }
}
```
To this:
```json
{
    "Some" : "Other Modules",
    "ytdl-core-discord" : {
        "ytdl-core^4.××"
    }
}
```

But this solution is not working because in the `node_modules/ytdl-core-discord/package.json` is still using `ytdl-core^3.××`

We need to content `ytdl-core-discord`'s developer to update `ytdl-core` module in `package.json`, I can't update that cause I am using Heroku to host my bot

Update:
I found another solution, but you can't play soundcloud music anymore.

**Comment by BlazeIsClone** [comment]
yup im getting im getting this same error as well. I clean installed ytdl-core latest version as well.

**Comment by Xenodirt** [comment]
I believe it has something to do with YTDL Core itself after it recently got DMCA'd. There's no known fix to this.

**Comment by wolf-yuan-6115** [comment]
Hi ! @BlazeIsClone & @Xenodirt 
I know how to fix it, I **maybe** will pull a new version.

**Comment by BlazeIsClone** [comment]
> Hi ! @BlazeIsClone & @Xenodirt 
> I know how to fix it, I **maybe** will pull a fixed version.

Hey that would be amazing thank you very mutch and have a great day!

**Comment by wolf-yuan-6115** [comment]
Hi !
@BlazeIsClone and @Xenodirt 
I have submitted a pull request, you can test them now!

**Comment by OGSkies** [comment]
@wolf-yuan-6115 can you send the link so i can fix my bot too
