### ISSUE TITLE
The Bot is not playing any song

### ISSUE THREAD

**Issue by DirectX-Luck** [eritislami/evobot#33]
` errors: [
    {
      domain: 'usageLimits',
      reason: 'accessNotConfigured',
      message: 'Project 1048051177020 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.',
      extendedHelp: 'https://console.developers.google.com/iam-admin/projects?pendingDeletion=true'
    }
  ],
  code: 403,
  message: 'Project 1048051177020 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.'
}
{
  errors: [
    {
      domain: 'usageLimits',
      reason: 'accessNotConfigured',
      message: 'Project 1048051177020 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.',
      extendedHelp: 'https://console.developers.google.com/iam-admin/projects?pendingDeletion=true'
    }
  ],
  code: 403,
  message: 'Project 1048051177020 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.'
}`

This is the error, I found in the console.

**Comment by eritislami** [comment]
The error says the google cloud console project from which you are using the youtube api key has been scheduled for deletion, if you are the owner of the project you can cancel the deletion or create a new one and get a new youtube data api key for the bot.

**Comment by DirectX-Luck** [comment]
Okay thanks. It worked.
