### ISSUE TITLE
Voice connection timeout

### ISSUE THREAD

**Issue by Scraayp** [eritislami/evobot#339]
**Describe the bug**
If i try to play a song i get this error! Could not join the channel: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.

**How To Reproduce**
1. join a voice channel
2. type: <prefix>play 7 years
 
**Expected behavior**
it should join and play the music!

**Environment (add if possible)**
* Node.js version: v12.19.0

**Additional information & screenshots**
No

**Comment by wolf-yuan-6115** [comment]
Not working for me
My bot play 7 years without any errors

**Comment by Scraayp** [comment]
Hmmm. Idk why it happens for me then!

**Comment by Scraayp** [comment]
The full error btw:
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/workspace/evobot/node_modules/discord.js/src/client/voice/VoiceConnection.js:303:26)
    at /workspace/evobot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
    at Timeout.<anonymous> (/workspace/evobot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}

**Comment by eritislami** [comment]
It's related to your/bots internet connection, not a bug

**Comment by Scraayp** [comment]
The internet connection is stable. So, it's not a problem on my internet connection

**Comment by eritislami** [comment]
> The internet connection is stable. So, it's not a problem on my internet connection

Does the bot have the 'view channel' permission for the voice channel trying to connect?

**Comment by Scraayp** [comment]
Yes, i have done some debug. I found out cleaning my npm cache worked out!

**Comment by wolf-yuan-6115** [comment]
> Yes, i have done some debug. I found out cleaning my npm cache worked out!

Eww today I have this error, I will try to redeploy bot files to Heroku...
