### ISSUE TITLE
Bug: Pausing a song doesn't work.

### ISSUE THREAD

**Issue by DM164** [eritislami/evobot#346]
**Describe the bug**
When pausing the bot and unpausing after a specific period of time, the song just skips every few seconds and then the bot stops playing the song almost as if the song never stopped playing and the bot is trying to keep up. (I host the bot on Heroku, on my Linux server it works fine)

**How To Reproduce**
1. Pause the bot
2. Wait a few seconds or minutes
3. Unpause
 
**Expected behavior**
Well... continue to play where I left off.

**Environment (add if possible)**
* Node.js version: latest heroku/node.js buildpack

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by wolf-yuan-6115** [comment]
Well... sometime I have this error too

**Comment by REMOOO** [comment]
i have this problem when lunch bot on vps
