### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by JoxyS** [eritislami/evobot#352]
**Describe the bug**
When I try to play some songs, it gives me the message Video unavailable

**How To Reproduce**
1./play SONG NAME OR SONG URL

**Additional information & screenshots**
https://i.imgur.com/FocIb33.png

**Comment by eritislami** [comment]
Already reported in other issues, it's from ytdl

**Comment by JoxyS** [comment]
but has it been fixed? I tried to see, but the solutions proposed by the community did not work

**Comment by eritislami** [comment]
No i still get this error even with latest package versions
