### ISSUE TITLE
Bug: Volume can be set to out of bounds values.

### ISSUE THREAD

**Issue by evrardco** [eritislami/evobot#364]
**Describe the bug**
When using the volume command to set any volume possible.

**How To Reproduce**

:warning: These steps can produce very loud sounds that can be hurtful for your ears or your speakers. :warning:

1. Have a fully functional bot at disposal.
2. Play any song.
3. Use the command /volume 10e32 for example.
4. Enjoy your bleeding ears.
 
**Expected behavior**

The bot should refuse the command and output the following: 

@username, Please use a number between 0 - 100. 

**Environment (add if possible)**

* Node.js version: node:12.19-slim, the version from the docker image.

**Additional information & screenshots**

The bug can also be reproduced with the following commands, for any number in the same formats.
/volume 0xFFFF
/volume 0b1111111111
/volume 10e20000000
and more, you get it.

The bug is caused by some number formats which can be parsed by the Number() function but not by the parseInt() function which is the one used for the bounds check. I've already fixed it in my  PR #363

**Comment by eritislami** [comment]
Merged
