### ISSUE TITLE
(node:4032) UnhandledPromiseRejectionWarning: TypeError: scdl.isValidUrl is not a functionBug: 

### ISSUE THREAD

**Issue by Himo313** [eritislami/evobot#370]
(node:4032) UnhandledPromiseRejectionWarning: TypeError: scdl.isValidUrl is not a function
when i try to play a song

**Comment by miatoszs** [comment]
I also have this problem

**Comment by zLuisOne** [comment]
Same problem happened to me, but I solved it just by removing "***scdl.isValidUrl (url)***"

**Comment by Himo313** [comment]
> Same problem happened to me, but I solved it just by removing "_**scdl.isValidUrl (url)**_"

where can i find scdl.isVaildUrl

**Comment by miatoszs** [comment]
/commands/play.js 
 } else if (scdl.isValidUrl(url) && url.includes("/sets/")) {
} else if (url.includes("/sets/")) {

**Comment by eritislami** [comment]
Going to revert scdl package to working version

**Comment by miatoszs** [comment]
how can i do that

**Comment by eritislami** [comment]
> how can i do that?

Git pull, delete node_modules, npm install

**Comment by miatoszs** [comment]
thx
