### ISSUE TITLE
Bug: message.guild.member is not a function

### ISSUE THREAD

**Issue by haruzinh0** [eritislami/evobot#373]
**Describe the bug**
Uncaught Promise Error: 
[2020-11-26 18:49:40] TypeError: message.guild.member is not a function

**How To Reproduce**
try to use use reactions in the embed, like, play, volume, skip etc
1.
2.
 
**Expected behavior**
it works, but its not working.

**Environment (add if possible)**
* Node.js version: v14.15.1

**Comment by eritislami** [comment]
Can't reprocude, working fine for me, can you post full error with the stack trace ?

**Comment by haruzinh0** [comment]
eris, the Guild#member was removed it on latest discord.js version. i fixed it to latest version. :)

**Comment by haruzinh0** [comment]
include/play.js > change const member = message.guild.members(user); 
to 
const member = message.guild.members.cache.get(user.id);

cheers.

**Comment by eritislami** [comment]
It's there in 12.5.1 which is used in the bot
https://discord.js.org/#/docs/main/12.5.1/class/Guild?scrollTo=member
