### ISSUE TITLE
 Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by mega-xsam** [eritislami/evobot#382]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by mega-xsam** [comment]
Error parsing info: Unable to retrieve video metadata

**Comment by mega-xsam** [comment]
Error parsing info: Unable to retrieve video metadata

**Comment by eritislami** [comment]
Check existing issues
