### ISSUE TITLE
Question: Playlocal command (with the intention of playing sound in mp3 format from a local directory.)

### ISSUE THREAD

**Issue by Gruala** [eritislami/evobot#398]
**Describe the solution you'd like**
A description of what you want to happen.

I don't know if that's already active, but if it wasn't:
Could you create a "called playlocal" command to play sound in MP3 format?
a variable will be to have: "PathLocalAudio" example: "./audio" where you could put MP3 music.

Could that command be integrated?

This is the best music bots of all I've ever tried. But I'd get better if I could have this command.

Thanks for everything. Greetings.

**Comment by Gruala** [comment]
Example:

/playlocal music.mp3

**Comment by eritislami** [comment]
Thanks for the suggestion, I can add this soon.

**Comment by Gruala** [comment]
I've tried a lot of music sound players.
This is the best I've ever used. I want to congratulate you on your work. Many codes after days have errors or failures in youTube dll calls, or connection errors. This code is pretty stable.

Thank you very much for this contribution.

**Comment by eritislami** [comment]
Commit 1ce79e8fc63e78424ff84ae00934dcb63e64d4f2

Put your music in sounds folder and play music with /clip song.mp3

**Comment by Gruala** [comment]
Hello.
Two hours after uploading the command I tried to check, but I have the following problem:
**Error: Error parsing info: Unable to retrieve video metadata**

Looks like the same thing's happening to a lot of people. As soon as I can, I'll tell you what. But it sure works very well.
Thz.
