### ISSUE TITLE
Standard Volume

### ISSUE THREAD

**Issue by Molthor** [eritislami/evobot#399]
So the bot is working realy well, Good work. 
But is there a way to set the volume to 10% as Standard, instead of having to do it everytime we play something.

**Comment by evrardco** [comment]
Actually that would be a good idea I'm gonna look into it, hopefully the maintainer agrees with us :p

**Comment by evrardco** [comment]
I just did it. I added a key DEFAULT_VOLUME in the config.json file. Like the other config keys, it can also be set with the environment variable of the same name.

I tested it with a few commands and it seems to work with no bug from what I can see.

**Comment by Molthor** [comment]
Sweet  !! will test it out tomorrow too. and will give a feedback. thank you!
