### ISSUE TITLE
Bug: Not work music for YouTube

### ISSUE THREAD

**Issue by RyzenK8** [eritislami/evobot#402]
**Describe the bug**
Can't make music work

**How To Reproduce**
1. Start node index.js
2. Make $play youtube.com/exemple
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 15
* Update all pack.json

**Additional information & screenshots**
![IMG_20201130_083215](https://user-images.githubusercontent.com/34812693/100580640-9b0b2d80-32e6-11eb-8282-ecb531e50de7.jpg)

**Comment by Pedro9700** [comment]
Can confirm, this happens to me aswell, no idea whats causing the issue.
Nodejs ver -12.17.0
npm ver -6.14.4
ubuntu 20.04
If anyone has a fix for the problem, I would appreciate :)

**Comment by DynamoYT** [comment]
@RyzenK8 Try
```
npm uninstall ytdl-core
npm install ytdl-core@4.0.3
```

**Comment by Pedro9700** [comment]
![image](https://user-images.githubusercontent.com/29014242/100626032-2ef7ec00-331d-11eb-9231-77f7561727bd.png)
I tried to use 4.0.3 but still got the same error.
I´m not sure, but could be due to ytdl-core-discord conflict?

**Comment by AstethicDeath** [comment]
![image](https://user-images.githubusercontent.com/47943804/100635872-b7848580-3339-11eb-972e-2ea4050af329.png)

**Comment by canopus310** [comment]
i did a bit of searching and the error is caused by ytdl-core-discord because it isnt currently up to date

**Comment by totolerigolo324** [comment]
> J'ai fait un peu de recherche et l'erreur est causée par ytdl-core-discord car il n'est pas actuellement à jour

So we just have to wait, right? cool!...

**Comment by eritislami** [comment]
No way to fix this, some videos are just blocked
