### ISSUE TITLE
Bug: Error: could not find player config

### ISSUE THREAD

**Issue by Crncodesallsortsofthings** [eritislami/evobot#410]
**Describe the bug**
error message saying could not find player config
**How To Reproduce**
was working for ages, then one day this happens
 
**Expected behavior**
it to work like it is meant to, play the song that I requested 

**Environment (add if possible)**
* Node.js version: 12.0.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Are you using latest updated package and package lock?
