### ISSUE TITLE
Suggestion: command cooldown

### ISSUE THREAD

**Issue by evrardco** [eritislami/evobot#416]
When people disagree on a song choice, they often spam command to play, stop, etc different songs. I suggest, as the name implies that a configurable cooldown is added.

The way I see it is the following:
Say the cooldown is set on X seconds, when someone sends a command accepted by the bot, the bot then refuses any  command during the next X seconds.

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/blob/8a10821725c741bd580c4371492e6fc6d0d8a7d9/commands/playlist.js#L10

There is already, you can add this line just line in other commands or increase the cooldown as much as you want for each command

**Comment by evrardco** [comment]
Oh ok, I didn't notice it, sorry for wasting your time :innocent:
