### ISSUE TITLE
Bug:  Can't retrive video meta data

### ISSUE THREAD

**Issue by instax-dutta** [eritislami/evobot#418]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by omgdoge** [comment]
i got too

**Comment by eritislami** [comment]
It's from ytdl when it can't get info about the video, nothing can be done about it
