### ISSUE TITLE
Livestream Support

### ISSUE THREAD

**Issue by alhassanv** [eritislami/evobot#42]
Hello,
I was trying to play a livestream and I got this error
<code>
(node:11344) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (C:\Users\alhas\Desktop\evobot-master\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (C:\Users\alhas\Desktop\evobot-master\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (C:\Users\alhas\Desktop\evobot-master\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at C:\Users\alhas\Desktop\evobot-master\node_modules\ytdl-core-discord\index.js:35:24
    at C:\Users\alhas\Desktop\evobot-master\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:289:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code>

**Comment by eritislami** [comment]
Run `npm install ffmpeg-static` and try again

**Comment by Vanawy** [comment]
I also try to play livestream, and bot just playing few seconds and stop playing without any errors in logs and messages in discord

**Comment by alhassanv** [comment]
Nothing gets played and after a few seconds I get
<code>Could not join voice channel: Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.</code>

**Comment by alhassanv** [comment]
Wow its working

**Comment by Vanawy** [comment]
I have issue-related question 

> Run npm install ffmpeg-static and try again, although i never tested playing a livestream not sure if this will work in the current version

Why is ffmpeg-static not in dependencies?

**Comment by eritislami** [comment]
> Why is ffmpeg-static not in dependencies?

Readme from [ytdl-core-discord](https://github.com/amishshah/ytdl-core-discord)

For compatible videos, this module uses prism-media to extract Opus audio from a stream without having to pipe it through FFmpeg first. This greatly reduces the processing power required, making playback smoother and allowing you to play over more connections simultaneously.

For videos where the required codec (webm + opus) isn't available, the module will fallback to using FFmpeg to encode the stream in Opus. Many new videos on YouTube are available in this codec so hopefully this isn't frequent.

Most of the time ffmpeg is not required but can be installed from an [official build](https://ffmpeg.org/download.html) or by package manager. I guess it would be wise to add a note to the readme for anyone that is encountering this same error

**Comment by Vanawy** [comment]
> Most of the time ffmpeg is not required but can be installed from an [official build](https://ffmpeg.org/download.html) or by package manager. I guess it would be wise to add a note to the readme for anyone that is encountering this same error

I think it should be in readme just like #27

**Comment by ParasDeshpande** [comment]
It works but the livestream audio lags. Is there any way to fix this?

**Comment by NullPointDev** [comment]
> It works but the livestream audio lags. Is there any way to fix this?
@ParasDeshpande 

There is inevitably going to be lag, referring to the [ytdl-core-discord](https://github.com/amishshah/ytdl-core-discord) readme,

> For compatible videos, this module uses prism-media to extract Opus audio from a stream without having to pipe it through FFmpeg first. This greatly reduces the processing power required, making playback smoother and allowing you to play over more connections simultaneously.

Which (implicitly) says that ffmpeg takes more processing power to handle. Sometimes, it is what it is.
