### ISSUE TITLE
Bug: [YTDL]: Youtube search is failing.

### ISSUE THREAD

**Issue by evrardco** [eritislami/evobot#426]
When using the play command to search song on youtube, the bot outputs the following error:
Error: Error parsing info: Unable to retrieve video metadata

1. Boot the most recent bot version
2. /play levan polka
 
**Expected behavior**
Levan polka starts playing, hopefully your cat starts vibing as well.

**Environment (add if possible)**
* Node.js version: v14.15.1
* ytdl-core: v4.1.2

I believe the bug is due to some recent change in the youtube API or most possibly to some legal drama that happened today: https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

**Comment by eritislami** [comment]
![image](https://user-images.githubusercontent.com/22680785/101094306-7a7bf580-35bc-11eb-8cf6-3c604e889419.png)

There are about 100 issues for video metadata, there's nothing I can do about it, in the future im just gonna delete issues about ytdl, I have no control over it, also the video could be blocked or some kind of region restriction whatever
