### ISSUE TITLE
filters 

### ISSUE THREAD

**Issue by instax-dutta** [eritislami/evobot#435]
Can You Add Filters Like Bassboost , 8d Audio , Trebble etc ?

**Comment by eritislami** [comment]
Not possible right now

**Comment by instax-dutta** [comment]
Please try to add take your owntime

**Comment by wolf-yuan-6115** [comment]
> Not possible right now

But this is possible in npm package `discord-player`

**Comment by instax-dutta** [comment]
Ok, no problem.
