### ISSUE TITLE
Is it possible to automatically set the bot volume according to the music...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#44]
Is it possible to automatically set the bot volume according to the music (like spotify does), so that if the music volume is too loud the bot can automatically set it to a lower volume, so that peoples' ears dont blow up when you start the queue... Ofc, this is not that required but it can be a good feature to add to the bot.

**Comment by eritislami** [comment]
There is a way to set volume using dB (Decibel units) but i think it would make the usage more complicated for everyone
