### ISSUE TITLE
Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by totolerigolo324** [eritislami/evobot#443]
This is a **ytdl-core-discord** issue, 

1. Go to your node_modules folder and remove ytdl-core-discord folder 
2. Go to you package-lock.json and in that under ytdl-core-discord change the ytdl-core to the latest version.
(check for the latest version here [node-ytdl-core](https://github.com/fent/node-ytdl-core/releases))

Should look like this:
![image](https://user-images.githubusercontent.com/64116737/101198951-3bb47100-368a-11eb-960f-80256f29fb5f.png)

4. Then `npm rebuild`

_Originally posted by @BlazeIsClone in https://github.com/eritislami/evobot/discussions/389#discussioncomment-147429_

**Comment by totolerigolo324** [comment]
For those who have the problem @eritislami ;D

**Comment by eritislami** [comment]
I made a fork of ytdl-core-discord [here](https://github.com/eritislami/erit-ytdl), now using latest ytdl. If original author makes it public/updates it again we can always switch back.
