### ISSUE TITLE
Bug: Error parsing info: Unable to retrieve video metadata in playlist.js

### ISSUE THREAD

**Issue by SuperEric1** [eritislami/evobot#447]
Playlist command error: Error parsing info: Unable to retrieve video metadata.

**Comment by BlazeDexX** [comment]
this is problem from ytdl-core-discord, change the module to erit-ytdl

**Comment by REMOOO** [comment]
> this is problem from ytdl-core-discord, change the module to erit-ytdl

**I lunch the bot on RPD but when i play a song it gives me this error**

![problem](https://user-images.githubusercontent.com/13511097/101313225-69521380-385e-11eb-99b6-7f48f20fccb0.PNG)

**Comment by BlazeDexX** [comment]
> > this is problem from ytdl-core-discord, change the module to erit-ytdl
> 
> **I lunch the bot on RPD but when i play a song it gives me this error**
> 
> ![problem](https://user-images.githubusercontent.com/13511097/101313225-69521380-385e-11eb-99b6-7f48f20fccb0.PNG)

upgrade ytdl-core and change module ytdl-core-discord to erit-ytdl fix my problem

**Comment by eritislami** [comment]
Sometimes ytdl just won't be able to retreive the video, just make sure to be using the latest package and package-lock from the repo.
