### ISSUE TITLE
Clip playlist

### ISSUE THREAD

**Issue by Gruala** [eritislami/evobot#448]
First of all, thank you for solving @evrardco with the library problem 'ytdl-core-discord'
Thanks to him and all the active developers, **mainly** @eritislami, **for his project** and for sharing his work with everyone.

I finally tried the command:
/clip 'plays mp3 files'
An example for playing an mp3 file (putmusichere.mp3) in the folder: /sound:
/clip putmusichere

The command works perfectly. I am very happy. Everything's perfect. Other bots don't do this. Congratulations.

_Question for the future:_
**Could you include a playlist for the clips command in the future?** I don't know if you'd need the js command called cliplist.js for this purpose.
**Could you include pause/play/next/stop... buttons for command clips in the future... who have the youtube lists?**
![image](https://user-images.githubusercontent.com/46764078/101247205-62b98400-3718-11eb-8724-27a92274a3c6.png)
 
Thank you and very good work may or may not integrate those options

**Comment by evrardco** [comment]
@Gruala Although I've been active for other parts of this project lately, I can't take credits for solving the library problem 'ytdl-core-discord', I think it is @eritislami  who solved it :)

**Comment by Gruala** [comment]
Those who understand programming see it clearly. You use a DLL created by him. 
"erit-ytdl": "^0.1.2"
I've seen her again. I don't know if it was in this project at first. But it's to be appreciated for your great contribution. But I also wanted to highlight the contributions of other users like you. Thanks for that.

**The most honest thing would be to thank you for everything** @eritislami, (there is a lot of work behind all this) after using other Bot codes... I keep saying it's the most stable of them all. I was surprised by that from day one. That denotes fine programming. A good programmer.

**Comment by mihawkman** [comment]
@evrardco how do you fix the ytld core discord problem?

**Comment by BlazeIsClone** [comment]
> @evrardco how do you fix the ytld core discord problem?
This has already been fix thanks to @eritislami,

Please use this fork, this should solve the issue with ytdl-core-discord [here](https://github.com/eritislami/erit-ytdl)
