### ISSUE TITLE
Bug: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by REMOOO** [eritislami/evobot#463]
**I lunch the bot on RPD but when i play a song it gives me this error**

![problem](https://user-images.githubusercontent.com/13511097/101313740-8b986100-385f-11eb-91b0-401199047580.PNG)

**Comment by lambor590** [comment]
Update package.json

**Comment by lambor590** [comment]
So use erit-ytdl

**Comment by REMOOO** [comment]
> So use erit-ytdl

how to use explain please

**Comment by eritislami** [comment]
Clone the repo, npm install, its already changed to use other package

**Comment by eritislami** [comment]
Sometimes ytdl just won't be able to retreive the video, just make sure to be using the latest package and package-lock from the repo. There isnt anything to do about it.
