### ISSUE TITLE
Bug: Can't play music.

### ISSUE THREAD

**Issue by 360Noob** [eritislami/evobot#476]
Describe the bug
A description of what the bug is.
Bot joins the voice channel for about 3-4 seconds, then leaves, leaving me the message "Error: Error parsing info: Unable to retrieve video metadata"
How To Reproduce

Using the "play" command.
Expected behavior
A description of what you expected to happen.
I'd expect that my bot would play the music i gave him to
Environment (add if possible)

Node.js version: 12.14.1
Additional information & screenshots
Add any other context or screenshots about the problem here.
![Screenshot 2020-12-09 181359](https://user-images.githubusercontent.com/48653977/101656664-a29ba680-3a4b-11eb-89de-6f79c718160c.png)

Already tried to uninstall the ytdl-core-discord package, didnt work tho

**Comment by eritislami** [comment]
- Try using the package and package-lock from latest commit
- If not sometimes ytdl can't get info about the video, it's not a bug and nothing can be done to change that.

**Comment by 360Noob** [comment]
> * Try using the package and package-lock from latest commit
> * If not sometimes ytdl can't get info about the video, it's not a bug and nothing can be done to change that.

how can i get those? did you update them??

**Comment by eritislami** [comment]
- Delete node_modules,
- git pull,
- npm install
