### ISSUE TITLE
Bug: playlist embed over 2048 length

### ISSUE THREAD

**Issue by totolerigolo324** [eritislami/evobot#486]
**Describe the bug**
When we order the playlist with long playlist, the program gives us an error because the embed is more than 2048 in length.

**How To Reproduce**
1. Start a playlist with around 50+ songs

we see that the program works because the musics are added to the queue but no confirmation message from the bot

**Expected behavior**
If the embed of a playlist is more than 2048 in length we receive a message that says there are too many characters --> https://github.com/eritislami/evobot/blob/b0f431ab340099356b1642e4d9f23586df96b618/commands/playlist.js#L97 but the condition does not work and the error appears.

**Environment (add if possible)**
* Node.js version: 15.4.0
* discord.js: 12.5.1

**Additional information & screenshots**
Here is the error : 
`DiscordAPIError: Invalid Form Body
embed.description: Must be 2048 or fewer in length.
    at RequestHandler.execute (/home/ubuntu/bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async RequestHandler.push (/home/ubuntu/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/750463534835433632/messages',
  code: 50035,
  httpStatus: 400
}`

**Comment by eritislami** [comment]
This doesn't happen for me, did you make code changes?

**Comment by totolerigolo324** [comment]
no, I haven't changed anything on this line

**Comment by wolf-yuan-6115** [comment]
> no, I haven't changed anything on this line
> ![Capture](https://user-images.githubusercontent.com/53100486/102014481-84d58680-3d56-11eb-96b1-2523ba7b8893.PNG)
> 

Set pruning to `true`
