### ISSUE TITLE
Bug: playlist title has html escaped characters

### ISSUE THREAD

**Issue by William5553** [eritislami/evobot#489]
**Describe the bug**
If a playlist title has an apostrophe in it, it will show up as `&#39;`

**How To Reproduce**
1. run the playlist command on any playlist that has an apostrophe in the title
 
**Expected behavior**
an apostrophe appears

**Environment (add if possible)**
* Node.js version: 12.0

**Additional information & screenshots**
This can be fixed by replacing https://github.com/eritislami/evobot/blob/b0f431ab340099356b1642e4d9f23586df96b618/commands/playlist.js#L91 with ``.setTitle(playlist.title.replace(/&#(\d+);/g, (match, dec) => {
    return String.fromCharCode(dec);
  }))``

**Comment by wolf-yuan-6115** [comment]
I didn't got this erroron playlist command , but I got this error on search command
Weird
