### ISSUE TITLE
Suggestions, can modify queue

### ISSUE THREAD

**Issue by L0SER8228** [eritislami/evobot#512]
Upgrade the util code, canModifyQueue. If a user cannot modify the queue it sends a message to the author. But if the user blocked dm it just return, don't send any message.

Make it so that it try to send message to the author first if can't then it should send the message to the message.chhanel

**Comment by nickdevnl** [comment]
That will cause the channel spammed with unneeded messages.

**Comment by L0SER8228** [comment]
I'm telling that, if the user blocked dm, then the bot will send the message to the channel. At first it will try to dm the user. And we can set automatic delete the message after a time, so no spamming

**Comment by nickdevnl** [comment]
Still a useless suggestion tho.
He still cant modify the queue even if he has the bot blocked.
This is unneeded.

**Comment by nickdevnl** [comment]
@eritislami you can close this if you want to.
