### ISSUE TITLE
Bug: Nowplaying command does not say that a livestream as LIVE. 

### ISSUE THREAD

**Issue by NikosProGamer** [eritislami/evobot#515]
**Describe the bug**
Now playing command does not say LIVE if you play a livestream.

**How To Reproduce**
1. Play a livestream.
2. Now run the nowplaying command. It just shows the livestream name and not the LIVE.
 
**Expected behavior**
I expected  to show the stream name then below the LIVE which replaces the length bar of normal tracks/videos.

**Environment (add if possible)**
* Node.js version: Latest LTS

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://user-images.githubusercontent.com/53112175/103148562-bcd2c580-4769-11eb-93cf-2c212c2371d7.png)

**Comment by eritislami** [comment]
I dont support anything about livestreams, if it works it works, it's not a livestream bot.

**Comment by wolf-yuan-6115** [comment]
> **Describe the bug**
> Now playing command does not say LIVE if you play a livestream.
> 
> **How To Reproduce**
> Steps to reproduce the behavior:
> 1. Play a livestream.
> 2. Now run the nowplaying command. It just shows the livestream name and not the LIVE.
>  
> **Expected behavior**
> I expected  to show the stream name then below the LIVE which replaces the length bar of normal tracks/videos.
> 
> **Environment (add if possible)**
> * Node.js version: Latest LTS
> 
> **Additional information & screenshots**
> Add any other context or screenshots about the problem here.
> ![image](https://user-images.githubusercontent.com/53112175/103148562-bcd2c580-4769-11eb-93cf-2c212c2371d7.png)
> 

I don't have this issue, please try another stream.
