### ISSUE TITLE
Bug: undefined properties of 'url' when no url specified in the first place.

### ISSUE THREAD

**Issue by djsmithuk** [eritislami/evobot#520]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. have multiple versions of the bot running in different servers listening to music
2. eventually when searching for songs you get an error relating to undefined url.
 
**Expected behavior**
Play.js detects no url present and searches like normal.

**Environment (add if possible)**
* Heruko-20

**Additional information & screenshots**

![image](https://user-images.githubusercontent.com/33575896/103219555-f2b4ad00-4915-11eb-92f2-dca365be53dd.png)

 Dec 28 13:50:13Z app/worker.1 (node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit
Dec 28 13:50:13Z  app/worker.1 (Use `node --trace-warnings ...` to show where the warning was created)
Dec 28 14:01:23Z  app/worker.1 TypeError: Cannot read property 'url' of undefined
Dec 28 14:01:23Z  app/worker.1     at Object.execute (/app/commands/play.js:104:50)
Dec 28 14:01:23Z  app/worker.1     at runMicrotasks (<anonymous>)
Dec 28 14:01:23Z  app/worker.1     at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by wolf-yuan-6115** [comment]
No, I don't have this bug.
