### ISSUE TITLE
Bug: Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by Peppuss** [eritislami/evobot#527]
![botyt](https://user-images.githubusercontent.com/64472824/103770672-b1638200-5026-11eb-83ec-e5ef66f96239.PNG)
 When i styart one song the bot say this, pls help meeee

**Comment by PasinduDushan** [comment]
Have you put the correct youtube-api key?

**Comment by dnnzz** [comment]
I have that too API key is correct. This bug about ytdl-core's version i think it needs to updated to 4.4.1 version of ytdl core

**Comment by DirectX-Luck** [comment]
Hello, I just got this bug and replaced a new API key. But, The bug is still appearing. Also I updated ytdl-core

**Comment by totolerigolo324** [comment]
> Bonjour, je viens de recevoir ce bogue et j'ai remplacé une nouvelle clé API. Mais, le bogue apparaît toujours. J'ai également mis à jour ytdl-core

To solve the problem use the eritislami API which is called `erit-ytdl` instead of `ytdl-core-discord`.

**Comment by dnnzz** [comment]
> > Bonjour, je viens de recevoir ce bogue et j'ai remplacé une nouvelle clé API. Mais, le bogue apparaît toujours. J'ai également mis à jour ytdl-core
> 
> To solve the problem use the eritislami API which is called `erit-ytdl` instead of `ytdl-core-discord`.

Exact solution thanks a lot !

**Comment by wolf-yuan-6115** [comment]
@eritislami Pls close this
