### ISSUE TITLE
Search & Select videos

### ISSUE THREAD

**Issue by inxec** [eritislami/evobot#54]
**Is your feature request related to a problem? Please describe.**
Not really, but yknow, theres some music that has bass boosted version, reaction of the music video etc. Sometimes the bot plays the different music than what you want

**Describe the solution you'd like**
It would be cool if you will add a selection feature / embed. What this does is, when you type "!play NCS Warrior", there would be an embed that would show up and 5 different NCS Warrior music (This could be a bass boosted etc), then in that embed, there would be 5 reactions (from 1 to 5), and if you react with the number 2 (couñf be anything from 1-5) emoji, the bot will play the music that is in the 2nd choices

Hope you make this happen 😀

**Comment by ParasDeshpande** [comment]
@eritislami You should add a search command for that... So that you can search youtube and select a result from that..

**Comment by inxec** [comment]
@eritislami Yeah, thats what im talking about

**Comment by eritislami** [comment]
Thanks for the suggestion, will consider working on this once some other issues are handled

**Comment by eritislami** [comment]
Added search and select in c92fe53c4375339c65f4fc953b3e6f1bc0e08f7c
To select a song you reply with the song # that comes before the name
