### ISSUE TITLE
Mongo db

### ISSUE THREAD

**Issue by V1rtuaI** [eritislami/evobot#543]
Possibly add support for mongo db? So that users can store the queues in a schema rather than through a Set().

**Comment by henry-bao** [comment]
Sorry again for commenting on a closed discussion. 
@V1rtuaI I am actually currently working on implementing saved-queues by using MongoDB. If you are interested, hit me up on discord `Hackel#1337` 😄

**Comment by V1rtuaI** [comment]
Added aha Ethan#7000
