### ISSUE TITLE
Bug: new remove command not working

### ISSUE THREAD

**Issue by NikosProGamer** [eritislami/evobot#547]
**Describe the bug**
I added the new remove command code from the latest commit for that command and i cant remove a song from the queue. For example, i have 3 songs in the queue and i try !remove 3. It thinks im not giving a queue number and throws me the usage message. I can do !remove 2 but, after it gets removed, i try to remove at that time the new 2nd song in queue and it throws again the usage message.

**How To Reproduce**
1. Put atleast 3-4 songs in the queue
2. Do !remove 3, it doesnt remove anything and throws the usage message.
3. Now, try !remove 2. It removes the 2nd song from the queue as expected. Try running the same command now. It won't work and will throw the usage message once again.
 
**Expected behavior**
To remove the provided song in the queue.

**Environment (add if possible)**
* Node.js version: 12, Windows 10

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/53112175/104330384-9a290680-54f6-11eb-859c-ca3f0f1344f4.png)

**Comment by eritislami** [comment]
Should be ok now
