### ISSUE TITLE
DJ/Voting for music control

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#55]
**Describe the bug**
Anyone can stop or make changes to the music queue without being in the same voice channel as the bot.

**How To Reproduce**
1.Play some music in a voice channel.
2.Use another account which is not connected to any voice channel or is in a different voice channel to type !stop | !pause or other commands.
 
**Expected behavior**
The bot should reply with a message that, the bot is already being used in a different voice channel or you need to be listening to the same voice channel as the bot to use the playlist controls.

**Environment (add if possible)**
* Node.js version: 12.x

**Comment by eritislami** [comment]
Thanks for your suggestion but this isnt a bug, next time please use the feature request template, i believe what you are requesting is a 'dj' role or voting for controlling the bot

I will keep this open but i can't say when i will work on this at the moment

**Comment by ParasDeshpande** [comment]
@eritislami No it is a bug as anyone even outside the voice channel can control th music queue, the bot doesent check if the user requesting the command is in the same channel as the bot or not...

**Comment by ParasDeshpande** [comment]
@eritislami Well yes i suggested the queue controls with voting system in another issue(which you closed) which was an enhancement... But this was a easy fix, you just have to check if the user is in the same voice channel as the bot or not... Both are two different things...

**Comment by eritislami** [comment]
9700cff0bd0350077c5c4106d00bbbefc2ffe895
