### ISSUE TITLE
please add filters 

### ISSUE THREAD

**Issue by instax-dutta** [eritislami/evobot#554]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by wolf-yuan-6115** [comment]
You need to use `discord-ytdl-core` to use this feature, but evobot is using `ytdl-core-discord`, it's two different packages.
