### ISSUE TITLE
update.sh

### ISSUE THREAD

**Issue by techroy23** [eritislami/evobot#557]
# see https://github.com/eritislami/evobot/pull/556

you can add this script to your rc.local or to your cronjob.
this will make sure you always have the latest commit.

**Comment by ccsdscs** [comment]
Hi

**Comment by ccsdscs** [comment]
archive/tar, const FormatGNU = 8 pkg archive/tar, const FormatGNU Format pkg archive/tar, const FormatPAX = 4 pkg archive/tar, const FormatPAX Format pkg archive/tar, const FormatUSTAR = 2 pkg archive/tar, const FormatUSTAR Format pkg archive/tar, const FormatUnknown = 0 pkg archive/tar, const FormatUnknown Format pkg archive/tar, method (Format) String() string pkg archive/tar, type Format int pkg archive/tar, type Header struct, Format Format pkg archive/tar, type Header struct, PAXRecords map[string]string pkg archive/zip, method (*Writer) SetComment(string) error pkg archive/zip, type FileHeader struct, Modified time.Time pkg archive/zip, type FileHeader struct, NonUTF8 bool pkg bufio, method (*Reader) Size() int pkg bufio, method (*Writer) Size() int pkg crypto/tls, const ECDSAWithSHA1 = 515 pkg crypto/tls, const ECDSAWithSHA1 SignatureScheme pkg crypto/x509, const CANotAuthorizedForExtKeyUsage = 9 pkg crypto/x509, const CANotAuthorizedForExtKeyUsage InvalidReason pkg crypto/x509, const ExtKeyUsageMicrosoftCommercialCodeSigning = 12 pkg crypto/x509, const ExtKeyUsageMicrosoftCommercialCodeSigning ExtKeyUsage pkg crypto/x509, const ExtKeyUsageMicrosoftKernelCodeSigning = 13 pkg crypto/x509, const ExtKeyUsageMicrosoftKernelCodeSigning ExtKeyUsage pkg crypto/x509, const NameConstraintsWithoutSANs = 6 pkg crypto/x509, const NameConstraintsWithoutSANs InvalidReason pkg crypto/x509, const TooManyConstraints = 8 pkg crypto/x509, const TooManyConstraints InvalidReason pkg crypto/x509, const UnconstrainedName = 7 pkg crypto/x509, const UnconstrainedName InvalidReason pkg crypto/x509, func MarshalPKCS1PublicKey(*rsa.PublicKey) []uint8 pkg crypto/x509, func MarshalPKCS8PrivateKey(interface{}) ([]uint8, error) pkg crypto/x509, func ParsePKCS1PublicKey([]uint8) (*rsa.PublicKey, error) pkg crypto/x509, method (PublicKeyAlgorithm) String() string pkg crypto/x509, type Certificate struct, ExcludedEmailAddresses []string pkg crypto/x509, type Certificate struct, ExcludedIPRanges []*net.IPNet pkg crypto/x509, type Certificate struct, ExcludedURIDomains []string pkg crypto/x509, type Certificate struct, PermittedEmailAddresses []string pkg crypto/x509, type Certificate struct, PermittedIPRanges []*net.IPNet pkg crypto/x509, type Certificate struct, PermittedURIDomains []string pkg crypto/x509, type Certificate struct, URIs []*url.URL pkg crypto/x509, type CertificateInvalidError struct, Detail string pkg crypto/x509, type CertificateRequest struct
