### ISSUE TITLE
Bot playlist controls can be improved...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#56]
**Is your feature request related to a problem? Please describe.**
Anyone can stop the music instead of the voting system like other bots have. Ex. I'm always frustrated when someone skips the song without asking anyone in the voice channel...

**Describe the solution you'd like**
I would like a simillar voting system like other bots have (add react to vote feature if you want instead of commands)

**Comment by eritislami** [comment]
Closing as duplicate of #55
