### ISSUE TITLE
TTS command 

### ISSUE THREAD

**Issue by SonMaxime** [eritislami/evobot#568]
Here's a cool feature (i think lol). Text-to-speach command !
How it works ? Simply : .tts <args>

Image to explain how we can create the command:
![image](https://user-images.githubusercontent.com/47661880/105007672-8fabc700-5a38-11eb-888b-02ee2c4c9e3c.png)

**Comment by wolf-yuan-6115** [comment]
I don't think this is a required feature for music bot

**Comment by SonMaxime** [comment]
> I don't think this is a required feature for music bot

yeah but it can be cool
