### ISSUE TITLE
Skipto (song queue #)

### ISSUE THREAD

**Issue by inxec** [eritislami/evobot#57]
Adding this would be really cool. What this does is when you type !skipto (song queue nunber), the bot will will skip the other song(s) and play the music in the song queue number that you provided

**Comment by eritislami** [comment]
Thanks for the suggestion, will consider working on this once some other issues are handled

**Comment by eritislami** [comment]
Added skip to in 4da3b49faaf83d84ecb58cf6e86b320ed1ac59b8 if you notice any problems please leave a comment in this issue
