### ISSUE TITLE
Bot error on manual disconnection by user

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#58]
**Describe the bug**
If you disconnect the bot manually, it stops working properly.

**How To Reproduce**
1.Play a song
2.Manually disconnect the bot
 
**Expected behavior**
The bot should stop/clear the queue if it get's manually disconnected by a user.

**Environment (add if possible)**
* Node.js version: 12.x^

**Comment by eritislami** [comment]
What exactly do you mean by 'manually disconnect' did you just end the process?

**Comment by penguz** [comment]
> What exactly do you mean by 'manually disconnect' did you just end the process?

Disconnecting the bot by right clicking while in voice chat and clicking disconnect.

**Comment by ParasDeshpande** [comment]
Yes... @penguz

**Comment by eritislami** [comment]
Fixed in ff9242d544b24dab6c01c24d1b56b56788f96212
