### ISSUE TITLE
Bug:  Failed at the @discordjs/opus@0.3.3 install script.

### ISSUE THREAD

**Issue by wmichx** [eritislami/evobot#598]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\micha\AppData\Roaming\npm-cache\_logs\2021-01-26T17_48_32_867Z-debug.log

**Comment by n0thingeb** [comment]
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\micha\Desktop\evobot-master\node_modules\prism-media\src\util\loader.js
- C:\Users\micha\Desktop\evobot-master\node_modules\prism-media\src\opus\Opus.js
- C:\Users\micha\Desktop\evobot-master\node_modules\prism-media\src\opus\index.js
- C:\Users\micha\Desktop\evobot-master\node_modules\prism-media\src\index.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\client\voice\player\BasePlayer.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\client\voice\player\BroadcastAudioPlayer.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\client\voice\VoiceBroadcast.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\client\voice\ClientVoiceManager.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\client\Client.js
- C:\Users\micha\Desktop\evobot-master\node_modules\discord.js\src\index.js
- C:\Users\micha\Desktop\evobot-master\index.js
Error: Cannot find module 'opusscript'
Require stack:

**Comment by SonMaxime** [comment]
try to install `opusscript` | `@discordjs/opus` | `node-opus` | again or try to install additionnal tools for nodejs
