### ISSUE TITLE
Enhancement for Music Volume [Assign the volume value to guild instead of queue]

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#60]
**Is your feature request related to a problem? Please describe.**
The bot volume changes whenever the queue ends. It is really annoying sometimes when we have to use the volume command everytime the queue ends.

**Describe the solution you'd like**
Assign the volume value to guild instead of queue.

**Comment by eritislami** [comment]
You can right click on the bot and set the 'user volume' to whatever you prefer, i don't see your solution as neccesarry at the moment.
