### ISSUE TITLE
Bug: Command Error

### ISSUE THREAD

**Issue by dBerkeTurkmen** [eritislami/evobot#605]
**Describe the bug**
I get an error when try to use /help command.

**Environment (add if possible)**
* Node.js version: v10.19.0
* OS: Linux Ubuntu 20.04

**Additional information & screenshots**
https://prnt.sc/xpxepf

**Comment by eritislami** [comment]
Your node.js installation is old, https://nodejs.org/en/ update to the LTS version to fix.
