### ISSUE TITLE
Bug: Error

### ISSUE THREAD

**Issue by dBerkeTurkmen** [eritislami/evobot#611]
`Error: Error: Cannot find module '/home/ubuntu/bot/Test/evobot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/@discordjs/opus/lib/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
    at Object.loader [as require] (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:149:5)
    at download (/home/ubuntu/bot/Test/evobot/node_modules/ytdl-core-discord/index.js:51:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async play (/home/ubuntu/bot/Test/evobot/include/play.js:38:18)
/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/769172427908841472/messages',
  code: 50035,
  httpStatus: 400
}
ubuntu@ip-172-31-33-48:~/bot/Test/evobot$ a
a: command not found
ubuntu@ip-172-31-33-48:~/bot/Test/evobot$
ubuntu@ip-172-31-33-48:~/bot/Test/evobot$ a
a: command not found
ubuntu@ip-172-31-33-48:~/bot/Test/evobot$ node index.js
Golden Company ready!
TypeError: Cannot read property 'url' of undefined
    at Object.execute (/home/ubuntu/bot/Test/evobot/commands/play.js:107:50)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Error: Error: Cannot find module '/home/ubuntu/bot/Test/evobot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-linux-x64-glibc-2.31/opus.node'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/@discordjs/opus/lib/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/index.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/client/Client.js
- /home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/index.js
- /home/ubuntu/bot/Test/evobot/index.js
    at Object.loader [as require] (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/ubuntu/bot/Test/evobot/node_modules/prism-media/src/opus/Opus.js:149:5)
    at download (/home/ubuntu/bot/Test/evobot/node_modules/ytdl-core-discord/index.js:51:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async play (/home/ubuntu/bot/Test/evobot/include/play.js:38:18)
/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/home/ubuntu/bot/Test/evobot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/769172427908841472/messages',
  code: 50035,
  httpStatus: 400
}`

**Comment by Amitexing** [comment]
+

**Comment by Takiyo0** [comment]
have you installed `@discordjs/opus` package? If still not working, try to `npm install` again to make sure all modules on package.json is installed. and if it's not working, maybe try to download again evobot's file from this github

**Comment by eritislami** [comment]
Try deleting node_modules and npm install, make sure your package and package-lock is same as the master branch files
