### ISSUE TITLE
Bug: Error: No suitable format found

### ISSUE THREAD

**Issue by SrPeterr** [eritislami/evobot#616]
**Describe the bug**
Every time I play a song, I tried a few, this error occurs

**How To Reproduce**
1.Play a song
2.Bot doesn't play the song and then leaves
 
**Expected behavior**
Play the specified song

**Environment (add if possible)**
* Node.js version: v12.18.3

**Additional information & screenshots**
Add any other context or screenshots about the problem here.
![image](https://user-images.githubusercontent.com/21348463/106449164-f7740000-6483-11eb-8031-cdeaa3fa2f90.png)

**Comment by eritislami** [comment]
Sometimes it can't find a playable format it's not a bug, what you can do is make sure you have latest package versions, update to node 14 and try again
