### ISSUE TITLE
Bug: Playlist command not fetching the song duration 

### ISSUE THREAD

**Issue by henry-bao** [eritislami/evobot#622]
**Describe the bug**
Songs that were imported by /playlist have a duration of -1 instead of their actual duration.

**How To Reproduce**
1. Import any playlist using the /playlist command
2. Check /nowplaying and the time bar won't show up
 
**Expected behavior**
Reading the code for the playlist command I expected the duration to be fetched in seconds and should show up on /nowplay

**Environment (add if possible)**
* Node.js version: v14.15.1

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
It's on purpose to reduce the youtube api cost, this can be fixed easy but you would reach the quota much faster so it's not worth it in my opinion
https://github.com/eritislami/evobot/blob/9b37eea244e7dfeceede23fd934e8f239be3fde1/commands/playlist.js#L63
https://github.com/eritislami/evobot/blob/9b37eea244e7dfeceede23fd934e8f239be3fde1/commands/playlist.js#L80

Those are the lines that determine what information is returned by the youtube api, snippet is the lowest cost to play the song, you can change it in your own bot if you think its important

**Comment by henry-bao** [comment]
Hi, I know this discussion has been closed but I found a way to actually fetch the `durationSeconds` without changing the `{ part: "snippet" }` bit
```js
    const newSongs = await Promise.all(videos
    .filter((video) => video.title != "Private video" && video.title != "Deleted video")
    .map(async (video) => {
      const vid = await video.fetch();
        return(song = {
          title: video.title,
          url: video.url,
          duration: vid.durationSeconds,
          thumbnail: video.thumbnails.medium.url
        });
    }));
```
Here's the code if anyone wants, also thanks for the reply Erit ^_^

**Comment by eritislami** [comment]
Okay will check this again, last time i checked the duration was not returned by the api 👀
