### ISSUE TITLE
Add a command for have custom prefix per server

### ISSUE THREAD

**Issue by ZyGout** [eritislami/evobot#624]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by Takiyo0** [comment]
do you want it with mongodb? i can give example for this

**Comment by ZyGout** [comment]
No, with quick.db and I already have this but for the LOCALE I can't do that (for the music)
