### ISSUE TITLE
Bug: Unable to deploy to heroku

### ISSUE THREAD

**Issue by ShashankKumarSaxena** [eritislami/evobot#630]
I tried to deploy it in heroku. The logs are clear no error but it doesn't plays the music

it shows me this error 

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

please help
![image](https://user-images.githubusercontent.com/69804741/107259837-7e684000-6a63-11eb-8f94-7a40101e095f.png)
here is the full log image

**Comment by dlcoals** [comment]
Are you using web dyno?
you have to use worker dyno by adding Procfile.

**Comment by wolf-yuan-6115** [comment]
@eritislami Already add the Profile, just start the worker dyno instead web dyno
