### ISSUE TITLE
 Error: Cannot find module 'i18n' on Docker version

### ISSUE THREAD

**Issue by JuezFenix** [eritislami/evobot#639]
Hi, trying to update from 0.9.0 to 0.10.0 i get this error

I try editing Dockerfile changing to node:14.15.5-slim base and adding "npm install i18n --save" before npm install, but the error persist.

Please update Dockerfile or fix the error.

**Comment by JuezFenix** [comment]
Neverming, i create a new Dockerfile and upload to Dockerhub https://hub.docker.com/r/juezfenix/evobot-docker

**Comment by FatGrizzly** [comment]
uhh, @eritislami can you update the dockerfile, I am having this issue too

**Comment by survivedtoast** [comment]
> uhh, @eritislami can you update the dockerfile, I am having this issue too

Yes please update, guys a temporary fix is to delete everything, save all the important stuff, and just start over, but that's about it. Please fix this, it's happend to me.
