### ISSUE TITLE
Error on search command

### ISSUE THREAD

**Issue by inxec** [eritislami/evobot#64]
I have this error
![Screenshot_20200612_212833](https://user-images.githubusercontent.com/64691412/84507715-d80d4480-acf3-11ea-84a5-6814bc7ea541.JPG)
This is the const channel code:
 const channel = message.member.voice

I still have the same code of search.js in this repository

**Comment by eritislami** [comment]
Try with a fresh clone of the project in another folder, if it works then you have to check your own modifications

**Comment by eritislami** [comment]
If you find an issue with the bot feel free to reply otherwise i can't help you with your personal discord bot.
