### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Ronak83s** [eritislami/evobot#644]
![Screenshot 2021-02-13 202903](https://user-images.githubusercontent.com/72686370/107853115-256d2300-6e3a-11eb-8f4e-d2306d1e4ed5.png)

**Comment by Ronak83s** [comment]
It's not writing the proper reply
like Enabled or Disabled

**Comment by Sekzi03** [comment]
PS C:\Users\thana\OneDrive\Computer\evobor> node .
C:\Users\****\OneDrive\Computer\evobtter\index.js:10
const { canModifyQueue, LOCALE } = require("../util/EvobotUtil"); 

Any idea what happened here?
