### ISSUE TITLE
[ FEATURE REQUEST ] Add lyrics command

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#65]
**Describe the solution you'd like**
It would be really nice to have a lyrics command for the bot to get the lyrics of the current playing song like other bots...

**Additional context**
This should be really helpful for a lyrics command - https://www.npmjs.com/package/lyrics-finder

**Comment by eritislami** [comment]
Added as you suggested in f0319fd924f8d04680ed55c73e440be06245fd2d
