### ISSUE TITLE
 Can you change it ? member.send change to message.channel.send

### ISSUE THREAD

**Issue by ImPoppy03** [eritislami/evobot#66]
```
module.exports = {
  canModifyQueue(member) {
    const { channel } = member.voice;
    const botChannel = member.guild.me.voice.channel;

    if (channel !== botChannel) {
      member.send("You need to join the voice channel first!").catch(console.error);
      return false;
    }

    return true;
  }
};

**Comment by eritislami** [comment]
I wrote it the way it is now so it can be used to handle media reactions as well

**Comment by ImPoppy03** [comment]
I am not using the reaction system. Please change for me. 😄

**Comment by eritislami** [comment]
> I am not using the reaction system. Please change for me. 😄

I will show you how to change it but not do it myself.

Change this line in command files from `if (!canModifyQueue(message.member)) return;` to `if (!canModifyQueue(message)) return;`

And `member.send("You need to join the voice channel first!").catch(console.error);` to `message.channel.send("You need to join the voice channel first!").catch(console.error);`

**Comment by ImPoppy03** [comment]
message and channel not defined omg 😞

**Comment by eritislami** [comment]
try this
```js
module.exports = {
  canModifyQueue(message) {
    const { channel } = message.member.voice;
    const botChannel = message.member.guild.me.voice.channel;

    if (channel !== botChannel) {
      message.channel.send("You need to join the voice channel first!").catch(console.error);
      return false;
    }

    return true;
  }
};
```
