### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ayLynx1** [eritislami/evobot#672]
**Describe the bug**
Music pauses for a while and speeds up to catch up with it self.
I have allocated 2.5gb of ram for the bot which should be more than enough and I have a very stable internet connection.
**How To Reproduce**
1.  Let the bot run for a while.
2. It happens randomly
 
**Expected behavior**
It shouldnt pause randomly and play smoothly

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by zorrigas** [comment]
is a Lag problem, possible a lost connection for secounds

**Comment by wolf-yuan-6115** [comment]
It's not ram' problem
My server only have 512 MB ram but it working perfectly

**Comment by Maks1116** [comment]
It is internet connection problem
