### ISSUE TITLE
Bump ytdl-core to newer versio 

### ISSUE THREAD

**Issue by survivedtoast** [eritislami/evobot#677]
**Describe the bug**
A description of what the bug is.

Bassicly just update YTDL-Core, thanks.

**How To Reproduce**
1. Just play a song
2. GIves you an error saying it needs to be updated
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 1.14.60

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by wolf-yuan-6115** [comment]
Update yourself

**Comment by SugarD-x** [comment]
> Update yourself

That doesn't exactly update the project, hence why he posted it here...

For the record, updating my copy of the project to the latest dependencies didn't cause any issues that I could find, and actually fixed some playback problems I was having.
