### ISSUE TITLE
Add feature - Crossfade between songs

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#68]
**Describe the solution you'd like**
Is it possible to make the queue crossfade to another song instead of starting a new song after the earlier song is over. Like spotify and some other music apps crossfade between songs instead of letting the earlier song end and then playing a new one.

**Additional context**
If it is possible, it would make the bot much better from some other busic bots...

**Comment by eritislami** [comment]
Not possible in the current implementation
