### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by TrippieNight** [eritislami/evobot#686]
**Describe the bug**
My bot is on a host that uses Linux as an operating system, and I think that because of this, it can not play live broadcasts. I hosted the bot on my computer and Heroku and everything worked, but when I run it on a Linux host after starting the live broadcast playback, the bot immediately stops, without starting to play

**Comment by Takiyo0** [comment]
do you have a great connection? because playing live music is taking more resource than normal music. Also, i think your Linux isn't the problem because heroku used Linux for it's OS.

**Comment by Moquent** [comment]
> **Describe the bug**
> My bot is on a host that uses Linux as an operating system, and I think that because of this, it can not play live broadcasts. I hosted the bot on my computer and Heroku and everything worked, but when I run it on a Linux host after starting the live broadcast playback, the bot immediately stops, without starting to play

@TrippieNight having Linux as an OS hosting your bot is extremely more efficient than Windows as a host. The current problem you're having if I'm not wrong is either your CPU architecture or internet connection speed.
