### ISSUE TITLE
Add lavalink support.

### ISSUE THREAD

**Issue by IamTheRealSami** [eritislami/evobot#7]
As ffmepg gives studdering noise on Discord if you don't have a stable network. And lavalink is now very popular on Discord. It's be great if all the music bots on Discord have High Quality Music Streaming.

**Comment by Yonle** [comment]
yeah sound is great. but by one question:

-Do you have a host????

**Comment by IamTheRealSami** [comment]
Yes I've a host. Add me on Discord. My username is Error#3167

**Comment by eritislami** [comment]
I don't have plans to do this right now or the near future
