### ISSUE TITLE
Bug: Bot raises Error [VOICE_CONNECTION_TIMEOUT] when I try to play a song

### ISSUE THREAD

**Issue by Jack1424** [eritislami/evobot#716]
**Describe the bug**
Every time I run the /play command to try and play a song, the bot will join the voice channel, but then after 15 seconds of silence, it raises an error and leaves. I have attached the error below.

**Environment**
* Node.js version: 14.16.1
* Running on Ubuntu Server 20.04

**Additional information & screenshots**
![Capture](https://user-images.githubusercontent.com/55409055/116491210-61bff500-a867-11eb-8038-ad3fea155ad6.PNG)
![Capture](https://user-images.githubusercontent.com/55409055/116491450-e01c9700-a867-11eb-9229-4b6735d51e76.PNG)

**Notes**
I have tried running the command while I was in a completely open voice channel while the bot had full permissions. Everything is completely updated. I know that this isn't a connection issue either as I have other Discord bots running on this VM. The VM is connected to the internet via unrestricted 10GB fiber.

**Comment by eritislami** [comment]
Definitely not a bug from the bot side, nothing you can change in the code to fix this, what I suggest you can try is to change the voice region for the voice channel and see if its still happening, it could also have trouble connecting to discord api despite you having a good internet connection.

**Comment by Jack1424** [comment]
Changing the voice region didn't seem to change anything. I'm pretty sure that I have a good connection to the Discord API because I have other bots running on this server as well. I have gotten evobot running on this setup before, but after I wiped the server it stopped working.

**Comment by hellomrjones** [comment]
Same error. Bot is broken. There is a solution proposed here, but I don't know how to apply it https://github.com/discordjs/discord.js/issues/2979

**Comment by hellomrjones** [comment]
https://bleepcoder.com/discord-js/256397644/authenticate-failed says you should " I just wanted to save you some time by pointing out that it is possible to get this error if your voice room doesn't have the "View Channel" permission enabled for the bot." 

Got no clue where to set this. Any ideas?

**Comment by hellomrjones** [comment]
In the channel itself, Bot has all the permissions...

**Comment by Jack1424** [comment]
Sorry that it took so long for me to reply, and thanks for helping me out.

I've attached all of the settings that I am using in Discord to configure bot the bot and a test channel that I have made. My server is located on the east coast. Anyone on the Discord server has full access to the voice channel and the bot has all permissions enabled.

**Voice Channel Settings**
![permissions2](https://user-images.githubusercontent.com/55409055/116919629-89c0a700-ac1f-11eb-91f3-151b476171c1.PNG)
![permissions1](https://user-images.githubusercontent.com/55409055/116919630-89c0a700-ac1f-11eb-832c-2bbb95d3900a.PNG)
![overview](https://user-images.githubusercontent.com/55409055/116919631-89c0a700-ac1f-11eb-8754-b1d740d48caa.PNG)

**Bot Role Settings**
![role6](https://user-images.githubusercontent.com/55409055/116919658-947b3c00-ac1f-11eb-8873-fb63ab5e57af.PNG)
![role5](https://user-images.githubusercontent.com/55409055/116919659-9513d280-ac1f-11eb-8cd0-583b6d9d7e15.PNG)
![role4](https://user-images.githubusercontent.com/55409055/116919660-9513d280-ac1f-11eb-834c-ffe49f96283c.PNG)
![role3](https://user-images.githubusercontent.com/55409055/116919661-9513d280-ac1f-11eb-97a3-0f4c3104b132.PNG)
![role2](https://user-images.githubusercontent.com/55409055/116919662-9513d280-ac1f-11eb-8921-b1e40fe6b7bb.PNG)
![role1](https://user-images.githubusercontent.com/55409055/116919663-9513d280-ac1f-11eb-9b0f-164d40bc741a.PNG)

I'm pretty sure that this isn't an issue with the way that I have my Discord server configured. Maybe I set the bot up wrong? Is there any other information I can provide that will help you?

**Comment by eritislami** [comment]
> Please fix this immediately and stop pushing backend changes with no notification. Thanks.

Hope you are referring to discord.js developers and not me or the project, it's fairly obvious that I can only react to fix things after the discord developers make changes, I certainly don't work for Discord directly.

**Comment by NotSoEvilDead** [comment]
Sorry, a different github issue from discord staff linked directly into this one.  Yes, this is absolutely discord's problem to fix.  Cheers.
