### ISSUE TITLE
Bug: On using playlist commands (without playing music) bot responds in dm...

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#72]
**Describe the bug**
On using playlist commands, bot responds with "you need to join voice channel first" in dm.

**How To Reproduce**
1.Join a voice channel
2.Use skip command
 
**Expected behavior**
Bot should respond with "Nothing is playing" in server text channel instead of dm....

**Environment (add if possible)**
* Node.js version: ^12.0.x

**Info**
This should be an issue in canModifyQueue()

In canModifyQueue() you only check for the channel but not for the queue playing...
There should be different messages for both things...

**Comment by eritislami** [comment]
b488dcea868b2d00596ddd8a7abe90cb00ae5ac1
