### ISSUE TITLE
Add Sharding System

### ISSUE THREAD

**Issue by rexjohannes** [eritislami/evobot#721]
**Is your feature request related to a problem? Please describe.**
Please add an Sharding System to run the Bot on more Servers better.
**Describe the solution you'd like**
Just an Simple Sharding Manager
**Describe alternatives you've considered**
Like this code https://github.com/littlestudios69/Little_Music/blob/main/shard.js
**Additional context**
/

**Comment by Tomato6966** [comment]
That code u shared is actually my code, and i tell you that does not work for such a music bot with reactions

Why?
You have to change many things for the each shards. that's not useful enough. 

Do internal sharding!
