### ISSUE TITLE
Bug: When i do -pruning it sends "Message pruning is {result}" instead of "Message pruning is on/off" how do i fix it ?

### ISSUE THREAD

**Issue by ryzyx** [eritislami/evobot#725]
**Describe the bug**
Pruning system does not work
 
When i do -pruning it sends "Message pruning is {result}" instead of "Message pruning is on/off" how do i fix it ?

**Comment by wolf-yuan-6115** [comment]
Please describe this bug clearly, thanks!

**Comment by ryzyx** [comment]
> Please describe this bug clearly, thanks!

Ive edited it now :D

**Comment by ryzyx** [comment]
> Please describe this bug clearly, thanks!

I mean ive edited the comment i made here i am still not able to fix it

**Comment by wolf-yuan-6115** [comment]
What command did you typed?

**Comment by ryzyx** [comment]
@wolf-yuan-6115 i hope this is what u were asking for

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 i hope this is what u were asking for

Sorry, can you provide **Command that you are typed in Discord**

**Comment by wolf-yuan-6115** [comment]
And please also check closed issues.

**Comment by ryzyx** [comment]
> > @wolf-yuan-6115 i hope this is what u were asking for
> 
> Sorry, can you provide **Command that you are typed in Discord**

sns pruning

**Comment by ryzyx** [comment]
> And please also check closed issues.

im guessing you are not a native English speaker. Yeah i checked all with pruning and stuff. There was a issue but the person didnt tell the fix

**Comment by wolf-yuan-6115** [comment]
> > And please also check closed issues.
> 
> im guessing you are not a native English speaker. Yeah i checked all with pruning and stuff. There was a issue but the person didnt tell the fix
> 

Yes, I'm not a native English speaker, you can check my Github profile.
And I will open a PR that will fix this issue.

**Comment by ryzyx** [comment]
> > > And please also check closed issues.
> > 
> > 
> > im guessing you are not a native English speaker. Yeah i checked all with pruning and stuff. There was a issue but the person didnt tell the fix
> 
> Yes, I'm not a native English speaker, you can check my Github profile.
> And I will open a PR that will fix this issue.
what is a PR?

**Comment by ryzyx** [comment]
ah ok u mean pull request

**Comment by wolf-yuan-6115** [comment]
> ah ok u mean pull request

Sorry, PR will delay because I'm busy now.
