### ISSUE TITLE
Bug: createBar not a function

### ISSUE THREAD

**Issue by dylanjamesdev** [eritislami/evobot#736]
**Describe the bug**
Createbar is not a function and is failing in all commands that require it.

**Environment (add if possible)** Ubuntu Server 20.04 LTS
* Node.js version: 14.16.1

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

Image: https://dylan.uwu.solutions/MEqydj2e

**Comment by Sparker-99** [comment]
Have a look at pull request #735 . Internal functions have been updated for version 1.0.4, the one that you are using.

**Comment by dylanjamesdev** [comment]
Thank you :)
