### ISSUE TITLE
nowplaying command doesn't work properly when songs are queued using a playlist

### ISSUE THREAD

**Issue by ryzyx** [eritislami/evobot#737]
**Is your feature request related to a problem? Please describe.**
The nowplaying command doesnt show the bar properly when a youtube playlist has been queued

**Describe the solution you'd like**
I would like the nowplaying bar to show the current length of the song.

**Describe alternatives you've considered**
It works perfectly fine when you queue songs one by one. But when u queue it using a playlist it breaks

**Additional context**
No

**Comment by ryzyx** [comment]
Pls help

**Comment by wolf-yuan-6115** [comment]
Know issue.

**Comment by wolf-yuan-6115** [comment]
YouTube API won't return video length
