### ISSUE TITLE
Bug: Issue with skipping songs when paused.

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#75]
**Describe the bug**
When the queue is paused and i skip the song, two songs are played after resuming.

**How To Reproduce**
1.Play a playlist
2.Pause the queue
3.Skip to a song
4.Resume the queue
 
**Expected behavior**
The song that i skipped to must be played, but the earlier message is also sent after resuming...

**Environment (add if possible)**
* Node.js version: ^12.0.x

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/63962807/84585998-06de0480-ae33-11ea-8162-995d3612baa3.png)

**Comment by ParasDeshpande** [comment]
Also after that whenever i skip the song, this error keeps occuring until i restart the bot...
The reactions are not added.
Nothing in the code was changed except getting the thumbnail from youtube and making the started playing message into an embed...

![image](https://user-images.githubusercontent.com/63962807/84586297-fb400d00-ae35-11ea-98dc-69f00b1d967a.png)


```
DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\Other\Bot Coding\Bots\Currently Working\evobot\src\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'put',
  path: '/channels/718919267923263491/messages/721610671787081829/reactions/%E2%8F%AF/@me',
  code: 10008,
  httpStatus: 404
}
```

**Comment by eritislami** [comment]
Can you test this again in 6dc676d636323b57b7cdb5044ebda6788710fc7b ? I believe it should work properly now

**Comment by ParasDeshpande** [comment]
I tried that, it works now but sometimes it fails to add reactions to the message. It just adds one reaction and gives this error.

```
DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\Other\Bot Coding\Bots\Currently Working\Ririchiyo Music V-0.4.0\src\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'put',
  path: '/channels/718919267923263491/messages/721703913358884927/reactions/%E2%8F%AF/@me',
  code: 10008,
  httpStatus: 404
}
```

![image](https://user-images.githubusercontent.com/63962807/84593505-3bb97e00-ae6a-11ea-8fcc-3f3474140a2e.png)


And also the pause thing is not working properly... When i pause the song and then skip to a song and then unpause the queue it sends 2 messages of 2 different songs at once....

![image](https://user-images.githubusercontent.com/63962807/84593707-15e0a900-ae6b-11ea-9cb0-38aac5750317.png)

**Comment by eritislami** [comment]
After my latest changes today it should be better than before, also note during my testing i never got the unknown message error, i think its only happening on your side.

If you do decide to test these changes please do it on a fresh clone without any changes at all otherwise this discussion is pointless

**Comment by ParasDeshpande** [comment]
Sure... But i think the message embed for playing should not make any difference...
I also tried it with the fresh clone without changes (earlier), the issue was the same on both... I will test out the newer version and let you know... : )

**Comment by eritislami** [comment]
Will close this soon if this has been resolved

**Comment by ParasDeshpande** [comment]
I think the issue is solved in the latest commit... :)
