### ISSUE TITLE
Bug: I dont have a bot.js

### ISSUE THREAD

**Issue by LOGODERKING** [eritislami/evobot#757]
I dont have a bot.js file and the bot doenst start because of that problem

**Comment by wolf-yuan-6115** [comment]
evobot use index.js, not bot.js ==

**Comment by LOGODERKING** [comment]
but if i want to start the bot there is standing Error: Cannot find module 'discord.js'

**Comment by Takaki-Sakura** [comment]
The thing is don't climb the ladder if you don't know how it works, learn js first

**Comment by wolf-yuan-6115** [comment]
> but if i want to start the bot there is standing Error: Cannot find module 'discord.js'

Start command:
```
npm i
node index.js
```
If you have other questions, please google first
