### ISSUE TITLE
Status Code 404

### ISSUE THREAD

**Issue by DavidRoyaleYT2** [eritislami/evobot#760]
I have 404 error whit my bot of discord can you help me

**Comment by Tantoony** [comment]
uh.. can you take a screenshot of it?

**Comment by DavidRoyaleYT2** [comment]
I fix it

**Comment by DC-Guru** [comment]
I am having the same issue in the every music bot i made from this repo

**Comment by SrIzan10** [comment]
https://github.com/eritislami/evobot/issues/774#issue-927117409

**Comment by eritislami** [comment]
4b4a2e84ff2b245c752631008f619d1232bb3f58

get newest commit & `npm install`
