### ISSUE TITLE
https://discordapp.com/api/oauth2/authorize?client_id=YOUR_BOT_ID_HERE&scope=bot&permissions

### ISSUE THREAD

**Issue by ccsdscs** [eritislami/evobot#771]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by ccsdscs** [comment]
# ```
> ``
```

**Comment by wolf-yuan-6115** [comment]
?

**Comment by SrIzan10** [comment]
uhhhh
