### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by KwzGVGN** [eritislami/evobot#775]
Hello 'I have a 404 error every time I start a music and nothing happens I give you a screen
![Capture d’écran (384)](https://user-images.githubusercontent.com/79052324/122940193-8cfd2700-d374-11eb-98b3-fd2c14b49a0d.png)

**Comment by sykkuno23567** [comment]
me too

**Comment by SamueleArrigo** [comment]
Has anyone found a solution?
I have already update ytdl-core but the issue persist.

**Comment by Marshxan** [comment]
YTDL is down there is to EST time for it to be back up just wait!

**Comment by SamueleArrigo** [comment]
> YTDL is down there is to EST time for it to be back up just wait!

Ok, thanks!

**Comment by wolf-yuan-6115** [comment]
https://github.com/eritislami/evobot/issues/774

**Comment by eritislami** [comment]
4b4a2e84ff2b245c752631008f619d1232bb3f58

get newest commit & `npm install`
