### ISSUE TITLE
Bug: Status code: 404

### ISSUE THREAD

**Issue by Ellischnelli** [eritislami/evobot#778]
Everytime I want to play musik the Bot says: Status code: 404!
I've been looking for hours but i coudn't find any mistakes!

Can someone pleas help me?

![Discort](https://user-images.githubusercontent.com/81874364/123311393-6f23f380-d527-11eb-82a4-e62d30e236eb.png)

**Comment by ryzyx** [comment]
#774

**Comment by eritislami** [comment]
4b4a2e84ff2b245c752631008f619d1232bb3f58

get newest commit & `npm install`
