### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by D4rkk1** [eritislami/evobot#783]
is there a way to put spotify API?

**Comment by dylanjamesdev** [comment]
Theres a pull req for that somewhere

**Comment by SugarD-x** [comment]
https://github.com/eritislami/evobot/pull/590

**Comment by BlazeIsClone** [comment]
If anyone needs to know how Spotify API works along with YouTube and SoundClound, I bootstrapped everything: [blazeIsClone/A41SLBOT](https://github.com/BlazeIsClone/A41SLBOT)
