### ISSUE TITLE
Heroku issue

### ISSUE THREAD

**Issue by mrhappyma** [eritislami/evobot#785]
**Describe the bug**
It keeps crashing, getting this in the logs:
heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
heroku[web.1]: Stopping process with SIGKILL
heroku[web.1]: Process exited with status 137
heroku[web.1]: State changed from starting to crashed
**How To Reproduce**
I just start the app and it does that and if I restart it does that too
 
**Expected behavior**
it would work and not crash

**Environment (add if possible)**
* Node.js version: idk the one that keroku uses

**Additional information & screenshots**
nope

**Comment by wolf-yuan-6115** [comment]
Start **worker** dyno instead **web** dyno

**Comment by ndbiaw** [comment]
are you sure you changed Dynos' running pattern from web to bot?

**Comment by SrIzan10** [comment]
@mrhappyma ^
