### ISSUE TITLE
Bug: !help command not working

### ISSUE THREAD

**Issue by darkmannie** [eritislami/evobot#789]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1. Write !help in chat
2. Get ur error msg
 
**Expected behavior**
See commandslist in discord

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

![image](https://user-images.githubusercontent.com/15308910/125176650-76105e80-e1d5-11eb-82c8-6463ad8916c4.png)

**Comment by wolf-yuan-6115** [comment]
Can you provide a screenshot that is using English locale?
I can't understand what is that error message.

**Comment by darkmannie** [comment]
Sure, thats all i got
![image](https://user-images.githubusercontent.com/15308910/125181961-239d6500-e20a-11eb-9a61-4001b0ae6418.png)

**Comment by wolf-yuan-6115** [comment]
Use node.js version >14.x<=14.16.1
You probably using node js 12.x

**Comment by darkmannie** [comment]
my bad, update has fixed it, thank you for ur assistance

![image](https://user-images.githubusercontent.com/15308910/125190118-cc17ed00-e23b-11eb-8631-7bd9d4758276.png)

**Comment by wolf-yuan-6115** [comment]
Please use node.js `<=14.16.1`, node.js `>14.16.1` will let pause command broke

**Comment by SrIzan10** [comment]
The best version to use is LTS, that works just fine
