### ISSUE TITLE
Seek Command

### ISSUE THREAD

**Issue by abdooo9** [eritislami/evobot#792]
We need seek command for move position of the track
Example use:
!seek 1:30
The bot will move the track to 1 minute, 30 seconds..
Thank You..

**Comment by wolf-yuan-6115** [comment]
> We need seek command for move position of the track
> Example use:
> !seek 1:30
> The bot will move the track to 1 minute, 30 seconds..
> Thank You..

You can search solution on Google and open a pull request if you want.

**Comment by abdooo9** [comment]
.
