### ISSUE TITLE
Bug Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by luisbaker** [eritislami/evobot#81]
When a video is unavailable in a country where the bot is hosted, the bot simply crashes and I need to restart it
(node:7700) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at C:\Users\Administrator\Desktop\evobot\node_modules\ytdl-core-discord\index.js:40:41
    at C:\Users\Administrator\Desktop\evobot\node_modules\ytdl-core-discord\node_modules\ytdl-core\lib\info.js:288:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eritislami** [comment]
This is a duplicate issue of #52 the error needs to be fixed by ytdl-core-discord author
