### ISSUE TITLE
Error [VOICE_CONNECTION_TIMEOUT]

### ISSUE THREAD

**Issue by Deym-String** [eritislami/evobot#83]
Help I tried to use this Music bot and installed all node modules without any problem or error but when I tried to play a music to my server this shows up. I already tried to change Discord server location still the same error.

`(node:441219) UnhandledPromiseRejectionWarning: Error: send EPERM 213.179.200.232:50004
    at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)`

`(node:441219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

`(node:441219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by eritislami** [comment]
Likely your bot is missing permissions, try giving it administrator role in your server

**Comment by Deym-String** [comment]
> 
> 
> Likely your bot is missing permissions, try giving it administrator role in your server

I already given the bot a role with all access to my discord server.

**Comment by eritislami** [comment]
I tried to google research your error but honestly there are 0 results about it, can you try a complete fresh reinstall of the bot?

**Comment by Deym-String** [comment]
The error was from my Hosting provider.

**Source of Problem:**
The hosting I used wasn't allowed for inbound UDP.

**Solve by the following:**
Switching to another Hosting provider.
