### ISSUE TITLE
Bug: Bot leaves channel on starting music (no error)

### ISSUE THREAD

**Issue by ParasDeshpande** [eritislami/evobot#84]
**Describe the bug**
Bot leaves channel on starting music.

**How To Reproduce**
1.use play command

**Additional information & screenshots**
![Capture15](https://user-images.githubusercontent.com/63962807/85145222-e2868b80-b269-11ea-83f3-8487d9c6f576.PNG)

**Comment by eritislami** [comment]
Thats a livestream... its not supported by the bot

**Comment by eritislami** [comment]
Some live videos like this: https://www.youtube.com/watch?v=UmeCfbG3too work fine with the bot, these things depent on the ytdl-core packages and i can't do anything to change that.
