### ISSUE TITLE
When using the pruning command

### ISSUE THREAD

**Issue by Stan2016Games** [eritislami/evobot#845]
The command returns a command that doesn't do what it is supposed to.

**How To Reproduce**
1. type in /pruning
 
**Expected behavior**
it will do what pruning is supposed to

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
"Message pruning is {result}"

**Comment by wolf-yuan-6115** [comment]
Already fixed in https://github.com/eritislami/evobot/pull/740/
You might using outdated version

**Comment by tsukasaroot** [comment]
I confirm, I build directly from master branch and having this issue on pruning with latest version of node.js.
