### ISSUE TITLE
Slash Command

### ISSUE THREAD

**Issue by totoyzx** [eritislami/evobot#849]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want slash command

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by Velosofy** [comment]
Please explain your "feature request"
What slash command do you want

**Comment by totoyzx** [comment]
![Screenshot_20210901-184839_Discord.jpg](https://user-images.githubusercontent.com/72244878/131658847-a46149d4-b5f4-41e5-93db-b713fcc756f5.jpg)

**Comment by Velosofy** [comment]
To my understanding, these so called "interaction command" is only available from DiscordJS v13.
Currently evobot is running DiscordJS v12

**Comment by totoyzx** [comment]
ok ok, may i know if you are going to make a big release with a lot of new changes?

**Comment by Velosofy** [comment]
I dont think evobot will upgrade to DiscordJS v13 any soon, you can check the other opened Issue that discuss "moving to v13"

**Comment by totoyzx** [comment]
ok thankz
