### ISSUE TITLE
Help: glitch host problem

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#85]
![Screenshot_20200619-221143](https://user-images.githubusercontent.com/53672750/85155849-1918d200-b27b-11ea-9c97-a40a92772699.png)

![Screenshot_20200619-221156](https://user-images.githubusercontent.com/53672750/85155959-3cdc1800-b27b-11ea-94ee-a5a009eb804c.png)
![Screenshot_20200619-221206](https://user-images.githubusercontent.com/53672750/85155991-449bbc80-b27b-11ea-8179-28c6cf05870d.png)

**Comment by eritislami** [comment]
I have never used glitch and don't officially support it here, but what i can see from the error is that you need to run `npm install` on the project.

**Comment by VirusLauncher** [comment]
Problem: here is that there isn't a valid token for discord bot or youtube api.they didn't rename config.json.example to config.json

**Comment by mmoomocow** [comment]
I think the issue is the same as #89 as it starts contains the same error message
I have answered it there but it's what @eritislami said, you need to run `npm install`

**Comment by eritislami** [comment]
Update: https://support.glitch.com/t/an-update-on-pinging-services-glitch/27311

Glitch has made it impossible to host 24/7 apps like discord bots on their platform and is permanently banning these projects
