### ISSUE TITLE
disable messages when using emoji controls

### ISSUE THREAD

**Issue by tarneaux** [eritislami/evobot#855]
Hi,
I'd like to disable the messages when I press the emoji controls. This makes it so that I can't crank the volume down quickly. A bit annoying.
Thanks!

**Comment by wolf-yuan-6115** [comment]
Use commands to crack down volume quickly

**Comment by eritislami** [comment]
It's not because of the messages, the reactions have a minimum time limit from the discord API, so you can't spam it

**Comment by LordRampantHump** [comment]
the simple answer is
play.js

from line 92 remove or comment the following

`await playingMessage.react("⏭");
      await playingMessage.react("⏯");
      await playingMessage.react("🔇");
      await playingMessage.react("🔉");
      await playingMessage.react("🔊");
      await playingMessage.react("🔁");
      await playingMessage.react("⏹");`

**Comment by wolf-yuan-6115** [comment]
It's not a good solution...

**Comment by Goldenfreddy0703** [comment]
Hey @tarneaux , Prune is not working and it just prune the reactions but if you removed these lines then they will disable messages.

**Remove these Lines:**
 115
 125
 129
 139
 143
 155, 156
 167, 168
 175, 176, 177, 178, 179, 180, 181, 182 ---I would keep these if you want to know if your song has it on repeat or not. (🔁)
 189
  
You could remove all these lines or you could download this file and put in the include folder. 
[include.zip](https://github.com/eritislami/evobot/files/7181896/include.zip)

**Comment by Goldenfreddy0703** [comment]
Hey im really sorry, those lines were for the spotify pull request version.
Just download this file and then put it in your include folder and that should do the trick.
[play.zip](https://github.com/eritislami/evobot/files/7181994/play.zip)


If you need any more help, my discord is The Owl Witch#4432

**Comment by tarneaux** [comment]
Thanks, it works!

**Comment by Goldenfreddy0703** [comment]
Hey anytime, I still think the pruning thing is a bug tho but again, your welcome.
