### ISSUE TITLE
No video was found with a matching title

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#86]
![Screenshot_20200620-074309](https://user-images.githubusercontent.com/53672750/85188590-bf8bc400-b2c9-11ea-8e8b-a6435943f22b.png)
Fix that

**Comment by eritislami** [comment]
Fix what exactly? if it doesnt find the video its not like i can do something about it...

![image](https://i.imgur.com/HWrk11m.png)
