### ISSUE TITLE
language with mongoDB

### ISSUE THREAD

**Issue by RyvalAlex** [eritislami/evobot#862]
A version with mongoDB to manage languages on different servers could be interesting.
I tried to do it on my side but it didn't work, i18n can't find the locale.

**Comment by noobyogi0010** [comment]
@RyvalAlex I would like to try and implement this, if you could provide some basic idea or starting steps it'll be great!

**Comment by eritislami** [comment]
Closing as this is irrelevant to the future of the bot at this moment
