### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Stan2016Games** [eritislami/evobot#867]
**Describe the bug**
If you try to play an age restricted video you get error 410.

**How To Reproduce**
1. Input -p {age restricted video}
2. It gives you the error
 
**Expected behavior**
I expected the age restricted video to play

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/70027287/132983203-d4e7403e-e72d-42b3-8fe7-8d940a635692.png)

**Comment by wolf-yuan-6115** [comment]
Then don't play age restricted video

**Comment by Stan2016Games** [comment]
> Then don't play age restricted video

Some music videos are age restricted, so it is impossible to listen to them?

**Comment by eritislami** [comment]
> > Then don't play age restricted video
> 
> Some music videos are age restricted, so it is impossible to listen to them?

No because youtube requires you to verify your age for those videos and we can't work around that right now, not a bug

**Comment by alou-S** [comment]
@eritislami youtube-dl has an option to use a cookies.txt file to bypass the age restriction problem. This can also be implemented in the node module but I didn't succeed (don't know javascript at all or which cookies to use).

Is it possible to implement this so it is easier for the end user?
Thanks.
