### ISSUE TITLE
i need help pls showing error

### ISSUE THREAD

**Issue by GokseLW** [eritislami/evobot#87]
![image](https://user-images.githubusercontent.com/57256097/85196170-ea354700-b2e0-11ea-907b-048a8af9bf6b.png)
![image](https://user-images.githubusercontent.com/57256097/85196225-6760bc00-b2e1-11ea-8e13-7318e4fabd33.png)
![image](https://user-images.githubusercontent.com/57256097/85196228-6c257000-b2e1-11ea-954d-5a37301d9668.png)

**Comment by eritislami** [comment]
Delete node_modules & package-lock.json and run `npm install`

**Comment by GokseLW** [comment]
not working

**Comment by eritislami** [comment]
And you are running the bot on your local computer?

**Comment by GokseLW** [comment]
i runed in local computer in vps + in glitch + repl.it not work

**Comment by eritislami** [comment]
> i runed in local computer in vps + in glitch + repl.it not work

This is a network problem wherever you are hosting the bot, you can try to change the region of your discord server otherwise check discord.js support server or try google your errors

**Comment by GokseLW** [comment]
no its not from host connection or region

**Comment by eritislami** [comment]
> no its not from host connection or region

I tested this on 3 different machines (Windows,MacOS,Ubuntu) and [Vultr VPS](https://www.vultr.com/) and it's working fine for me.
