### ISSUE TITLE
Bug: cant play playlist from spotify

### ISSUE THREAD

**Issue by arz03** [eritislami/evobot#885]
**Describe the bug**
A description of what the bug is.
gives "Cannot read property 'getVideos' of undefined" error in playlist command when using spotify link.
bot phrases youtube playlist instead of spotify songs
**How To Reproduce**
1.use playlist command with a spotify playlist link
2.
 
**Expected behavior**
A description of what you expected to happen.
should've queued all songs fro spotify playlist
**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
screenshot: https://cdn.discordapp.com/attachments/815456992822296596/887779111353864232/unknown.png
Add any other context or screenshots about the problem here.

**Comment by eritislami** [comment]
Spotify is not supported, not sure why you thought this was supposed to work
