### ISSUE TITLE
Evobot arm docker image

### ISSUE THREAD

**Issue by MujiSayed** [eritislami/evobot#897]
**Is your feature request related to a problem? Please describe.**
No issue. I was able to git pull the repository on a rapsberry pi, run npm install and build a docker image using `docker built -t evobot .`

**Describe the solution you'd like**
There's currently a PR #895 for adding docker builds into github actions, could we also create one for arm images for user's running a raspberry pi?

**Describe alternatives you've considered**
The only other alternative for a docker image uploaded into dockerhub is to manually pull the repo, and build the image yourself

**Additional context**
N/A

**Comment by MujiSayed** [comment]
The only issue I've had with manually creating my own docker image is it does not take values from config.json and returns an error stating "The Youtube Key you provided was not a string". A workaround I've used is to manually pass my discord token and youtube api key as an environment variable

**Comment by MujiSayed** [comment]
> 
> 
> The only issue I've had with manually creating my own docker image is it does not take values from config.json and returns an error stating "The Youtube Key you provided was not a string". A workaround I've used is to manually pass my discord token and youtube api key as an environment variable

for anyone else that might across this very problem, this was due to config.json being included in the .dockerignore file. Once the line was removed, i was able to include my config.json in the docker image and could run the app without having to pass any environment variables

**Comment by eritislami** [comment]
> > The only issue I've had with manually creating my own docker image is it does not take values from config.json and returns an error stating "The Youtube Key you provided was not a string". A workaround I've used is to manually pass my discord token and youtube api key as an environment variable
> 
> for anyone else that might across this very problem, this was due to config.json being included in the .dockerignore file. Once the line was removed, i was able to include my config.json in the docker image and could run the app without having to pass any environment variables

Should I remove config from being ignored? i put it there so people don't publish something with their own keys included

**Comment by MujiSayed** [comment]
I don’t think that’d be a good idea. I think a note on the readme would be
more helpful

**Comment by SrIzan10** [comment]
Oh, that’s why I couldn’t build the Docker image in my Raspberry Pi?
I made my own version of the Dockerfile that for me worked. When I get to home I’ll send it.

**Comment by MujiSayed** [comment]
> 
> 
> Oh, that’s why I couldn’t build the Docker image in my Raspberry Pi? I made my own version of the Dockerfile that for me worked. If this is active I’ll send it.

decided to deploy this over to dockerhub on a personal account for arm. If anyone is interested: docker pull basedmeezus/basedbot:latest

**Comment by SrIzan10** [comment]
Ok, my docker image is just:
- Create a volume from a folder that is on the host
- `npm install` it
- Make the volume a workdir
- And everytime the docker containers start, do `git pull && node index.js`

**Comment by MujiSayed** [comment]
Thanks for including the steps for arm docker image. Closing issue as it's no longer required
