### ISSUE TITLE
Connection error when playing song

### ISSUE THREAD

**Issue by WhlIlte** [eritislami/evobot#90]
**Describe the bug**
I just cloned the repository, edited the config.json file, i did npm install and I tried to start the bot, it starts succesfuly but if I use a play command (play, playlist, search) it just throws the error below.

**Environment (add if possible)**
* Node.js version: 12.18.1

**Additional information & screenshots**
Console output:
![image](https://user-images.githubusercontent.com/44441061/85464440-ebe46080-b5a7-11ea-9a08-726aef215b19.png)

**Comment by eritislami** [comment]
I'm not sure what this error is exactly but it's possible that your network/firewall is blocking the connection of the bot
