### ISSUE TITLE
Bug: i can't deploy on Heroku

### ISSUE THREAD

**Issue by HTPH** [eritislami/evobot#901]
![unknown](https://user-images.githubusercontent.com/55040678/133881636-ad4d0d9a-8556-4a03-b03e-29393a6933cd.png)

**Comment by wolf-yuan-6115** [comment]
Please try to redeploy bot

**Comment by HTPH** [comment]
> Please try to redeploy bot
not workin
![unknown (1)](https://user-images.githubusercontent.com/55040678/133889249-30025f50-9655-4bb9-b74a-ba2bd0255477.png)
g
