### ISSUE TITLE
Query cost for YouTube lookup decrease

### ISSUE THREAD

**Issue by TheLostInPlace** [eritislami/evobot#904]
**Is your feature request related to a problem? Please describe.**
The current way the bot uses the YouTube api results in a query cost of 100 units from the quota, which is very expensive for what the bot does with the information returned.

**Describe the solution you'd like**
By replacing the "snippet" with "id", the YouTube api will only return a "videoId", which can be directly inserted into "https://www.youtube.com/watch?v=videoId" then passed into YouTubeDL. This lowers the cost of the search down to 20 units only, which is quite a considerable decrease, as with the current costs, the bot is limited to 100 YouTube searches per day, as opposed to 500.

**Describe alternatives you've considered**
This can be added as a toggle via the config.json for people who don't mind the expensive quota cost, however through my very basic js knowledge, it seems that the bot doesn't even use more than 90% of what the current API returns.

**Comment by eritislami** [comment]
Hey thanks for suggesting this, i managed to replace 3 of the 4 requests to use id instead of snippet, the last one couldn't work with just id because it would return the playlist with empty videos array.

![](https://i.imgur.com/4muWCfE.png)

**Comment by eritislami** [comment]
ab9db1f95260534ba9234e58115df63e183bd536

**Comment by TheLostInPlace** [comment]
I can confirm that editing "play.js" to use the suggestion I made makes the quota cost only 20 units. I'm now trying to figure out a way for it to work with playlists, as your screenshot demonstrates that replacing snippet with id breaks that feature.
