### ISSUE TITLE
Use of embed

### ISSUE THREAD

**Issue by zyiang1928** [eritislami/evobot#91]
Hello, can't you use embed in the include / play.js playingMessage section? if possible, why not use embed?

**Comment by eritislami** [comment]
Because discord automatically creates an embed from the music link from youtube/soundcloud, why add more code to do the same thing that is already done anyways?

**Comment by ParasDeshpande** [comment]
@zyiang1928 Well if you want to do that check #49 but that just adds more code for the same thing that discord does already as he said...

**Comment by zyiang1928** [comment]
Okay, thank you very much for the answer
