### ISSUE TITLE
Bug:  Cannot read properties of null (reading 'setVolumeLogarithmic')

### ISSUE THREAD

**Issue by pozhiloy-enotik** [eritislami/evobot#913]
**How To Reproduce**
1. Join a voice channel
2. Start playing music
3. Disconnect from a voice channel
4. Disconnect bot from a voice channel(need admin rights)
5. Click on volume down button ![image](https://user-images.githubusercontent.com/49619526/133940057-a2b6572f-a086-4a75-b213-2cc509f95147.png)
6. Bot crashes with an error 
```
/root/evobot/include/play.js:152
          queue.connection.dispatcher.setVolumeLogarithmic(queue.volume / 100);
                                      ^

TypeError: Cannot read properties of null (reading 'setVolumeLogarithmic')
    at ReactionCollector.<anonymous> (/root/evobot/include/play.js:152:39)
    at ReactionCollector.emit (node:events:406:35)
    at ReactionCollector.handleCollect (/root/evobot/node_modules/discord.js/src/structures/interfaces/Collector.js:100:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by eritislami** [comment]
Well, the dispatcher doesn't exist anymore after disconnecting the bot ¯\\_(ツ)_/¯. Seems like too much of an edge case to worry about it

**Comment by pozhiloy-enotik** [comment]
> 
> 
> Well, the dispatcher doesn't exist anymore after disconnecting the bot ¯\_(ツ)_/¯. Seems like too much of an edge case to worry about it

Yes, but after that the bot exits and you need to restart it manually
![image](https://user-images.githubusercontent.com/49619526/133990329-dc80dcbb-4f1f-4114-9031-b8187327cc69.png)

**Comment by eritislami** [comment]
https://pm2.keymetrics.io/
