### ISSUE TITLE
Bug: YouTube playlists being queued only add the first ten tracks

### ISSUE THREAD

**Issue by Koooper** [eritislami/evobot#925]
**Describe the bug**
Regardless of how many tracks a playlist has, only the first ten listed will be queued up.

**How To Reproduce**
1. Attempt to queue up a YouTube playlist with more than tracks with either !play or !playlist
2. View queue, only to realize the lack of tracks
3. disappointment
 
**Expected behavior**
All tracks in the playlist are to be added

**Environment (add if possible)**
* Node.js version: 16.9.1
* Environment: Heroku (free dyno)

**Comment by 3Demon** [comment]
@Koooper Are you tried to change MAX_PLAYLIST_SIZE in config.json?
