### ISSUE TITLE
Bug: pruning command not working

### ISSUE THREAD

**Issue by entertvl** [eritislami/evobot#927]
**Describe the bug**
`pruning` command now fails running on Docker.
Because config.json ignoring .dockerignore.
 
**Expected behavior**
I'm not sure if we should use config.json for state management. Another idea?

**Comment by entertvl** [comment]
https://github.com/eritislami/evobot/issues/926#issuecomment-925124568

**Comment by Koooper** [comment]
can replicate on heroku
