### ISSUE TITLE
How to create soundcloud client id 

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#93]
![Screenshot_20200624-140356](https://user-images.githubusercontent.com/53672750/85519656-a6657900-b623-11ea-92d2-be3321239950.png)

**Comment by mmoomocow** [comment]
see [this](https://github.com/zackradisic/node-soundcloud-downloader#client-id) project for how to get one without  the google form

**Comment by RakibHasanMunna1** [comment]
Not working ☹️

**Comment by mmoomocow** [comment]
Are you signed into an account?

**Comment by RakibHasanMunna1** [comment]
> Are you signed into an account?

Yes

**Comment by ParasDeshpande** [comment]
It will appear as <action-on-website>?client_id=something whenever you play a song or do something on their website, hope it helps @RakibHasanMunna1

**Comment by mmoomocow** [comment]
### Here is a step-by-step guide

1. sign in to an account
2. go to any page
3. open developer tools (ctrl/cmd + shift + i)
4. open the `Network` tab
5. reload page
6. look for anything that has `?client_id=`
7. click on that request and look at `headers`
8. look for the url
```
https://api-v2.soundcloud.com/me/play-history/tracks?client_id=SomeStringOfNumbersAndLetters&limit=25&offset=0&linked_partitioning=1&app_version=1593096385&app_locale=en
```
9. copy the client id, in the URL above it is `SomeStringOfNumbersAndLetters`

**Comment by RakibHasanMunna1** [comment]
> ### Here is a step-by-step guide
> 1. sign in to an account
> 2. go to any page
> 3. open developer tools (ctrl/cmd + shift + i)
> 4. open the `Network` tab
> 5. reload page
> 6. look for anything that has `?client_id=`
> 7. click on that request and look at `headers`
> 8. look for the url
> 
> ```
> https://api-v2.soundcloud.com/me/play-history/tracks?client_id=SomeStringOfNumbersAndLetters&limit=25&offset=0&linked_partitioning=1&app_version=1593096385&app_locale=en
> ```
> 
> 1. copy the client id, in the URL above it is `SomeStringOfNumbersAndLetters`

Mobile user

**Comment by eritislami** [comment]
> Mobile user

We can't help you with that, read the readme & try googling your problems.

**Comment by Klubuntu** [comment]
> https://api-v2.soundcloud.com

Thanks

**Comment by Klubuntu** [comment]
> ### Here is a step-by-step guide
> 1. sign in to an account
> 2. go to any page
> 3. open developer tools (ctrl/cmd + shift + i)
> 4. open the `Network` tab
> 5. reload page
> 6. look for anything that has `?client_id=`
> 7. click on that request and look at `headers`
> 8. look for the url
> 
> ```
> https://api-v2.soundcloud.com/me/play-history/tracks?client_id=SomeStringOfNumbersAndLetters&limit=25&offset=0&linked_partitioning=1&app_version=1593096385&app_locale=en
> ```
> 
> 9. copy the client id, in the URL above it is `SomeStringOfNumbersAndLetters`

Thanks ✅
