### ISSUE TITLE
Bug: Resume is not working

### ISSUE THREAD

**Issue by herculys** [eritislami/evobot#932]
Reacting with pause does pause, but resuming or /resume does not work.

using pt-br localization.

**Comment by Brskt** [comment]
I can confirm that I have this issue too with the default localization.

**Comment by eritislami** [comment]
It behaves weirdly with some node.js versions, I use 14.15.5 and haven't noticed any issues, as far as the code goes I can't do anything to make it work universally, there's just one method for pausing and resuming, nothing else can be done about it.

**Comment by herculys** [comment]
Was using 14.17.6 LTS before, downgraded to your version and is working as intended now big thanks.
Updating the requirements could be useful, it says _Node.js v14.0.0 or newer_ in the readme.
