### ISSUE TITLE
Function for playing mp3 files

### ISSUE THREAD

**Issue by Blaxers** [eritislami/evobot#936]
bot allows you to play single songs.
there is no command to play all songs contained in a folder.

**Comment by wolf-yuan-6115** [comment]
Playing mp3 file require FFmpeg encoder, which will decrease audio quality & use more resources.

Or we can use `js-mp3` but it still will eat more memory then usual, due to it pull all audio data into ArrayBuffer

**Comment by eritislami** [comment]
Closing as old and not planned.
