### ISSUE TITLE
why can't select the song in the search command

### ISSUE THREAD

**Issue by MuhaGX** [eritislami/evobot#939]
### Discussed in https://github.com/eritislami/evobot/discussions/938

<div type='discussions-op-text'>

<sup>Originally posted by **MuhaGX** September 24, 2021</sup>
![image](https://user-images.githubusercontent.com/70599137/134611784-169a3ea1-c37c-4f69-b833-faf85c6c7e25.png)
</div>

**Comment by sandrzejewskipl** [comment]
answer with "2", not "/2"

**Comment by eritislami** [comment]
Not a bug
