### ISSUE TITLE
Bug: /Resume command don't work

### ISSUE THREAD

**Issue by Angelico2102** [eritislami/evobot#943]
**Describe the bug**
If you pause a song with "/pause" and then use "/resume", the song won't play.

**Comment by imrit450** [comment]
I have this issue too.

**Comment by NikosProGamer** [comment]
put this:

`            queue.connection.dispatcher.pause();
            queue.connection.dispatcher.resume();`
in each command, and it should work then. this fixed it for me

**Comment by Angelico2102** [comment]
Thanks! Fixed :)

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot/issues/932#issuecomment-926159038
