### ISSUE TITLE
Bug: This code sometimes has errors in the background

### ISSUE THREAD

**Issue by kurumicute** [eritislami/evobot#951]
**Describe the bug**

This code sometimes has errors in the background, I don’t know why...

**How To Reproduce**
1.I don't know. He may happen once an hour.
 
**Expected behavior**
Sometimes playing music BOT will automatically close.

**Environment (add if possible)**
   work on my computer
* Node.js version: 16.9.1

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/90886946/134794163-5103749c-1201-4f9b-ac87-ad808d5eed34.png)

**Comment by drewburr** [comment]
@kurumicute could you tell us more about how your bot is setup? What version of Evobot are you running, and are you running this using Docker or with Node? Your config.json might help as well, but please be sure to remove all tokens and API keys

**Comment by kurumicute** [comment]
> @kurumicute could you tell us more about how your bot is setup? What version of Evobot are you running, and are you running this using Docker or with Node? Your config.json might help as well, but please be sure to remove all tokens and API keys

I use Node.js
![image](https://user-images.githubusercontent.com/90886946/136066842-02f321b9-7efb-4a85-b8fa-d56bed644345.png)
