### ISSUE TITLE
Add spotify search

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#96]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by ParasDeshpande** [comment]
Spotify does not allow the entire track to be played by other apps as they wont earn any revenue from ads. If that is allowed by spotify then the music can be played ad free by other apps and that would not be good for spotify. But what we can do is get the song name from spotify and find the same song on youtube and play it from there. So at most we can add a feature to play with spotify links. Spotify search would be kinda useless as at the end the music is going to be played from youtube anyway...

**Comment by eritislami** [comment]
Please stop posting duplicate issues
