### ISSUE TITLE
Bug: ReferenceError: Collection is not defined

### ISSUE THREAD

**Issue by NacreousDawn596** [eritislami/evobot#961]
**Describe the bug**
A description of what the bug is.

**How To Reproduce**
1.run it
2.then read it
 
**Expected behavior**
A description of what you expected to happen:
it should run :)

**Environment (add if possible)**
* Node.js version: v10.19.0

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by NacreousDawn596** [comment]
ReferenceError: Collection is not defined

**Comment by eritislami** [comment]
https://github.com/eritislami/evobot#requirements

If you're gonna post a stupid bug report at least read the requirements first.
