### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RakibHasanMunna1** [eritislami/evobot#97]
![Screenshot_20200625-134527](https://user-images.githubusercontent.com/53672750/85678696-88af1700-b6ea-11ea-8def-9bea84317f7b.png)

**Comment by mmoomocow** [comment]
I dont see the problem here, whats wrong?

**Comment by VirusLauncher** [comment]
This is not due to Evobot. This is glitch problem.

**Comment by ParasDeshpande** [comment]
But there's no visible problem... 😒 @VirusLauncher 
Well i see only two unrelated problems, his Phone Battery is on 7% and he is getting 0KB/s bandwidth...

**Comment by eritislami** [comment]
Not a bug, please follow the rules and dont create bug reports when really the issue is something else. Also stop creating multiple issues for the same thing or else i have to start taking actions against this.
