### ISSUE TITLE
Leave voicechannel when alone for 5 minutes

### ISSUE THREAD

**Issue by pquerner** [eritislami/evobot#999]
**Is your feature request related to a problem? Please describe.**
When the bot is left alone in the voicechannel, it keeps playing. The bot should leave after a few minutes when no humans are in the channel.

**Describe the solution you'd like**
The bot should leave the channel when left alone.

**Comment by Stuka1337** [comment]
> add this code to "index.js" :
> 
> ```
> client.on('voiceStateUpdate', (oldState, newState) => {
> 
>     let i = 300000; // 5 minutes in ms, you can change this.
> 
>     if (oldState.channelID !==  oldState.guild.me.voice.channelID || newState.channel) return;
> 
>         // How many people in channel
>               if (!(oldState.channel.members.size - 1))
>                   setTimeout(() => {
>                   if (!(oldState.channel.members.size - 1)){
>                       const queue = client.queue.get(oldState.guild.id);
>                       if(queue){
>                           client.queue.delete(oldState.guild.id);
>                           oldState.channel.leave();
>                           queue.textChannel.send("Leaving the voice channel because there is no one on the voice channel ...");
>                       }else{
>                           oldState.channel.leave();
>                       }
>                   }
>               }, i); wait for (i) ms
>   });
> ```
> 
> and Done! Source: Modified [code](https://stackoverflow.com/questions/64241703) . _You can follow the code at this link or just copy mine that's slightly modified._

Didn't work with my implementation, it doesn't understand the "wait" command, what to do?

**Comment by pquerner** [comment]
That line is a comment, so try remove it or commenting it 

`
              }, i); //wait for (i) ms
`

**Comment by Stuka1337** [comment]
> 

Code is executing fine now but it still doesn't work, queue keeps playing and the bot isn't leaving. Any fix? Or if possible please share your index.js so i can compare.
